// @ll/core/partner — the partnership primitive for two-person (dyad) collaborative learning.
// Language-agnostic: operates on user ids, pack ids, and generic activity records — NO language data.
// Pure logic only; the partnership / visibility / published-state ROWS are persisted by the app
// (apps/web/lib/partner-store.ts + Supabase), exactly as core/familiarity's state lives in the store.
// Deterministic by design — id + invite code are generated by the app layer and passed in, so every
// function here is pure and unit-testable. See DESIGN-partnered-learning.md §1.1 / §3.1.
import type { ProgressMetrics } from "../familiarity/scoring.js";

export type PartnershipStatus = "pending" | "active" | "paused" | "ended";

/** The link between two trusted learners, scoped to one pack (§1.3). Dyad-optimized: two member
 *  slots, invitee undefined until the invite is redeemed. Generalizes to N via a join table later. */
export interface Partnership {
  id: string;
  packId: string;
  members: [string, string?]; // [inviter, invitee?]
  status: PartnershipStatus;
  inviteCode?: string; // durable on the row, so the inviter can re-share
  createdAt: Date;
  updatedAt: Date;
}

/** Per-member privacy controls — each member governs what the OTHER may see. Default-permissive within
 *  an active trusted dyad, but always revocable (a toggle off hides the data at the next publish + read). */
export interface VisibilitySettings {
  shareActivity: boolean; // weekly metrics for the activity-visibility surface
  shareFamiliarity: boolean; // the familiarity projection (complementary SRS / teach-back; Phase 2)
  shareStreak: boolean; // contribute to the shared streak
  allowTeachBack: boolean; // may be prompted to record explanations for the partner (Phase 2)
}

/** Trusted-dyad default. Revocable per setting; nothing is shared until the partnership is `active`. */
export const DEFAULT_VISIBILITY: VisibilitySettings = {
  shareActivity: true,
  shareFamiliarity: true,
  shareStreak: true,
  allowTeachBack: true,
};

/** The activity half of what a member publishes for the partner to read (§1.1). The familiarity
 *  half is a FamiliarityProjection from ./familiarity-diff (Phase 2). */
export interface ActivityRecord {
  lastActiveDay: string; // YYYY-MM-DD (local); "" ⇒ never active
  metrics?: ProgressMetrics; // present only if shareActivity
}

const stamp = (p: Partnership, patch: Partial<Partnership>, now: Date): Partnership => ({
  ...p,
  ...patch,
  updatedAt: now,
});

/** Build a pending partnership. `id` + `code` come from the app layer (DB/`crypto`) so this stays pure. */
export function invite(id: string, packId: string, inviterId: string, code: string, now = new Date()): Partnership {
  return {
    id,
    packId,
    members: [inviterId, undefined],
    status: "pending",
    inviteCode: code,
    createdAt: now,
    updatedAt: now,
  };
}

/** Redeem an invite: pending → active once the invitee consents (the second half of mutual consent).
 *  Guards the trust boundary — you can't claim a non-pending link, a taken slot, or partner yourself. */
export function accept(p: Partnership, inviteeId: string, now = new Date()): Partnership {
  if (p.status !== "pending") throw new Error(`cannot accept a ${p.status} partnership`);
  if (p.members[1]) throw new Error("partnership already has a second member");
  if (p.members[0] === inviteeId) throw new Error("cannot partner with yourself");
  return stamp(p, { members: [p.members[0], inviteeId], status: "active" }, now);
}

/** No-shame exit: pause without penalty or guilt (the load-bearing dyad-survival mechanic). */
export function pause(p: Partnership, now = new Date()): Partnership {
  if (p.status !== "active") throw new Error(`cannot pause a ${p.status} partnership`);
  return stamp(p, { status: "paused" }, now);
}

export function resume(p: Partnership, now = new Date()): Partnership {
  if (p.status !== "paused") throw new Error(`cannot resume a ${p.status} partnership`);
  return stamp(p, { status: "active" }, now);
}

export function end(p: Partnership, now = new Date()): Partnership {
  if (p.status === "ended") return p;
  return stamp(p, { status: "ended" }, now);
}

export function isActive(p: Partnership): boolean {
  return p.status === "active";
}

/** The other member's user id (undefined if the invite is unclaimed or `userId` isn't a member). */
export function partnerOf(p: Partnership, userId: string): string | undefined {
  if (p.members[0] === userId) return p.members[1];
  if (p.members[1] === userId) return p.members[0];
  return undefined;
}

// ---- shared streak (derived; the solo Progress.streak is untouched — §1.5) ----

const DAY_MS = 86_400_000;
/** Parse a local YYYY-MM-DD to a UTC-noon timestamp (noon avoids DST/offset edge cases). */
function dayToMs(day: string): number {
  const [y, m, d] = day.split("-").map(Number);
  return Date.UTC(y ?? 1970, (m ?? 1) - 1, d ?? 1, 12);
}
/** Whole days from `a` to `b` (both YYYY-MM-DD); negative if b precedes a. */
function daysBetween(a: string, b: string): number {
  return Math.round((dayToMs(b) - dayToMs(a)) / DAY_MS);
}

/** Shared streak: advances only when BOTH partners were active *today*; freezes grant grace across a
 *  missed joint day without resetting. Derived from both published ActivityRecords + the stored shared
 *  `prev` ({count,lastDay}). Idempotent per day. `freezes` = grace days available to bridge a gap.
 *  MVP simplification: continuity is judged from `lastActiveDay` + `prev`, not a full per-day history. */
export function sharedStreak(
  a: ActivityRecord,
  b: ActivityRecord,
  today: string,
  prev: { count: number; lastDay: string } = { count: 0, lastDay: "" },
  freezes = 0,
): { count: number; lastDay: string } {
  const bothActiveToday = a.lastActiveDay === today && b.lastActiveDay === today;
  if (!bothActiveToday) return prev; // streak doesn't advance until both show up; no reset mid-day
  if (prev.lastDay === today) return prev; // already counted today (idempotent)
  if (prev.lastDay === "") return { count: 1, lastDay: today }; // first joint day
  const gap = daysBetween(prev.lastDay, today); // ≥ 1 here
  if (gap === 1) return { count: prev.count + 1, lastDay: today }; // consecutive
  if (gap - 1 <= freezes) return { count: prev.count + 1, lastDay: today }; // freeze bridges the gap
  return { count: 1, lastDay: today }; // gap too large → reset
}

// ---- partner session cadence (the STRUCTURED joint session — a daily/weekly review of solo work) ----

export type PartnerCadence = "daily" | "weekly";
export type PartnerActivityKind = "review-help" | "speak" | "teachback" | "story";

export interface PartnerSessionInputs {
  cadence: PartnerCadence;
  partnerCanHelpMe: number; // # items my partner knows that I'm weak/new on (from complementaryDiff)
  iCanHelpPartner: number; // the mirror — drives teach-back
  speakScenarioId?: string; // a scenario to produce together; omit ⇒ no speak step
  storyId?: string; // a shared text to close on; omit ⇒ no story step
  /** New words I locked in this window (recency proxy for effort; default 0). */
  myRecent?: number;
  /** New words my partner locked in this window (default 0). */
  partnerRecent?: number;
  /** Did my partner practice in this window? false ⇒ a light catch-up instead of a full review (default true). */
  partnerActive?: boolean;
}

export interface PartnerSessionItem {
  kind: PartnerActivityKind;
  ref?: string; // scenario / story id, where relevant
  count?: number; // # of words, for review-help / teachback
}

/** How the session is tilted by who did more solo work — drives the UI's framing line. */
export type PartnerEmphasis = "balanced" | "you-teach" | "partner-teaches" | "catch-up";

export interface PartnerSessionPlan {
  window: "today" | "this week";
  emphasis: PartnerEmphasis;
  items: PartnerSessionItem[];
  estMinutes: number;
}

/** A meaningful effort gap (in new words this window) before the session tilts toward teach vs. review. */
const EFFORT_GAP = 5;

/** Assemble the dyad's STRUCTURED joint session for the current cadence window — a guided pass that
 *  reviews each person's recent solo work TOGETHER, rather than the flat activity menu. Pedagogy order:
 *    1. review-help — drill what I'm weak on AND my partner knows (helping beats lonely drilling; §2/§5.6)
 *    2. speak       — produce together on a scenario (the conversation-first core)
 *    3. teachback   — I explain items my partner is shaky on (retrieval for me, input for them)
 *    4. story       — a shared text as a closer / conversation fuel
 *  Weekly widens the pass (it covers a week of solo work). ADAPTIVE to effort asymmetry: whoever did
 *  more this window does more TEACHING (their fresh words → teach-back); whoever did less gets WALKED
 *  THROUGH it (more review-help). If a partner hasn't practiced at all, it's a light catch-up + a nudge
 *  rather than a full review — so an uneven week doesn't produce a lopsided plan. Pure + language-agnostic. */
export function buildPartnerSession(inputs: PartnerSessionInputs): PartnerSessionPlan {
  const weekly = inputs.cadence === "weekly";
  const window = weekly ? "this week" : "today";

  // Partner hasn't shown up this window → don't build a full review around absent work; keep it light.
  if (inputs.partnerActive === false) {
    const items: PartnerSessionItem[] = [];
    if (inputs.speakScenarioId) items.push({ kind: "speak", ref: inputs.speakScenarioId });
    if (inputs.storyId) items.push({ kind: "story", ref: inputs.storyId });
    return { window, emphasis: "catch-up", items, estMinutes: Math.max(3, items.length * 4) };
  }

  const gap = (inputs.myRecent ?? 0) - (inputs.partnerRecent ?? 0);
  const emphasis: PartnerEmphasis = gap >= EFFORT_GAP ? "you-teach" : gap <= -EFFORT_GAP ? "partner-teaches" : "balanced";

  const items: PartnerSessionItem[] = [];
  // review-help (partner helps me): widened when they did more, trimmed when I did more.
  if (inputs.partnerCanHelpMe > 0) {
    const base = weekly ? 12 : 5;
    const cap = emphasis === "partner-teaches" ? base + 4 : emphasis === "you-teach" ? Math.ceil(base / 2) : base;
    items.push({ kind: "review-help", count: Math.min(inputs.partnerCanHelpMe, cap) });
  }
  if (inputs.speakScenarioId) items.push({ kind: "speak", ref: inputs.speakScenarioId });
  // teach-back (I teach partner): on weekly, or whenever I did more — boosted then.
  if ((weekly || emphasis === "you-teach") && inputs.iCanHelpPartner > 0) {
    items.push({ kind: "teachback", count: Math.min(inputs.iCanHelpPartner, emphasis === "you-teach" ? 8 : 5) });
  }
  if (inputs.storyId && (weekly || items.length < 2)) items.push({ kind: "story", ref: inputs.storyId });

  const estMinutes = items.reduce((m, it) => m + (it.kind === "review-help" ? Math.max(1, Math.ceil((it.count ?? 0) * 0.5)) : 4), 0);
  return { window, emphasis, items, estMinutes: Math.max(3, estMinutes) };
}
