// MACHINE-GENERATED by pipeline/src/run-breakdowns.ts (Opus 4.8). Word-by-word breakdowns + a one-line
// "how it fits" grammar takeaway for the pack's multi-word phrases/chunks, keyed by the exact (trimmed)
// `answer` string. Merged onto review items in index.ts and shown on the flashcard reveal
// (PhraseBreakdown). Regenerate with: pipeline/node_modules/.bin/tsx pipeline/src/run-breakdowns.ts
export interface PhraseBreakdownData {
  breakdown: { part: string; gloss: string }[];
  takeaway: string;
}

export const breakdowns: Record<string, PhraseBreakdownData> = {
  "Ајде да …": {
    "breakdown": [
      {
        "part": "Ајде",
        "gloss": "come on"
      },
      {
        "part": "да",
        "gloss": "let's"
      }
    ],
    "takeaway": "\"Ајде да\" plus a verb is the standard way to say \"let's do something.\""
  },
  "близу / далеку": {
    "breakdown": [
      {
        "part": "близу",
        "gloss": "near"
      },
      {
        "part": "далеку",
        "gloss": "far"
      }
    ],
    "takeaway": "Two simple location words that don't change form."
  },
  "брат / сестра": {
    "breakdown": [
      {
        "part": "брат",
        "gloss": "brother"
      },
      {
        "part": "сестра",
        "gloss": "sister"
      }
    ],
    "takeaway": "\"Брат\" is masculine; \"сестра\" ends in -а, marking it feminine."
  },
  "Важи. / Договорено.": {
    "breakdown": [
      {
        "part": "Важи",
        "gloss": "it holds/OK"
      },
      {
        "part": "Договорено",
        "gloss": "agreed"
      }
    ],
    "takeaway": "Both are fixed one-word replies; \"Договорено\" is a set past form meaning \"agreed.\""
  },
  "Ве молам": {
    "breakdown": [
      {
        "part": "Ве",
        "gloss": "you (formal)"
      },
      {
        "part": "молам",
        "gloss": "I ask/beg"
      }
    ],
    "takeaway": "The little pronoun \"ве\" (you) sits right before the verb \"молам\"."
  },
  "Во колку часот?": {
    "breakdown": [
      {
        "part": "Во",
        "gloss": "at/in"
      },
      {
        "part": "колку",
        "gloss": "how many/what"
      },
      {
        "part": "часот",
        "gloss": "the hour"
      }
    ],
    "takeaway": "\"часот\" has \"the\" stuck on the end (-от); literally \"at what the-hour?\""
  },
  "Во ред.": {
    "breakdown": [
      {
        "part": "Во",
        "gloss": "in"
      },
      {
        "part": "ред",
        "gloss": "order"
      }
    ],
    "takeaway": "Literally \"in order,\" this fixed phrase just means \"OK/alright.\""
  },
  "во центарот": {
    "breakdown": [
      {
        "part": "во",
        "gloss": "in/to"
      },
      {
        "part": "центарот",
        "gloss": "the centre"
      }
    ],
    "takeaway": "The little word \"во\" means in/to, and \"the\" is tacked on as \"-от\" at the end."
  },
  "вчера / денес / утре": {
    "breakdown": [
      {
        "part": "вчера",
        "gloss": "yesterday"
      },
      {
        "part": "денес",
        "gloss": "today"
      },
      {
        "part": "утре",
        "gloss": "tomorrow"
      }
    ],
    "takeaway": "Time words you can drop at the start or end of a sentence."
  },
  "да оставам порака": {
    "breakdown": [
      {
        "part": "да",
        "gloss": "to (particle)"
      },
      {
        "part": "оставам",
        "gloss": "I leave"
      },
      {
        "part": "порака",
        "gloss": "message"
      }
    ],
    "takeaway": "The particle \"да\" plus an \"I\"-form verb makes the \"to do\" idea; the noun follows."
  },
  "Дали е ... таму?": {
    "breakdown": [
      {
        "part": "Дали",
        "gloss": "question word"
      },
      {
        "part": "е",
        "gloss": "is"
      },
      {
        "part": "...",
        "gloss": "(name)"
      },
      {
        "part": "таму",
        "gloss": "there"
      }
    ],
    "takeaway": "\"Дали\" flags a yes/no question; \"е\" is \"is\" and \"таму\" means \"there.\""
  },
  "два, три, четири, пет": {
    "breakdown": [
      {
        "part": "два",
        "gloss": "two"
      },
      {
        "part": "три",
        "gloss": "three"
      },
      {
        "part": "четири",
        "gloss": "four"
      },
      {
        "part": "пет",
        "gloss": "five"
      }
    ],
    "takeaway": "These are the basic counting numbers two through five, each a single fixed word."
  },
  "денар / денари": {
    "breakdown": [
      {
        "part": "денар",
        "gloss": "denar (one)"
      },
      {
        "part": "денари",
        "gloss": "denars (many)"
      }
    ],
    "takeaway": "Add -и to make the plural: one денар, many денари."
  },
  "дете / деца": {
    "breakdown": [
      {
        "part": "дете",
        "gloss": "child"
      },
      {
        "part": "деца",
        "gloss": "children"
      }
    ],
    "takeaway": "\"Дете\" is one child; \"деца\" is its irregular plural, children."
  },
  "Добар ден": {
    "breakdown": [
      {
        "part": "Добар",
        "gloss": "good (masculine)"
      },
      {
        "part": "ден",
        "gloss": "day"
      }
    ],
    "takeaway": "The adjective \"добар\" takes a masculine form to match the masculine noun \"ден.\""
  },
  "Добро сум, фала.": {
    "breakdown": [
      {
        "part": "Добро",
        "gloss": "well/good"
      },
      {
        "part": "сум",
        "gloss": "I am"
      },
      {
        "part": "фала",
        "gloss": "thanks"
      }
    ],
    "takeaway": "\"Сум\" means \"I am\"; \"добро\" describes how, and the little verb comes second."
  },
  "Добро утро": {
    "breakdown": [
      {
        "part": "Добро",
        "gloss": "good (neuter)"
      },
      {
        "part": "утро",
        "gloss": "morning"
      }
    ],
    "takeaway": "The adjective \"добро\" takes a neuter ending to match the neuter noun \"утро\"."
  },
  "Дома ли е …?": {
    "breakdown": [
      {
        "part": "Дома",
        "gloss": "home"
      },
      {
        "part": "ли",
        "gloss": "question marker"
      },
      {
        "part": "е",
        "gloss": "is"
      }
    ],
    "takeaway": "The little word \"ли\" turns it into a yes/no question; \"е\" means \"is.\""
  },
  "Драго ми е": {
    "breakdown": [
      {
        "part": "Драго",
        "gloss": "pleasant"
      },
      {
        "part": "ми",
        "gloss": "to me"
      },
      {
        "part": "е",
        "gloss": "is"
      }
    ],
    "takeaway": "Literally \"it is pleasant to me\"; the little \"ми\" (to me) sits before \"е.\""
  },
  "еден / една / едно": {
    "breakdown": [
      {
        "part": "еден",
        "gloss": "one (masculine)"
      },
      {
        "part": "една",
        "gloss": "one (feminine)"
      },
      {
        "part": "едно",
        "gloss": "one (neuter)"
      }
    ],
    "takeaway": "\"One\" changes ending to match the noun's gender: -en, -na, -no."
  },
  "едно кило": {
    "breakdown": [
      {
        "part": "едно",
        "gloss": "one/a (neuter)"
      },
      {
        "part": "кило",
        "gloss": "kilo"
      }
    ],
    "takeaway": "\"Едно\" is the neuter form of \"a/one,\" matching the neuter noun \"кило.\""
  },
  "Едно пиво, ве молам": {
    "breakdown": [
      {
        "part": "Едно",
        "gloss": "one (neuter)"
      },
      {
        "part": "пиво",
        "gloss": "beer"
      },
      {
        "part": "ве",
        "gloss": "you (polite)"
      },
      {
        "part": "молам",
        "gloss": "I ask/beg"
      }
    ],
    "takeaway": "\"Едно\" is the neuter \"one\" to match \"пиво\"; \"ве молам\" (I beg you) is the polite \"please.\""
  },
  "Едно пиво, ве молам.": {
    "breakdown": [
      {
        "part": "Едно",
        "gloss": "one (neuter)"
      },
      {
        "part": "пиво",
        "gloss": "beer"
      },
      {
        "part": "ве",
        "gloss": "you"
      },
      {
        "part": "молам",
        "gloss": "I ask/beg"
      }
    ],
    "takeaway": "Едно takes the -о form to match neuter пиво; ве молам is the fixed way to say please."
  },
  "жена / маж": {
    "breakdown": [
      {
        "part": "жена",
        "gloss": "woman/wife"
      },
      {
        "part": "маж",
        "gloss": "man/husband"
      }
    ],
    "takeaway": "\"Жена\" (feminine, -а) also means wife; \"маж\" (masculine) also means husband."
  },
  "Живеам во …": {
    "breakdown": [
      {
        "part": "Живеам",
        "gloss": "I live"
      },
      {
        "part": "во",
        "gloss": "in"
      }
    ],
    "takeaway": "The verb ending \"-ам\" already means \"I,\" so no separate word for \"I\" is needed."
  },
  "Зборувам малку.": {
    "breakdown": [
      {
        "part": "Зборувам",
        "gloss": "I speak"
      },
      {
        "part": "малку",
        "gloss": "a little"
      }
    ],
    "takeaway": "The -ам ending shows I; малку (a little) follows the verb."
  },
  "и / ама / затоа": {
    "breakdown": [
      {
        "part": "и",
        "gloss": "and"
      },
      {
        "part": "ама",
        "gloss": "but"
      },
      {
        "part": "затоа",
        "gloss": "so/therefore"
      }
    ],
    "takeaway": "These little linking words join sentences; they sit between the two parts they connect."
  },
  "Извинете, ама …": {
    "breakdown": [
      {
        "part": "Извинете",
        "gloss": "excuse me"
      },
      {
        "part": ",",
        "gloss": "pause"
      },
      {
        "part": "ама",
        "gloss": "but"
      },
      {
        "part": "…",
        "gloss": "(fill in)"
      }
    ],
    "takeaway": "\"Извинете\" is a polite command form; \"ама\" is a small linking word meaning \"but.\""
  },
  "Има проблем.": {
    "breakdown": [
      {
        "part": "Има",
        "gloss": "there is"
      },
      {
        "part": "проблем",
        "gloss": "problem"
      }
    ],
    "takeaway": "\"Има\" alone means \"there is,\" with the noun placed right after it."
  },
  "Имам брат и сестра.": {
    "breakdown": [
      {
        "part": "Имам",
        "gloss": "I have"
      },
      {
        "part": "брат",
        "gloss": "brother"
      },
      {
        "part": "и",
        "gloss": "and"
      },
      {
        "part": "сестра",
        "gloss": "sister"
      }
    ],
    "takeaway": "\"Имам\" is \"I have\"; \"и\" simply joins the two nouns, just like English \"and.\""
  },
  "Имате ли …?": {
    "breakdown": [
      {
        "part": "Имате",
        "gloss": "you have (formal)"
      },
      {
        "part": "ли",
        "gloss": "question marker"
      }
    ],
    "takeaway": "The \"-ате\" ending marks formal \"you\", and \"ли\" makes it a yes/no question."
  },
  "Јас се викам...": {
    "breakdown": [
      {
        "part": "Јас",
        "gloss": "I"
      },
      {
        "part": "се",
        "gloss": "self"
      },
      {
        "part": "викам",
        "gloss": "I call"
      }
    ],
    "takeaway": "Literally \"I call myself\"; the little word \"се\" goes just before the verb \"викам.\""
  },
  "Јас сум …": {
    "breakdown": [
      {
        "part": "Јас",
        "gloss": "I"
      },
      {
        "part": "сум",
        "gloss": "am"
      }
    ],
    "takeaway": "сум is the verb am; Јас (I) is optional since the ending already shows who."
  },
  "Јас сум од...": {
    "breakdown": [
      {
        "part": "Јас",
        "gloss": "I"
      },
      {
        "part": "сум",
        "gloss": "am"
      },
      {
        "part": "од",
        "gloss": "from"
      }
    ],
    "takeaway": "\"Сум\" is \"am\"; \"од\" means \"from\" and a place name follows it."
  },
  "Каде да се видиме?": {
    "breakdown": [
      {
        "part": "Каде",
        "gloss": "where"
      },
      {
        "part": "да",
        "gloss": "shall/to"
      },
      {
        "part": "се",
        "gloss": "each other"
      },
      {
        "part": "видиме",
        "gloss": "we see"
      }
    ],
    "takeaway": "\"да\" sets up \"shall we,\" and the little \"се\" sits right before the verb meaning \"each other.\""
  },
  "каде е": {
    "breakdown": [
      {
        "part": "каде",
        "gloss": "where"
      },
      {
        "part": "е",
        "gloss": "is"
      }
    ],
    "takeaway": "\"Е\" is \"is\" (from сум); it follows the question word \"каде.\""
  },
  "Каде е …?": {
    "breakdown": [
      {
        "part": "Каде",
        "gloss": "where"
      },
      {
        "part": "е",
        "gloss": "is"
      }
    ],
    "takeaway": "\"Е\" is the \"is\" form of сум; the question word comes first."
  },
  "Како се вели … на македонски?": {
    "breakdown": [
      {
        "part": "Како",
        "gloss": "how"
      },
      {
        "part": "се",
        "gloss": "self (reflexive)"
      },
      {
        "part": "вели",
        "gloss": "says"
      },
      {
        "part": "на",
        "gloss": "in/on"
      },
      {
        "part": "македонски",
        "gloss": "Macedonian"
      }
    ],
    "takeaway": "\"Се вели\" means \"is said\"; \"на\" plus the language names how to say it."
  },
  "Како се викаш?": {
    "breakdown": [
      {
        "part": "Како",
        "gloss": "how"
      },
      {
        "part": "се",
        "gloss": "self"
      },
      {
        "part": "викаш",
        "gloss": "you call"
      }
    ],
    "takeaway": "Literally \"how do you call yourself\"; the little \"се\" sits right before the verb \"викаш.\""
  },
  "Како си?": {
    "breakdown": [
      {
        "part": "Како",
        "gloss": "how"
      },
      {
        "part": "си",
        "gloss": "you are (informal)"
      }
    ],
    "takeaway": "\"Си\" is the informal \"you are\" form of сум; it follows the question word."
  },
  "Како сте?": {
    "breakdown": [
      {
        "part": "Како",
        "gloss": "how"
      },
      {
        "part": "сте",
        "gloss": "you are (formal/plural)"
      }
    ],
    "takeaway": "\"Сте\" is the polite/plural \"you are\" form of сум, used for respect."
  },
  "Ќе …": {
    "breakdown": [
      {
        "part": "Ќе",
        "gloss": "will (future)"
      }
    ],
    "takeaway": "Put \"ќе\" right before the verb to make the future tense."
  },
  "Ќе се видиме.": {
    "breakdown": [
      {
        "part": "Ќе",
        "gloss": "will"
      },
      {
        "part": "се",
        "gloss": "each other"
      },
      {
        "part": "видиме",
        "gloss": "we see"
      }
    ],
    "takeaway": "\"Ќе\" makes it future; \"се\" (before the verb) adds \"each other\"; -ме means \"we\"."
  },
  "Колку чини килото?": {
    "breakdown": [
      {
        "part": "Колку",
        "gloss": "how much"
      },
      {
        "part": "чини",
        "gloss": "costs"
      },
      {
        "part": "килото",
        "gloss": "the kilo"
      }
    ],
    "takeaway": "\"The\" is added onto the end of \"кило\" as \"-то\"; the question just uses \"how much costs the kilo.\""
  },
  "колку чини?": {
    "breakdown": [
      {
        "part": "колку",
        "gloss": "how much"
      },
      {
        "part": "чини",
        "gloss": "it costs"
      }
    ],
    "takeaway": "\"Чини\" literally means \"it costs\"; ask price with \"колку\" first."
  },
  "Колку чини?": {
    "breakdown": [
      {
        "part": "Колку",
        "gloss": "how much"
      },
      {
        "part": "чини",
        "gloss": "it costs"
      }
    ],
    "takeaway": "\"Чини\" is an -и verb meaning \"it costs\"; \"колку\" comes first to ask the amount."
  },
  "мајка / татко": {
    "breakdown": [
      {
        "part": "мајка",
        "gloss": "mother"
      },
      {
        "part": "татко",
        "gloss": "father"
      }
    ],
    "takeaway": "\"Мајка\" is feminine, \"татко\" masculine — basic family nouns."
  },
  "Ми се допаѓа.": {
    "breakdown": [
      {
        "part": "Ми",
        "gloss": "to me"
      },
      {
        "part": "се",
        "gloss": "reflexive particle"
      },
      {
        "part": "допаѓа",
        "gloss": "is pleasing"
      }
    ],
    "takeaway": "Literally \"it pleases to me\"; the little pronoun \"ми\" and particle \"се\" sit before the verb."
  },
  "Мило ми е.": {
    "breakdown": [
      {
        "part": "Мило",
        "gloss": "pleasant"
      },
      {
        "part": "ми",
        "gloss": "to me"
      },
      {
        "part": "е",
        "gloss": "is"
      }
    ],
    "takeaway": "Literally it's pleasant to me; the little pronoun ми sits before the verb е."
  },
  "Мислам дека …": {
    "breakdown": [
      {
        "part": "Мислам",
        "gloss": "I think"
      },
      {
        "part": "дека",
        "gloss": "that"
      }
    ],
    "takeaway": "The verb ending -ам shows \"I\"; \"дека\" links to whatever clause you add next."
  },
  "Може ли …?": {
    "breakdown": [
      {
        "part": "Може",
        "gloss": "it is possible/can"
      },
      {
        "part": "ли",
        "gloss": "question marker"
      }
    ],
    "takeaway": "The particle \"ли\" turns the statement into a yes/no question, sitting after the verb."
  },
  "Можете ли да повторите?": {
    "breakdown": [
      {
        "part": "Можете",
        "gloss": "you can (formal)"
      },
      {
        "part": "ли",
        "gloss": "question word"
      },
      {
        "part": "да",
        "gloss": "to (particle)"
      },
      {
        "part": "повторите",
        "gloss": "you repeat"
      }
    ],
    "takeaway": "\"Ли\" turns it into a question; \"да\" links \"can\" to a second verb."
  },
  "Можете ли да помогнете?": {
    "breakdown": [
      {
        "part": "Можете",
        "gloss": "you can"
      },
      {
        "part": "ли",
        "gloss": "question word"
      },
      {
        "part": "да",
        "gloss": "to"
      },
      {
        "part": "помогнете",
        "gloss": "help"
      },
      {
        "part": "?",
        "gloss": "question"
      }
    ],
    "takeaway": "\"Ли\" after the verb turns it into a yes/no question; \"да\" links \"can\" to the second verb."
  },
  "мојот / мојата": {
    "breakdown": [
      {
        "part": "мојот",
        "gloss": "my (masculine)"
      },
      {
        "part": "мојата",
        "gloss": "my (feminine)"
      }
    ],
    "takeaway": "\"My\" changes to match gender: \"-от\" for masculine nouns, \"-ата\" for feminine ones."
  },
  "На колку години си?": {
    "breakdown": [
      {
        "part": "На",
        "gloss": "at/on"
      },
      {
        "part": "колку",
        "gloss": "how many"
      },
      {
        "part": "години",
        "gloss": "years"
      },
      {
        "part": "си",
        "gloss": "you are"
      }
    ],
    "takeaway": "Macedonian asks \"at how many years are you?\"; \"си\" is the \"you are\" form of сум."
  },
  "Не знам.": {
    "breakdown": [
      {
        "part": "Не",
        "gloss": "not"
      },
      {
        "part": "знам",
        "gloss": "I know"
      }
    ],
    "takeaway": "\"Не\" before the verb means \"not\"; -ам shows the speaker is \"I.\""
  },
  "Не ми се допаѓа.": {
    "breakdown": [
      {
        "part": "Не",
        "gloss": "not"
      },
      {
        "part": "ми",
        "gloss": "to me"
      },
      {
        "part": "се",
        "gloss": "reflexive particle"
      },
      {
        "part": "допаѓа",
        "gloss": "is pleasing"
      }
    ],
    "takeaway": "Add \"не\" at the front to make it negative; the little words \"ми се\" still sit before the verb."
  },
  "Не работи.": {
    "breakdown": [
      {
        "part": "Не",
        "gloss": "not"
      },
      {
        "part": "работи",
        "gloss": "it works"
      },
      {
        "part": ".",
        "gloss": "end"
      }
    ],
    "takeaway": "Put \"не\" right before the verb to make it negative; the verb ending -и already means \"it.\""
  },
  "Не разбирам зошто.": {
    "breakdown": [
      {
        "part": "Не",
        "gloss": "not"
      },
      {
        "part": "разбирам",
        "gloss": "I understand"
      },
      {
        "part": "зошто",
        "gloss": "why"
      },
      {
        "part": ".",
        "gloss": "end"
      }
    ],
    "takeaway": "\"Не\" before the verb makes it negative; \"зошто\" (why) comes at the end here."
  },
  "Не разбирам.": {
    "breakdown": [
      {
        "part": "Не",
        "gloss": "not"
      },
      {
        "part": "разбирам",
        "gloss": "I understand"
      }
    ],
    "takeaway": "Put \"не\" before the verb to say \"not\"; the ending -ам shows \"I.\""
  },
  "нека ме повика": {
    "breakdown": [
      {
        "part": "нека",
        "gloss": "let/have (particle)"
      },
      {
        "part": "ме",
        "gloss": "me"
      },
      {
        "part": "повика",
        "gloss": "he calls"
      },
      {
        "part": "",
        "gloss": ""
      }
    ],
    "takeaway": "\"Нека\" means \"let him\"; the little pronoun \"ме\" sits right before the verb."
  },
  "ова / тоа": {
    "breakdown": [
      {
        "part": "ова",
        "gloss": "this"
      },
      {
        "part": "тоа",
        "gloss": "that"
      }
    ],
    "takeaway": "Two pointing words: ова is near you (this), тоа is farther away (that)."
  },
  "Ова не е …": {
    "breakdown": [
      {
        "part": "Ова",
        "gloss": "this"
      },
      {
        "part": "не",
        "gloss": "not"
      },
      {
        "part": "е",
        "gloss": "is"
      },
      {
        "part": "…",
        "gloss": "(fill in)"
      }
    ],
    "takeaway": "\"Не\" sits before \"е\" (is) to say \"isn't\"; \"ова\" is the neuter form of \"this.\""
  },
  "Од … сум.": {
    "breakdown": [
      {
        "part": "Од",
        "gloss": "from"
      },
      {
        "part": "сум",
        "gloss": "am"
      }
    ],
    "takeaway": "Od means from; сум (am) comes at the end after the place."
  },
  "Од каде си?": {
    "breakdown": [
      {
        "part": "Од",
        "gloss": "from"
      },
      {
        "part": "каде",
        "gloss": "where"
      },
      {
        "part": "си",
        "gloss": "you are"
      }
    ],
    "takeaway": "\"Си\" is \"you are\" (from сум); it sits after \"каде\" to make the question."
  },
  "Оставете порака.": {
    "breakdown": [
      {
        "part": "Оставете",
        "gloss": "leave (you-all)"
      },
      {
        "part": "порака",
        "gloss": "message"
      }
    ],
    "takeaway": "\"Оставете\" is a polite/plural command; the thing to leave follows the verb."
  },
  "педесет / сто / сто и педесет": {
    "breakdown": [
      {
        "part": "педесет",
        "gloss": "fifty"
      },
      {
        "part": "сто",
        "gloss": "hundred"
      },
      {
        "part": "сто",
        "gloss": "hundred"
      },
      {
        "part": "и",
        "gloss": "and"
      },
      {
        "part": "педесет",
        "gloss": "fifty"
      }
    ],
    "takeaway": "Build bigger numbers by joining with и: сто и педесет means a hundred and fifty."
  },
  "Побавно, ве молам.": {
    "breakdown": [
      {
        "part": "Побавно",
        "gloss": "slower"
      },
      {
        "part": "ве",
        "gloss": "you (polite)"
      },
      {
        "part": "молам",
        "gloss": "I beg/please"
      }
    ],
    "takeaway": "\"По-\" makes \"more/slower\"; \"ве молам\" is the set phrase for \"please.\""
  },
  "половина кило": {
    "breakdown": [
      {
        "part": "половина",
        "gloss": "half"
      },
      {
        "part": "кило",
        "gloss": "kilo"
      }
    ],
    "takeaway": "Just put \"половина\" (half) before the noun to say \"half a kilo.\""
  },
  "Работам како …": {
    "breakdown": [
      {
        "part": "Работам",
        "gloss": "I work"
      },
      {
        "part": "како",
        "gloss": "as/like"
      }
    ],
    "takeaway": "\"Работам\" ends in \"-ам\" for \"I,\" and \"како\" links to the job you name."
  },
  "Сакам …": {
    "breakdown": [
      {
        "part": "Сакам",
        "gloss": "I want"
      }
    ],
    "takeaway": "The \"-ам\" ending shows the doer is \"I\"; no separate word for \"I\" needed."
  },
  "Сакам да …": {
    "breakdown": [
      {
        "part": "Сакам",
        "gloss": "I want"
      },
      {
        "part": "да",
        "gloss": "to"
      }
    ],
    "takeaway": "\"Сакам\" means I want, and \"да\" links it to a following verb, like English \"to.\""
  },
  "Сакам да вратам.": {
    "breakdown": [
      {
        "part": "Сакам",
        "gloss": "I want"
      },
      {
        "part": "да",
        "gloss": "to"
      },
      {
        "part": "вратам",
        "gloss": "return"
      },
      {
        "part": ".",
        "gloss": "end"
      }
    ],
    "takeaway": "\"Сакам да\" plus a second verb means \"I want to…\"; both verbs take an \"I\" ending."
  },
  "Само тоа, фала.": {
    "breakdown": [
      {
        "part": "Само",
        "gloss": "only"
      },
      {
        "part": "тоа",
        "gloss": "that"
      },
      {
        "part": "фала",
        "gloss": "thanks"
      }
    ],
    "takeaway": "\"Само тоа\" literally means \"only that,\" a set way to say \"that's all.\""
  },
  "Свртете лево.": {
    "breakdown": [
      {
        "part": "Свртете",
        "gloss": "turn (command)"
      },
      {
        "part": "лево",
        "gloss": "left"
      }
    ],
    "takeaway": "\"Свртете\" is the polite command form (telling someone to do something), followed by the direction."
  },
  "Се согласувам.": {
    "breakdown": [
      {
        "part": "Се",
        "gloss": "self (reflexive)"
      },
      {
        "part": "согласувам",
        "gloss": "I agree"
      }
    ],
    "takeaway": "The little word \"се\" sits before the verb; the -ам ending means \"I\"."
  },
  "Сѐ уште учам.": {
    "breakdown": [
      {
        "part": "Сѐ",
        "gloss": "all/still"
      },
      {
        "part": "уште",
        "gloss": "still/yet"
      },
      {
        "part": "учам",
        "gloss": "I learn"
      }
    ],
    "takeaway": "\"Сѐ уште\" is the fixed phrase for \"still\"; ending -ам marks \"I.\""
  },
  "Сметката, ве молам": {
    "breakdown": [
      {
        "part": "Сметка",
        "gloss": "bill"
      },
      {
        "part": "-та",
        "gloss": "the"
      },
      {
        "part": "ве",
        "gloss": "you (polite)"
      },
      {
        "part": "молам",
        "gloss": "I ask"
      }
    ],
    "takeaway": "\"The\" is the ending -та stuck on \"сметка\"; \"ве молам\" adds the polite \"please.\""
  },
  "Сметката, ве молам.": {
    "breakdown": [
      {
        "part": "Сметка",
        "gloss": "bill"
      },
      {
        "part": "-та",
        "gloss": "the"
      },
      {
        "part": "ве",
        "gloss": "you"
      },
      {
        "part": "молам",
        "gloss": "I ask"
      }
    ],
    "takeaway": "The word for the sticks onto the end: сметка + та = the bill."
  },
  "сум / си / е": {
    "breakdown": [
      {
        "part": "сум",
        "gloss": "I am"
      },
      {
        "part": "си",
        "gloss": "you are"
      },
      {
        "part": "е",
        "gloss": "he/she/it is"
      }
    ],
    "takeaway": "These are the forms of \"to be\" — each ending shows who: I, you, or he/she/it."
  },
  "тука / таму": {
    "breakdown": [
      {
        "part": "тука",
        "gloss": "here"
      },
      {
        "part": "таму",
        "gloss": "there"
      }
    ],
    "takeaway": "Two basic place words: \"тука\" is here, \"таму\" is there."
  },
  "убаво / грозно": {
    "breakdown": [
      {
        "part": "убаво",
        "gloss": "nice"
      },
      {
        "part": "грозно",
        "gloss": "awful"
      }
    ],
    "takeaway": "Both end in -о, the neuter form used for general \"it's nice/awful\"."
  },
  "Учам македонски": {
    "breakdown": [
      {
        "part": "Учам",
        "gloss": "I learn"
      },
      {
        "part": "македонски",
        "gloss": "Macedonian"
      }
    ],
    "takeaway": "The ending -ам on \"учам\" already means \"I,\" so no separate word for \"I\" is needed."
  },
  "Учам македонски.": {
    "breakdown": [
      {
        "part": "Учам",
        "gloss": "I learn"
      },
      {
        "part": "македонски",
        "gloss": "Macedonian"
      }
    ],
    "takeaway": "The -ам ending on учам already means I, so no extra word for I."
  },
  "Уште еднаш, ве молам.": {
    "breakdown": [
      {
        "part": "Уште",
        "gloss": "more/again"
      },
      {
        "part": "еднаш",
        "gloss": "once"
      },
      {
        "part": "ве",
        "gloss": "you (polite)"
      },
      {
        "part": "молам",
        "gloss": "I beg/please"
      }
    ],
    "takeaway": "\"Уште еднаш\" literally means \"one more time\"; \"ве молам\" adds \"please.\""
  },
  "шест, седум, осум, девет, десет": {
    "breakdown": [
      {
        "part": "шест",
        "gloss": "six"
      },
      {
        "part": "седум",
        "gloss": "seven"
      },
      {
        "part": "осум",
        "gloss": "eight"
      },
      {
        "part": "девет",
        "gloss": "nine"
      },
      {
        "part": "десет",
        "gloss": "ten"
      }
    ],
    "takeaway": "These are the counting numbers six through ten, each a single fixed word."
  },
  "Што значи …?": {
    "breakdown": [
      {
        "part": "Што",
        "gloss": "what"
      },
      {
        "part": "значи",
        "gloss": "means"
      }
    ],
    "takeaway": "A simple question: \"што\" (what) plus the verb \"значи\" (means)."
  },
  "Што ќе сакате?": {
    "breakdown": [
      {
        "part": "Што",
        "gloss": "what"
      },
      {
        "part": "ќе",
        "gloss": "will (future)"
      },
      {
        "part": "сакате",
        "gloss": "you want (formal)"
      }
    ],
    "takeaway": "The particle ќе makes it future; the -те ending is the polite/plural you."
  },
  "Што правеше?": {
    "breakdown": [
      {
        "part": "Што",
        "gloss": "what"
      },
      {
        "part": "правеше",
        "gloss": "you were doing"
      }
    ],
    "takeaway": "Question starts with \"што\"; the ending -еше is the past \"you were doing\"."
  },
  "Што работиш?": {
    "breakdown": [
      {
        "part": "Што",
        "gloss": "what"
      },
      {
        "part": "работиш",
        "gloss": "you do/work"
      }
    ],
    "takeaway": "The -иш ending means you (one person); no separate word for you is needed."
  }
};
