// MACHINE-GENERATED by pipeline/src/run-chapters.ts from pipeline/output/curriculum-mk.json.
// The course spine: chapter 0 (letters & sounds) + 12 ordered chapters over content that already exists (artifacts join by the
// `gen-<chapterId>` id convention / tags — see packages/core/src/chapters). Edit the maps in
// run-chapters.ts and re-run; don't hand-edit this file.
import type { Chapter } from "@ll/pack-schema";

export const chapters: Chapter[] = [
  {
    "id": "s0-letters",
    "order": 0,
    "stage": 0,
    "stageTitle": "Decode & survive",
    "title": "Letters & sounds",
    "shortTitle": "Letters & sounds",
    "cefr": "pre-A1",
    "goal": "read and say any Macedonian word",
    "kind": "script"
  },
  {
    "id": "s0-repair",
    "order": 1,
    "stage": 0,
    "stageTitle": "Decode & survive",
    "title": "First words: I am…, I don't understand",
    "shortTitle": "First words",
    "cefr": "pre-A1",
    "goal": "say who you are, and keep going when you don't understand",
    "wordTags": [
      "question words"
    ]
  },
  {
    "id": "s0-greet",
    "order": 2,
    "stage": 0,
    "stageTitle": "Decode & survive",
    "title": "Hello, how are you?",
    "shortTitle": "Hello, how are you?",
    "cefr": "pre-A1",
    "goal": "greet people, ask simple questions, and choose casual ти or polite вие",
    "wordTags": [
      "pronouns",
      "this & that",
      "greeting",
      "social"
    ]
  },
  {
    "id": "s0-survive",
    "order": 3,
    "stage": 0,
    "stageTitle": "Decode & survive",
    "title": "Numbers and a first purchase",
    "shortTitle": "Numbers & prices",
    "cefr": "pre-A1",
    "goal": "count, point at things, and ask what they cost",
    "wordTags": [
      "numbers",
      "common adverbs"
    ]
  },
  {
    "id": "s1-cafe-order",
    "order": 4,
    "stage": 1,
    "stageTitle": "Core situations",
    "title": "At the café: order and pay",
    "shortTitle": "At the café",
    "cefr": "A1",
    "goal": "order a drink, ask for the bill, and pay",
    "extraIds": [
      "bar-order-a-drink",
      "ana-coffee",
      "cafe",
      "cafe-order-gap",
      "w-order-coffee"
    ],
    "wordTags": [
      "food & drink",
      "drinks",
      "ordering",
      "paying"
    ]
  },
  {
    "id": "s1-greet-intro",
    "order": 5,
    "stage": 1,
    "stageTitle": "Core situations",
    "title": "Meeting someone new",
    "shortTitle": "Meeting people",
    "cefr": "A1",
    "goal": "say your name, where you're from and what you do",
    "extraIds": [
      "bar-small-talk",
      "gen-introductions",
      "w-greet-name",
      "w-from"
    ],
    "wordTags": [
      "common verbs",
      "introductions"
    ]
  },
  {
    "id": "s1-market",
    "order": 6,
    "stage": 1,
    "stageTitle": "Core situations",
    "title": "At the market",
    "shortTitle": "At the market",
    "cefr": "A1",
    "goal": "buy fruit, bread and more, by the kilo",
    "extraIds": [
      "gen-shopping",
      "w-ask-price"
    ],
    "wordTags": [
      "money & shopping",
      "common adjectives",
      "shopping"
    ]
  },
  {
    "id": "s1-directions",
    "order": 7,
    "stage": 1,
    "stageTitle": "Core situations",
    "title": "Finding your way",
    "shortTitle": "Finding your way",
    "cefr": "A1",
    "goal": "ask for directions and follow them",
    "extraIds": [
      "gen-directions"
    ],
    "wordTags": [
      "places & travel",
      "prepositions",
      "directions"
    ]
  },
  {
    "id": "s2-smalltalk",
    "order": 8,
    "stage": 2,
    "stageTitle": "Connect & sustain",
    "title": "Likes, opinions and plans",
    "shortTitle": "Likes & plans",
    "cefr": "A2",
    "goal": "say what you like and think, and what you'll do",
    "wordTags": [
      "nature & weather",
      "conjunctions",
      "small-talk"
    ]
  },
  {
    "id": "s2-pasttime",
    "order": 9,
    "stage": 2,
    "stageTitle": "Connect & sustain",
    "title": "What you did today",
    "shortTitle": "What you did",
    "cefr": "A2",
    "goal": "tell someone what you did",
    "wordTags": [
      "time & days"
    ]
  },
  {
    "id": "s2-home-family",
    "order": 10,
    "stage": 2,
    "stageTitle": "Connect & sustain",
    "title": "Family, home and work",
    "shortTitle": "Family & home",
    "cefr": "A2",
    "goal": "tell someone about your family and your life",
    "wordTags": [
      "family & people",
      "home & everyday objects",
      "possessives"
    ]
  },
  {
    "id": "s2-arrange",
    "order": 11,
    "stage": 2,
    "stageTitle": "Connect & sustain",
    "title": "Making plans on the phone",
    "shortTitle": "Making plans",
    "cefr": "A2",
    "goal": "call someone and agree a time and place to meet",
    "extraIds": [
      "gen-phone"
    ],
    "wordTags": [
      "phone"
    ]
  },
  {
    "id": "s2-problems",
    "order": 12,
    "stage": 2,
    "stageTitle": "Connect & sustain",
    "title": "When things go wrong",
    "shortTitle": "When things go wrong",
    "cefr": "A2",
    "goal": "explain a problem and ask for it to be put right",
    "wordTags": [
      "body & health"
    ]
  }
];
