// MACHINE-GENERATED by pipeline/src/run-chapters.ts from pipeline/output/curriculum-mk.json.
// The course spine: 12 ordered chapters over content that already exists (artifacts join by the
// `gen-<chapterId>` id convention / tags — see packages/core/src/chapters). Edit the maps in
// run-chapters.ts and re-run; don't hand-edit this file.
import type { Chapter } from "@ll/pack-schema";

export const chapters: Chapter[] = [
  {
    "id": "s0-repair",
    "order": 1,
    "stage": 0,
    "stageTitle": "Decode & survive",
    "title": "Keeping the conversation alive (repair kit)",
    "shortTitle": "Repair kit",
    "cefr": "pre-A1",
    "goal": "any first exchange that breaks down",
    "wordTags": [
      "question words"
    ]
  },
  {
    "id": "s0-greet",
    "order": 2,
    "stage": 0,
    "stageTitle": "Decode & survive",
    "title": "Greetings, politeness, yes/no",
    "shortTitle": "Greetings & politeness",
    "cefr": "pre-A1",
    "goal": "meeting and parting",
    "wordTags": [
      "pronouns",
      "this & that",
      "greeting",
      "social"
    ]
  },
  {
    "id": "s0-survive",
    "order": 3,
    "stage": 0,
    "stageTitle": "Decode & survive",
    "title": "Survival operators + numbers 1–10",
    "shortTitle": "Survival words & numbers",
    "cefr": "pre-A1",
    "goal": "a first tiny transaction",
    "wordTags": [
      "numbers",
      "common adverbs"
    ]
  },
  {
    "id": "s1-cafe-order",
    "order": 4,
    "stage": 1,
    "stageTitle": "Core situations",
    "title": "Café & bar: order and pay (the anchor)",
    "shortTitle": "Café & bar",
    "cefr": "A1",
    "goal": "a relaxed bar/café in Skopje",
    "extraIds": [
      "bar-order-a-drink",
      "ana-coffee",
      "cafe",
      "cafe-order-gap",
      "w-order-coffee"
    ],
    "wordTags": [
      "food & drink",
      "drinks",
      "ordering",
      "paying"
    ]
  },
  {
    "id": "s1-greet-intro",
    "order": 5,
    "stage": 1,
    "stageTitle": "Core situations",
    "title": "Greetings & introductions",
    "shortTitle": "Introductions",
    "cefr": "A1",
    "goal": "meeting another patron at the bar / someone new",
    "extraIds": [
      "bar-small-talk",
      "gen-introductions",
      "w-greet-name",
      "w-from"
    ],
    "wordTags": [
      "common verbs",
      "introductions"
    ]
  },
  {
    "id": "s1-market",
    "order": 6,
    "stage": 1,
    "stageTitle": "Core situations",
    "title": "Shopping at the market",
    "shortTitle": "At the market",
    "cefr": "A1",
    "goal": "a small shop / the pazar",
    "extraIds": [
      "gen-shopping",
      "w-ask-price"
    ],
    "wordTags": [
      "money & shopping",
      "common adjectives",
      "shopping"
    ]
  },
  {
    "id": "s1-directions",
    "order": 7,
    "stage": 1,
    "stageTitle": "Core situations",
    "title": "Directions & getting around",
    "shortTitle": "Directions",
    "cefr": "A1",
    "goal": "a street in the city",
    "extraIds": [
      "gen-directions"
    ],
    "wordTags": [
      "places & travel",
      "prepositions",
      "directions"
    ]
  },
  {
    "id": "s2-smalltalk",
    "order": 8,
    "stage": 2,
    "stageTitle": "Connect & sustain",
    "title": "Small talk, likes & opinions",
    "shortTitle": "Small talk & opinions",
    "cefr": "A2",
    "goal": "lingering conversation after the basics are done",
    "wordTags": [
      "nature & weather",
      "conjunctions",
      "small-talk"
    ]
  },
  {
    "id": "s2-pasttime",
    "order": 9,
    "stage": 2,
    "stageTitle": "Connect & sustain",
    "title": "Your day: past & future",
    "shortTitle": "Past & future",
    "cefr": "A2",
    "goal": "talking about your day and your plans",
    "wordTags": [
      "time & days"
    ]
  },
  {
    "id": "s2-home-family",
    "order": 10,
    "stage": 2,
    "stageTitle": "Connect & sustain",
    "title": "Home, family & work",
    "shortTitle": "Home, family & work",
    "cefr": "A2",
    "goal": "telling someone about your life",
    "wordTags": [
      "family & people",
      "home & everyday objects",
      "possessives"
    ]
  },
  {
    "id": "s2-arrange",
    "order": 11,
    "stage": 2,
    "stageTitle": "Connect & sustain",
    "title": "Phone & arranging to meet",
    "shortTitle": "Phone & arranging",
    "cefr": "A2",
    "goal": "a short phone call to make a plan",
    "extraIds": [
      "gen-phone"
    ],
    "wordTags": [
      "phone"
    ]
  },
  {
    "id": "s2-problems",
    "order": 12,
    "stage": 2,
    "stageTitle": "Connect & sustain",
    "title": "Problems & complaints (repair kit, leveled up)",
    "shortTitle": "Problems & complaints",
    "cefr": "A2",
    "goal": "something went wrong (a shop, a café, a booking)",
    "wordTags": [
      "body & health"
    ]
  }
];
