// MACHINE-GENERATED by pipeline/src/run-conjugations.ts (Opus 4.8). Present-tense verb paradigms for the
// Build-a-sentence conjugation tabs. Spot-check + flip confidence to "validated" as you review.
// Regenerate/fill gaps with: pipeline/node_modules/.bin/tsx pipeline/src/run-conjugations.ts
import type { ConjugationSet } from "@ll/pack-schema";

export const conjugations: ConjugationSet[] = [
  {
    "lemma": "види",
    "gloss": "see",
    "group": "i",
    "forms": {
      "1sg": "видам",
      "2sg": "видиш",
      "3sg": "види",
      "1pl": "видиме",
      "2pl": "видите",
      "3pl": "видат"
    },
    "conceptId": "verb-conjugation",
    "confidence": "unreviewed"
  },
  {
    "lemma": "дава",
    "gloss": "give",
    "group": "a",
    "forms": {
      "1sg": "давам",
      "2sg": "даваш",
      "3sg": "дава",
      "1pl": "даваме",
      "2pl": "давате",
      "3pl": "даваат"
    },
    "conceptId": "verb-conjugation",
    "confidence": "unreviewed"
  },
  {
    "lemma": "доаѓа",
    "gloss": "come",
    "group": "a",
    "forms": {
      "1sg": "доаѓам",
      "2sg": "доаѓаш",
      "3sg": "доаѓа",
      "1pl": "доаѓаме",
      "2pl": "доаѓате",
      "3pl": "доаѓаат"
    },
    "conceptId": "verb-conjugation",
    "confidence": "unreviewed"
  },
  {
    "lemma": "е",
    "gloss": "be",
    "group": "irregular",
    "forms": {
      "1sg": "сум",
      "2sg": "си",
      "3sg": "е",
      "1pl": "сме",
      "2pl": "сте",
      "3pl": "се"
    },
    "conceptId": "verb-conjugation",
    "confidence": "unreviewed"
  },
  {
    "lemma": "живее",
    "gloss": "live",
    "group": "e",
    "forms": {
      "1sg": "живеам",
      "2sg": "живееш",
      "3sg": "живее",
      "1pl": "живееме",
      "2pl": "живеете",
      "3pl": "живеат"
    },
    "conceptId": "verb-conjugation",
    "confidence": "unreviewed"
  },
  {
    "lemma": "зборува",
    "gloss": "speak",
    "group": "a",
    "forms": {
      "1sg": "зборувам",
      "2sg": "зборуваш",
      "3sg": "зборува",
      "1pl": "зборуваме",
      "2pl": "зборувате",
      "3pl": "зборуваат"
    },
    "conceptId": "verb-conjugation",
    "confidence": "unreviewed"
  },
  {
    "lemma": "зема",
    "gloss": "take",
    "group": "a",
    "forms": {
      "1sg": "земам",
      "2sg": "земаш",
      "3sg": "зема",
      "1pl": "земаме",
      "2pl": "земате",
      "3pl": "земаат"
    },
    "conceptId": "verb-conjugation",
    "confidence": "unreviewed"
  },
  {
    "lemma": "знае",
    "gloss": "know",
    "group": "e",
    "forms": {
      "1sg": "знам",
      "2sg": "знаеш",
      "3sg": "знае",
      "1pl": "знаеме",
      "2pl": "знаете",
      "3pl": "знаат"
    },
    "conceptId": "verb-conjugation",
    "confidence": "unreviewed"
  },
  {
    "lemma": "има",
    "gloss": "have",
    "group": "a",
    "forms": {
      "1sg": "имам",
      "2sg": "имаш",
      "3sg": "има",
      "1pl": "имаме",
      "2pl": "имате",
      "3pl": "имаат"
    },
    "conceptId": "verb-conjugation",
    "confidence": "unreviewed"
  },
  {
    "lemma": "јаде",
    "gloss": "eat",
    "group": "e",
    "forms": {
      "1sg": "јадам",
      "2sg": "јадеш",
      "3sg": "јаде",
      "1pl": "јадеме",
      "2pl": "јадете",
      "3pl": "јадат"
    },
    "conceptId": "verb-conjugation",
    "confidence": "unreviewed"
  },
  {
    "lemma": "купува",
    "gloss": "buy",
    "group": "a",
    "forms": {
      "1sg": "купувам",
      "2sg": "купуваш",
      "3sg": "купува",
      "1pl": "купуваме",
      "2pl": "купувате",
      "3pl": "купуваат"
    },
    "conceptId": "verb-conjugation",
    "confidence": "unreviewed"
  },
  {
    "lemma": "може",
    "gloss": "can",
    "group": "e",
    "forms": {
      "1sg": "можам",
      "2sg": "можеш",
      "3sg": "може",
      "1pl": "можеме",
      "2pl": "можете",
      "3pl": "можат"
    },
    "conceptId": "verb-conjugation",
    "confidence": "unreviewed"
  },
  {
    "lemma": "оди",
    "gloss": "go, walk",
    "group": "i",
    "forms": {
      "1sg": "одам",
      "2sg": "одиш",
      "3sg": "оди",
      "1pl": "одиме",
      "2pl": "одите",
      "3pl": "одат"
    },
    "conceptId": "verb-conjugation",
    "confidence": "unreviewed"
  },
  {
    "lemma": "пие",
    "gloss": "drink",
    "group": "e",
    "forms": {
      "1sg": "пијам",
      "2sg": "пиеш",
      "3sg": "пие",
      "1pl": "пиеме",
      "2pl": "пиете",
      "3pl": "пијат"
    },
    "conceptId": "verb-conjugation",
    "confidence": "unreviewed"
  },
  {
    "lemma": "плаќа",
    "gloss": "pay",
    "group": "a",
    "forms": {
      "1sg": "плаќам",
      "2sg": "плаќаш",
      "3sg": "плаќа",
      "1pl": "плаќаме",
      "2pl": "плаќате",
      "3pl": "плаќаат"
    },
    "conceptId": "verb-conjugation",
    "confidence": "unreviewed"
  },
  {
    "lemma": "прашува",
    "gloss": "ask",
    "group": "a",
    "forms": {
      "1sg": "прашувам",
      "2sg": "прашуваш",
      "3sg": "прашува",
      "1pl": "прашуваме",
      "2pl": "прашувате",
      "3pl": "прашуваат"
    },
    "conceptId": "verb-conjugation",
    "confidence": "unreviewed"
  },
  {
    "lemma": "работи",
    "gloss": "work",
    "group": "i",
    "forms": {
      "1sg": "работам",
      "2sg": "работиш",
      "3sg": "работи",
      "1pl": "работиме",
      "2pl": "работите",
      "3pl": "работат"
    },
    "conceptId": "verb-conjugation",
    "confidence": "unreviewed"
  },
  {
    "lemma": "сака",
    "gloss": "want",
    "group": "a",
    "forms": {
      "1sg": "сакам",
      "2sg": "сакаш",
      "3sg": "сака",
      "1pl": "сакаме",
      "2pl": "сакате",
      "3pl": "сакаат"
    },
    "conceptId": "verb-conjugation",
    "confidence": "unreviewed"
  },
  {
    "lemma": "спие",
    "gloss": "sleep",
    "group": "e",
    "forms": {
      "1sg": "спијам",
      "2sg": "спиеш",
      "3sg": "спие",
      "1pl": "спиеме",
      "2pl": "спиете",
      "3pl": "спијат"
    },
    "conceptId": "verb-conjugation",
    "confidence": "unreviewed"
  },
  {
    "lemma": "треба",
    "gloss": "need / should",
    "group": "a",
    "forms": {
      "1sg": "требам",
      "2sg": "требаш",
      "3sg": "треба",
      "1pl": "требаме",
      "2pl": "требате",
      "3pl": "требаат"
    },
    "conceptId": "verb-conjugation",
    "confidence": "unreviewed"
  },
  {
    "lemma": "чини",
    "gloss": "cost",
    "group": "i",
    "forms": {
      "1sg": "чинам",
      "2sg": "чиниш",
      "3sg": "чини",
      "1pl": "чиниме",
      "2pl": "чините",
      "3pl": "чинат"
    },
    "conceptId": "verb-conjugation",
    "confidence": "unreviewed"
  }
];
