// MACHINE-GENERATED by pipeline/src/run-sentences.ts (Opus 4.8). "Build a sentence" items — one simple
// sentence per verb across all six persons, using only taught complement words. Spot-check + flip
// confidence to "validated". Regenerate/fill gaps with: pipeline/node_modules/.bin/tsx pipeline/src/run-sentences.ts
import type { SentenceItem } from "@ll/pack-schema";

export const sentences: SentenceItem[] = [
  {
    "id": "sent-види",
    "conceptIds": [
      "verb-conjugation"
    ],
    "verbLemma": "види",
    "supportWords": [
      "сонце"
    ],
    "variants": [
      {
        "person": "1sg",
        "en": "I see the sun",
        "mk": "Гледам сонце"
      },
      {
        "person": "2sg",
        "en": "you see the sun",
        "mk": "Гледаш сонце"
      },
      {
        "person": "3sg",
        "en": "he/she sees the sun",
        "mk": "Гледа сонце"
      },
      {
        "person": "1pl",
        "en": "we see the sun",
        "mk": "Гледаме сонце"
      },
      {
        "person": "2pl",
        "en": "you see the sun",
        "mk": "Гледате сонце"
      },
      {
        "person": "3pl",
        "en": "they see the sun",
        "mk": "Гледаат сонце"
      }
    ],
    "confidence": "unreviewed"
  },
  {
    "id": "sent-дава",
    "conceptIds": [
      "verb-conjugation"
    ],
    "verbLemma": "дава",
    "supportWords": [
      "пари"
    ],
    "variants": [
      {
        "person": "1sg",
        "en": "I give money",
        "mk": "Давам пари"
      },
      {
        "person": "2sg",
        "en": "you give money",
        "mk": "Даваш пари"
      },
      {
        "person": "3sg",
        "en": "he/she gives money",
        "mk": "Дава пари"
      },
      {
        "person": "1pl",
        "en": "we give money",
        "mk": "Даваме пари"
      },
      {
        "person": "2pl",
        "en": "you give money",
        "mk": "Давате пари"
      },
      {
        "person": "3pl",
        "en": "they give money",
        "mk": "Даваат пари"
      }
    ],
    "confidence": "unreviewed"
  },
  {
    "id": "sent-доаѓа",
    "conceptIds": [
      "verb-conjugation"
    ],
    "verbLemma": "доаѓа",
    "supportWords": [
      "сега"
    ],
    "variants": [
      {
        "person": "1sg",
        "en": "I come now",
        "mk": "Доаѓам сега"
      },
      {
        "person": "2sg",
        "en": "you come now",
        "mk": "Доаѓаш сега"
      },
      {
        "person": "3sg",
        "en": "he/she comes now",
        "mk": "Доаѓа сега"
      },
      {
        "person": "1pl",
        "en": "we come now",
        "mk": "Доаѓаме сега"
      },
      {
        "person": "2pl",
        "en": "you come now",
        "mk": "Доаѓате сега"
      },
      {
        "person": "3pl",
        "en": "they come now",
        "mk": "Доаѓаат сега"
      }
    ],
    "confidence": "unreviewed"
  },
  {
    "id": "sent-е",
    "conceptIds": [
      "verb-conjugation"
    ],
    "verbLemma": "е",
    "supportWords": [
      "болен"
    ],
    "variants": [
      {
        "person": "1sg",
        "en": "I am sick",
        "mk": "Јас сум болен"
      },
      {
        "person": "2sg",
        "en": "you are sick",
        "mk": "Ти си болен"
      },
      {
        "person": "3sg",
        "en": "he/she is sick",
        "mk": "Тој е болен"
      },
      {
        "person": "1pl",
        "en": "we are sick",
        "mk": "Ние сме болни"
      },
      {
        "person": "2pl",
        "en": "you are sick",
        "mk": "Вие сте болни"
      },
      {
        "person": "3pl",
        "en": "they are sick",
        "mk": "Тие се болни"
      }
    ],
    "confidence": "unreviewed"
  },
  {
    "id": "sent-живее",
    "conceptIds": [
      "verb-conjugation"
    ],
    "verbLemma": "живее",
    "supportWords": [
      "тука"
    ],
    "variants": [
      {
        "person": "1sg",
        "en": "I live here",
        "mk": "Живеам тука"
      },
      {
        "person": "2sg",
        "en": "you live here",
        "mk": "Живееш тука"
      },
      {
        "person": "3sg",
        "en": "he/she lives here",
        "mk": "Живее тука"
      },
      {
        "person": "1pl",
        "en": "we live here",
        "mk": "Живееме тука"
      },
      {
        "person": "2pl",
        "en": "you live here",
        "mk": "Живеете тука"
      },
      {
        "person": "3pl",
        "en": "they live here",
        "mk": "Живеат тука"
      }
    ],
    "confidence": "unreviewed"
  },
  {
    "id": "sent-зборува",
    "conceptIds": [
      "verb-conjugation"
    ],
    "verbLemma": "зборува",
    "supportWords": [
      "полека"
    ],
    "variants": [
      {
        "person": "1sg",
        "en": "I speak slowly",
        "mk": "Зборувам полека"
      },
      {
        "person": "2sg",
        "en": "you speak slowly",
        "mk": "Зборуваш полека"
      },
      {
        "person": "3sg",
        "en": "he/she speaks slowly",
        "mk": "Зборува полека"
      },
      {
        "person": "1pl",
        "en": "we speak slowly",
        "mk": "Зборуваме полека"
      },
      {
        "person": "2pl",
        "en": "you speak slowly",
        "mk": "Зборувате полека"
      },
      {
        "person": "3pl",
        "en": "they speak slowly",
        "mk": "Зборуваат полека"
      }
    ],
    "confidence": "unreviewed"
  },
  {
    "id": "sent-зема",
    "conceptIds": [
      "verb-conjugation",
      "definite-articles"
    ],
    "verbLemma": "зема",
    "supportWords": [
      "клуч"
    ],
    "variants": [
      {
        "person": "1sg",
        "en": "I take the key",
        "mk": "Земам клуч"
      },
      {
        "person": "2sg",
        "en": "You take the key",
        "mk": "Земаш клуч"
      },
      {
        "person": "3sg",
        "en": "He/she takes the key",
        "mk": "Зема клуч"
      },
      {
        "person": "1pl",
        "en": "We take the key",
        "mk": "Земаме клуч"
      },
      {
        "person": "2pl",
        "en": "You take the key",
        "mk": "Земате клуч"
      },
      {
        "person": "3pl",
        "en": "They take the key",
        "mk": "Земаат клуч"
      }
    ],
    "confidence": "unreviewed"
  },
  {
    "id": "sent-знае",
    "conceptIds": [
      "verb-conjugation"
    ],
    "verbLemma": "знае",
    "supportWords": [
      "пат"
    ],
    "variants": [
      {
        "person": "1sg",
        "en": "I know the way",
        "mk": "Знам пат"
      },
      {
        "person": "2sg",
        "en": "You know the way",
        "mk": "Знаеш пат"
      },
      {
        "person": "3sg",
        "en": "He/she knows the way",
        "mk": "Знае пат"
      },
      {
        "person": "1pl",
        "en": "We know the way",
        "mk": "Знаеме пат"
      },
      {
        "person": "2pl",
        "en": "You know the way",
        "mk": "Знаете пат"
      },
      {
        "person": "3pl",
        "en": "They know the way",
        "mk": "Знаат пат"
      }
    ],
    "confidence": "unreviewed"
  },
  {
    "id": "sent-има",
    "conceptIds": [
      "verb-conjugation"
    ],
    "verbLemma": "има",
    "supportWords": [
      "пари"
    ],
    "variants": [
      {
        "person": "1sg",
        "en": "I have money",
        "mk": "Имам пари"
      },
      {
        "person": "2sg",
        "en": "You have money",
        "mk": "Имаш пари"
      },
      {
        "person": "3sg",
        "en": "He/she has money",
        "mk": "Има пари"
      },
      {
        "person": "1pl",
        "en": "We have money",
        "mk": "Имаме пари"
      },
      {
        "person": "2pl",
        "en": "You have money",
        "mk": "Имате пари"
      },
      {
        "person": "3pl",
        "en": "They have money",
        "mk": "Имаат пари"
      }
    ],
    "confidence": "unreviewed"
  },
  {
    "id": "sent-јаде",
    "conceptIds": [
      "verb-conjugation"
    ],
    "verbLemma": "јаде",
    "supportWords": [
      "леб"
    ],
    "variants": [
      {
        "person": "1sg",
        "en": "I eat bread",
        "mk": "Јадам леб"
      },
      {
        "person": "2sg",
        "en": "You eat bread",
        "mk": "Јадеш леб"
      },
      {
        "person": "3sg",
        "en": "He/she eats bread",
        "mk": "Јаде леб"
      },
      {
        "person": "1pl",
        "en": "We eat bread",
        "mk": "Јадеме леб"
      },
      {
        "person": "2pl",
        "en": "You eat bread",
        "mk": "Јадете леб"
      },
      {
        "person": "3pl",
        "en": "They eat bread",
        "mk": "Јадат леб"
      }
    ],
    "confidence": "unreviewed"
  },
  {
    "id": "sent-купува",
    "conceptIds": [
      "verb-conjugation"
    ],
    "verbLemma": "купува",
    "supportWords": [
      "риба"
    ],
    "variants": [
      {
        "person": "1sg",
        "en": "I buy fish",
        "mk": "Купувам риба"
      },
      {
        "person": "2sg",
        "en": "You buy fish",
        "mk": "Купуваш риба"
      },
      {
        "person": "3sg",
        "en": "He/she buys fish",
        "mk": "Купува риба"
      },
      {
        "person": "1pl",
        "en": "We buy fish",
        "mk": "Купуваме риба"
      },
      {
        "person": "2pl",
        "en": "You buy fish",
        "mk": "Купувате риба"
      },
      {
        "person": "3pl",
        "en": "They buy fish",
        "mk": "Купуваат риба"
      }
    ],
    "confidence": "unreviewed"
  },
  {
    "id": "sent-може",
    "conceptIds": [
      "verb-conjugation"
    ],
    "verbLemma": "може",
    "supportWords": [
      "брзо"
    ],
    "variants": [
      {
        "person": "1sg",
        "en": "I can go quickly",
        "mk": "Можам брзо"
      },
      {
        "person": "2sg",
        "en": "You can go quickly",
        "mk": "Можеш брзо"
      },
      {
        "person": "3sg",
        "en": "He/she can go quickly",
        "mk": "Може брзо"
      },
      {
        "person": "1pl",
        "en": "We can go quickly",
        "mk": "Можеме брзо"
      },
      {
        "person": "2pl",
        "en": "You can go quickly",
        "mk": "Можете брзо"
      },
      {
        "person": "3pl",
        "en": "They can go quickly",
        "mk": "Можат брзо"
      }
    ],
    "confidence": "unreviewed"
  },
  {
    "id": "sent-оди",
    "conceptIds": [
      "verb-conjugation"
    ],
    "verbLemma": "оди",
    "supportWords": [
      "таму"
    ],
    "variants": [
      {
        "person": "1sg",
        "en": "I go there",
        "mk": "Одам таму"
      },
      {
        "person": "2sg",
        "en": "You go there",
        "mk": "Одиш таму"
      },
      {
        "person": "3sg",
        "en": "He/she goes there",
        "mk": "Оди таму"
      },
      {
        "person": "1pl",
        "en": "We go there",
        "mk": "Одиме таму"
      },
      {
        "person": "2pl",
        "en": "You go there",
        "mk": "Одите таму"
      },
      {
        "person": "3pl",
        "en": "They go there",
        "mk": "Одат таму"
      }
    ],
    "confidence": "unreviewed"
  },
  {
    "id": "sent-пие",
    "conceptIds": [
      "verb-conjugation"
    ],
    "verbLemma": "пие",
    "supportWords": [
      "кафе"
    ],
    "variants": [
      {
        "person": "1sg",
        "en": "I drink coffee",
        "mk": "Пијам кафе"
      },
      {
        "person": "2sg",
        "en": "You drink coffee",
        "mk": "Пиеш кафе"
      },
      {
        "person": "3sg",
        "en": "He/she drinks coffee",
        "mk": "Пие кафе"
      },
      {
        "person": "1pl",
        "en": "We drink coffee",
        "mk": "Пиеме кафе"
      },
      {
        "person": "2pl",
        "en": "You drink coffee",
        "mk": "Пиете кафе"
      },
      {
        "person": "3pl",
        "en": "They drink coffee",
        "mk": "Пијат кафе"
      }
    ],
    "confidence": "unreviewed"
  },
  {
    "id": "sent-плаќа",
    "conceptIds": [
      "verb-conjugation"
    ],
    "verbLemma": "плаќа",
    "supportWords": [
      "сега"
    ],
    "variants": [
      {
        "person": "1sg",
        "en": "I pay now",
        "mk": "Плаќам сега"
      },
      {
        "person": "2sg",
        "en": "You pay now",
        "mk": "Плаќаш сега"
      },
      {
        "person": "3sg",
        "en": "He/she pays now",
        "mk": "Плаќа сега"
      },
      {
        "person": "1pl",
        "en": "We pay now",
        "mk": "Плаќаме сега"
      },
      {
        "person": "2pl",
        "en": "You pay now",
        "mk": "Плаќате сега"
      },
      {
        "person": "3pl",
        "en": "They pay now",
        "mk": "Плаќаат сега"
      }
    ],
    "confidence": "unreviewed"
  },
  {
    "id": "sent-прашува",
    "conceptIds": [
      "verb-conjugation"
    ],
    "verbLemma": "прашува",
    "supportWords": [
      "лекар"
    ],
    "variants": [
      {
        "person": "1sg",
        "en": "I ask the doctor",
        "mk": "Прашувам лекар"
      },
      {
        "person": "2sg",
        "en": "You ask the doctor",
        "mk": "Прашуваш лекар"
      },
      {
        "person": "3sg",
        "en": "He/she asks the doctor",
        "mk": "Прашува лекар"
      },
      {
        "person": "1pl",
        "en": "We ask the doctor",
        "mk": "Прашуваме лекар"
      },
      {
        "person": "2pl",
        "en": "You ask the doctor",
        "mk": "Прашувате лекар"
      },
      {
        "person": "3pl",
        "en": "They ask the doctor",
        "mk": "Прашуваат лекар"
      }
    ],
    "confidence": "unreviewed"
  },
  {
    "id": "sent-работи",
    "conceptIds": [
      "verb-conjugation"
    ],
    "verbLemma": "работи",
    "supportWords": [
      "многу"
    ],
    "variants": [
      {
        "person": "1sg",
        "en": "I work a lot",
        "mk": "Работам многу"
      },
      {
        "person": "2sg",
        "en": "You work a lot",
        "mk": "Работиш многу"
      },
      {
        "person": "3sg",
        "en": "He/she works a lot",
        "mk": "Работи многу"
      },
      {
        "person": "1pl",
        "en": "We work a lot",
        "mk": "Работиме многу"
      },
      {
        "person": "2pl",
        "en": "You work a lot",
        "mk": "Работите многу"
      },
      {
        "person": "3pl",
        "en": "They work a lot",
        "mk": "Работат многу"
      }
    ],
    "confidence": "unreviewed"
  },
  {
    "id": "sent-сака",
    "conceptIds": [
      "verb-conjugation"
    ],
    "verbLemma": "сака",
    "supportWords": [
      "пиво"
    ],
    "variants": [
      {
        "person": "1sg",
        "en": "I want beer",
        "mk": "Сакам пиво"
      },
      {
        "person": "2sg",
        "en": "You want beer",
        "mk": "Сакаш пиво"
      },
      {
        "person": "3sg",
        "en": "He/she wants beer",
        "mk": "Сака пиво"
      },
      {
        "person": "1pl",
        "en": "We want beer",
        "mk": "Сакаме пиво"
      },
      {
        "person": "2pl",
        "en": "You want beer",
        "mk": "Сакате пиво"
      },
      {
        "person": "3pl",
        "en": "They want beer",
        "mk": "Сакаат пиво"
      }
    ],
    "confidence": "unreviewed"
  },
  {
    "id": "sent-спие",
    "conceptIds": [
      "verb-conjugation"
    ],
    "verbLemma": "спие",
    "supportWords": [
      "многу"
    ],
    "variants": [
      {
        "person": "1sg",
        "en": "I sleep a lot",
        "mk": "Спијам многу"
      },
      {
        "person": "2sg",
        "en": "You sleep a lot",
        "mk": "Спиеш многу"
      },
      {
        "person": "3sg",
        "en": "He/She sleeps a lot",
        "mk": "Спие многу"
      },
      {
        "person": "1pl",
        "en": "We sleep a lot",
        "mk": "Спиеме многу"
      },
      {
        "person": "2pl",
        "en": "You sleep a lot",
        "mk": "Спиете многу"
      },
      {
        "person": "3pl",
        "en": "They sleep a lot",
        "mk": "Спијат многу"
      }
    ],
    "confidence": "unreviewed"
  },
  {
    "id": "sent-треба",
    "conceptIds": [
      "verb-conjugation"
    ],
    "verbLemma": "треба",
    "supportWords": [
      "вода"
    ],
    "variants": [
      {
        "person": "1sg",
        "en": "I need water",
        "mk": "Требам вода"
      },
      {
        "person": "2sg",
        "en": "You need water",
        "mk": "Требаш вода"
      },
      {
        "person": "3sg",
        "en": "He/She needs water",
        "mk": "Треба вода"
      },
      {
        "person": "1pl",
        "en": "We need water",
        "mk": "Требаме вода"
      },
      {
        "person": "2pl",
        "en": "You need water",
        "mk": "Требате вода"
      },
      {
        "person": "3pl",
        "en": "They need water",
        "mk": "Требаат вода"
      }
    ],
    "confidence": "unreviewed"
  },
  {
    "id": "sent-чини",
    "conceptIds": [
      "verb-conjugation"
    ],
    "verbLemma": "чини",
    "supportWords": [
      "десет",
      "пари"
    ],
    "variants": [
      {
        "person": "1sg",
        "en": "I cost ten",
        "mk": "Чинам десет"
      },
      {
        "person": "2sg",
        "en": "You cost ten",
        "mk": "Чиниш десет"
      },
      {
        "person": "3sg",
        "en": "It costs ten",
        "mk": "Чини десет"
      },
      {
        "person": "1pl",
        "en": "We cost ten",
        "mk": "Чиниме десет"
      },
      {
        "person": "2pl",
        "en": "You cost ten",
        "mk": "Чините десет"
      },
      {
        "person": "3pl",
        "en": "They cost ten",
        "mk": "Чинат десет"
      }
    ],
    "confidence": "unreviewed"
  }
];
