// MACHINE-GENERATED by pipeline/src/run-sentences.ts (Opus 4.8). "Build a sentence" items — per verb, a ladder of
// complexity tiers (1: 2-3 words … 4: two clauses, 7-9 words), each across all six persons, using only taught
// words; generated then reviewed by a second Opus pass. Spot-check + flip confidence to "validated".
// Regenerate/fill gaps with: pipeline/node_modules/.bin/tsx pipeline/src/run-sentences.ts [--review-all]
import type { SentenceItem } from "@ll/pack-schema";

export const sentences: SentenceItem[] = [
  {
    "id": "sent-види-t3",
    "conceptIds": [
      "verb-conjugation",
      "definite-articles"
    ],
    "verbLemma": "види",
    "supportWords": [
      "доктор",
      "утро"
    ],
    "variants": [
      {
        "person": "1sg",
        "en": "In the morning I will see the doctor.",
        "mk": "Утрото ќе го видам докторот."
      },
      {
        "person": "2sg",
        "en": "In the morning you will see the doctor.",
        "mk": "Утрото ќе го видиш докторот."
      },
      {
        "person": "3sg",
        "en": "In the morning he will see the doctor.",
        "mk": "Утрото ќе го види докторот."
      },
      {
        "person": "1pl",
        "en": "In the morning we will see the doctor.",
        "mk": "Утрото ќе го видиме докторот."
      },
      {
        "person": "2pl",
        "en": "In the morning you will see the doctor.",
        "mk": "Утрото ќе го видите докторот."
      },
      {
        "person": "3pl",
        "en": "In the morning they will see the doctor.",
        "mk": "Утрото ќе го видат докторот."
      }
    ],
    "tier": 3,
    "confidence": "unreviewed"
  },
  {
    "id": "sent-види-t4",
    "conceptIds": [
      "verb-conjugation",
      "definite-articles"
    ],
    "verbLemma": "види",
    "supportWords": [
      "пријател",
      "град",
      "денес"
    ],
    "variants": [
      {
        "person": "1sg",
        "en": "I will see my friend today because he is coming to the city.",
        "mk": "Денес ќе го видам мојот пријател бидејќи доаѓа во градот."
      },
      {
        "person": "2sg",
        "en": "You will see your friend today because he is coming to the city.",
        "mk": "Денес ќе го видиш твојот пријател бидејќи доаѓа во градот."
      },
      {
        "person": "3sg",
        "en": "She will see her friend today because he is coming to the city.",
        "mk": "Денес ќе го види нејзиниот пријател бидејќи доаѓа во градот."
      },
      {
        "person": "1pl",
        "en": "We will see our friend today because he is coming to the city.",
        "mk": "Денес ќе го видиме нашиот пријател бидејќи доаѓа во градот."
      },
      {
        "person": "2pl",
        "en": "You will see your friend today because he is coming to the city.",
        "mk": "Денес ќе го видите вашиот пријател бидејќи доаѓа во градот."
      },
      {
        "person": "3pl",
        "en": "They will see their friend today because he is coming to the city.",
        "mk": "Денес ќе го видат нивниот пријател бидејќи доаѓа во градот."
      }
    ],
    "tier": 4,
    "confidence": "unreviewed"
  },
  {
    "id": "sent-дава",
    "conceptIds": [
      "verb-conjugation"
    ],
    "verbLemma": "дава",
    "supportWords": [
      "пари"
    ],
    "variants": [
      {
        "person": "1sg",
        "en": "I give money.",
        "mk": "Давам пари."
      },
      {
        "person": "2sg",
        "en": "You give money.",
        "mk": "Даваш пари."
      },
      {
        "person": "3sg",
        "en": "He/she gives money.",
        "mk": "Дава пари."
      },
      {
        "person": "1pl",
        "en": "We give money.",
        "mk": "Даваме пари."
      },
      {
        "person": "2pl",
        "en": "You give money.",
        "mk": "Давате пари."
      },
      {
        "person": "3pl",
        "en": "They give money.",
        "mk": "Даваат пари."
      }
    ],
    "confidence": "unreviewed"
  },
  {
    "id": "sent-дава-t2",
    "conceptIds": [
      "verb-conjugation",
      "definite-articles"
    ],
    "verbLemma": "дава",
    "supportWords": [
      "пари",
      "баба"
    ],
    "variants": [
      {
        "person": "1sg",
        "en": "I give money to grandma.",
        "mk": "Ѝ давам пари на баба."
      },
      {
        "person": "2sg",
        "en": "You give money to grandma.",
        "mk": "Ѝ даваш пари на баба."
      },
      {
        "person": "3sg",
        "en": "He/she gives money to grandma.",
        "mk": "Ѝ дава пари на баба."
      },
      {
        "person": "1pl",
        "en": "We give money to grandma.",
        "mk": "Ѝ даваме пари на баба."
      },
      {
        "person": "2pl",
        "en": "You give money to grandma.",
        "mk": "Ѝ давате пари на баба."
      },
      {
        "person": "3pl",
        "en": "They give money to grandma.",
        "mk": "Ѝ даваат пари на баба."
      }
    ],
    "tier": 2,
    "confidence": "unreviewed"
  },
  {
    "id": "sent-дава-t3",
    "conceptIds": [
      "verb-conjugation",
      "definite-articles"
    ],
    "verbLemma": "дава",
    "supportWords": [
      "клуч",
      "пријател",
      "сега"
    ],
    "variants": [
      {
        "person": "1sg",
        "en": "Now I give the key to my friend.",
        "mk": "Сега му го давам клучот на пријателот."
      },
      {
        "person": "2sg",
        "en": "Now you give the key to your friend.",
        "mk": "Сега му го даваш клучот на пријателот."
      },
      {
        "person": "3sg",
        "en": "Now he/she gives the key to the friend.",
        "mk": "Сега му го дава клучот на пријателот."
      },
      {
        "person": "1pl",
        "en": "Now we give the key to our friend.",
        "mk": "Сега му го даваме клучот на пријателот."
      },
      {
        "person": "2pl",
        "en": "Now you give the key to your friend.",
        "mk": "Сега му го давате клучот на пријателот."
      },
      {
        "person": "3pl",
        "en": "Now they give the key to their friend.",
        "mk": "Сега му го даваат клучот на пријателот."
      }
    ],
    "tier": 3,
    "confidence": "unreviewed"
  },
  {
    "id": "sent-дава-t4",
    "conceptIds": [
      "verb-conjugation",
      "definite-articles"
    ],
    "verbLemma": "дава",
    "supportWords": [
      "вода",
      "момче",
      "бидејќи",
      "болен",
      "многу"
    ],
    "variants": [
      {
        "person": "1sg",
        "en": "I give water to the boy because he is very sick.",
        "mk": "Му давам вода на момчето бидејќи е многу болен."
      },
      {
        "person": "2sg",
        "en": "You give water to the boy because he is very sick.",
        "mk": "Му даваш вода на момчето бидејќи е многу болен."
      },
      {
        "person": "3sg",
        "en": "He/she gives water to the boy because he is very sick.",
        "mk": "Му дава вода на момчето бидејќи е многу болен."
      },
      {
        "person": "1pl",
        "en": "We give water to the boy because he is very sick.",
        "mk": "Му даваме вода на момчето бидејќи е многу болен."
      },
      {
        "person": "2pl",
        "en": "You give water to the boy because he is very sick.",
        "mk": "Му давате вода на момчето бидејќи е многу болен."
      },
      {
        "person": "3pl",
        "en": "They give water to the boy because he is very sick.",
        "mk": "Му даваат вода на момчето бидејќи е многу болен."
      }
    ],
    "tier": 4,
    "confidence": "unreviewed"
  },
  {
    "id": "sent-доаѓа",
    "conceptIds": [
      "verb-conjugation"
    ],
    "verbLemma": "доаѓа",
    "supportWords": [
      "сега"
    ],
    "variants": [
      {
        "person": "1sg",
        "en": "I'm coming now.",
        "mk": "Доаѓам сега."
      },
      {
        "person": "2sg",
        "en": "You're coming now.",
        "mk": "Доаѓаш сега."
      },
      {
        "person": "3sg",
        "en": "He/she is coming now.",
        "mk": "Доаѓа сега."
      },
      {
        "person": "1pl",
        "en": "We're coming now.",
        "mk": "Доаѓаме сега."
      },
      {
        "person": "2pl",
        "en": "You're coming now.",
        "mk": "Доаѓате сега."
      },
      {
        "person": "3pl",
        "en": "They're coming now.",
        "mk": "Доаѓаат сега."
      }
    ],
    "confidence": "unreviewed"
  },
  {
    "id": "sent-доаѓа-t2",
    "conceptIds": [
      "verb-conjugation"
    ],
    "verbLemma": "доаѓа",
    "supportWords": [
      "со",
      "автобус"
    ],
    "variants": [
      {
        "person": "1sg",
        "en": "I come by bus.",
        "mk": "Доаѓам со автобус."
      },
      {
        "person": "2sg",
        "en": "You come by bus.",
        "mk": "Доаѓаш со автобус."
      },
      {
        "person": "3sg",
        "en": "He comes by bus.",
        "mk": "Доаѓа со автобус."
      },
      {
        "person": "1pl",
        "en": "We come by bus.",
        "mk": "Доаѓаме со автобус."
      },
      {
        "person": "2pl",
        "en": "You come by bus.",
        "mk": "Доаѓате со автобус."
      },
      {
        "person": "3pl",
        "en": "They come by bus.",
        "mk": "Доаѓаат со автобус."
      }
    ],
    "tier": 2,
    "confidence": "unreviewed"
  },
  {
    "id": "sent-доаѓа-t3",
    "conceptIds": [
      "verb-conjugation",
      "definite-articles"
    ],
    "verbLemma": "доаѓа",
    "supportWords": [
      "денес",
      "со",
      "воз",
      "град"
    ],
    "variants": [
      {
        "person": "1sg",
        "en": "Today I come to the city by train.",
        "mk": "Денес доаѓам во градот со воз."
      },
      {
        "person": "2sg",
        "en": "Today you come to the city by train.",
        "mk": "Денес доаѓаш во градот со воз."
      },
      {
        "person": "3sg",
        "en": "Today he comes to the city by train.",
        "mk": "Денес доаѓа во градот со воз."
      },
      {
        "person": "1pl",
        "en": "Today we come to the city by train.",
        "mk": "Денес доаѓаме во градот со воз."
      },
      {
        "person": "2pl",
        "en": "Today you come to the city by train.",
        "mk": "Денес доаѓате во градот со воз."
      },
      {
        "person": "3pl",
        "en": "Today they come to the city by train.",
        "mk": "Денес доаѓаат во градот со воз."
      }
    ],
    "tier": 3,
    "confidence": "unreviewed"
  },
  {
    "id": "sent-доаѓа-t4",
    "conceptIds": [
      "verb-conjugation",
      "definite-articles"
    ],
    "verbLemma": "доаѓа",
    "supportWords": [
      "град",
      "со",
      "воз",
      "бидејќи",
      "пат",
      "добар"
    ],
    "variants": [
      {
        "person": "1sg",
        "en": "I come to the city by train because the road is bad.",
        "mk": "Доаѓам во градот со воз бидејќи патот е лош."
      },
      {
        "person": "2sg",
        "en": "You come to the city by train because the road is bad.",
        "mk": "Доаѓаш во градот со воз бидејќи патот е лош."
      },
      {
        "person": "3sg",
        "en": "He comes to the city by train because the road is bad.",
        "mk": "Доаѓа во градот со воз бидејќи патот е лош."
      },
      {
        "person": "1pl",
        "en": "We come to the city by train because the road is bad.",
        "mk": "Доаѓаме во градот со воз бидејќи патот е лош."
      },
      {
        "person": "2pl",
        "en": "You come to the city by train because the road is bad.",
        "mk": "Доаѓате во градот со воз бидејќи патот е лош."
      },
      {
        "person": "3pl",
        "en": "They come to the city by train because the road is bad.",
        "mk": "Доаѓаат во градот со воз бидејќи патот е лош."
      }
    ],
    "tier": 4,
    "confidence": "unreviewed"
  },
  {
    "id": "sent-е",
    "conceptIds": [
      "verb-conjugation"
    ],
    "verbLemma": "е",
    "supportWords": [
      "болен"
    ],
    "variants": [
      {
        "person": "1sg",
        "en": "I am sick.",
        "mk": "Јас сум болен."
      },
      {
        "person": "2sg",
        "en": "You are sick.",
        "mk": "Ти си болен."
      },
      {
        "person": "3sg",
        "en": "He is sick.",
        "mk": "Тој е болен."
      },
      {
        "person": "1pl",
        "en": "We are sick.",
        "mk": "Ние сме болни."
      },
      {
        "person": "2pl",
        "en": "You are sick.",
        "mk": "Вие сте болни."
      },
      {
        "person": "3pl",
        "en": "They are sick.",
        "mk": "Тие се болни."
      }
    ],
    "confidence": "unreviewed"
  },
  {
    "id": "sent-е-t2",
    "conceptIds": [
      "verb-conjugation"
    ],
    "verbLemma": "е",
    "supportWords": [
      "добар",
      "доктор"
    ],
    "variants": [
      {
        "person": "1sg",
        "en": "I am a good doctor.",
        "mk": "Јас сум добар доктор."
      },
      {
        "person": "2sg",
        "en": "You are a good doctor.",
        "mk": "Ти си добар доктор."
      },
      {
        "person": "3sg",
        "en": "He is a good doctor.",
        "mk": "Тој е добар доктор."
      },
      {
        "person": "1pl",
        "en": "We are good doctors.",
        "mk": "Ние сме добри доктори."
      },
      {
        "person": "2pl",
        "en": "You are good doctors.",
        "mk": "Вие сте добри доктори."
      },
      {
        "person": "3pl",
        "en": "They are good doctors.",
        "mk": "Тие се добри доктори."
      }
    ],
    "tier": 2,
    "confidence": "unreviewed"
  },
  {
    "id": "sent-е-t3",
    "conceptIds": [
      "verb-conjugation"
    ],
    "verbLemma": "е",
    "supportWords": [
      "тука",
      "стан",
      "мал"
    ],
    "variants": [
      {
        "person": "1sg",
        "en": "I am here in a small apartment.",
        "mk": "Јас сум тука во мал стан."
      },
      {
        "person": "2sg",
        "en": "You are here in a small apartment.",
        "mk": "Ти си тука во мал стан."
      },
      {
        "person": "3sg",
        "en": "She is here in a small apartment.",
        "mk": "Таа е тука во мал стан."
      },
      {
        "person": "1pl",
        "en": "We are here in a small apartment.",
        "mk": "Ние сме тука во мал стан."
      },
      {
        "person": "2pl",
        "en": "You are here in a small apartment.",
        "mk": "Вие сте тука во мал стан."
      },
      {
        "person": "3pl",
        "en": "They are here in a small apartment.",
        "mk": "Тие се тука во мал стан."
      }
    ],
    "tier": 3,
    "confidence": "unreviewed"
  },
  {
    "id": "sent-е-t4",
    "conceptIds": [
      "verb-conjugation",
      "definite-articles"
    ],
    "verbLemma": "е",
    "supportWords": [
      "болен",
      "затоа",
      "одам",
      "доктор"
    ],
    "variants": [
      {
        "person": "1sg",
        "en": "I am sick today, therefore I am going to the doctor.",
        "mk": "Јас сум болен денес, затоа одам кај докторот."
      },
      {
        "person": "2sg",
        "en": "You are sick today, therefore you are going to the doctor.",
        "mk": "Ти си болен денес, затоа одиш кај докторот."
      },
      {
        "person": "3sg",
        "en": "He is sick today, therefore he is going to the doctor.",
        "mk": "Тој е болен денес, затоа оди кај докторот."
      },
      {
        "person": "1pl",
        "en": "We are sick today, therefore we are going to the doctor.",
        "mk": "Ние сме болни денес, затоа одиме кај докторот."
      },
      {
        "person": "2pl",
        "en": "You are sick today, therefore you are going to the doctor.",
        "mk": "Вие сте болни денес, затоа одите кај докторот."
      },
      {
        "person": "3pl",
        "en": "They are sick today, therefore they are going to the doctor.",
        "mk": "Тие се болни денес, затоа одат кај докторот."
      }
    ],
    "tier": 4,
    "confidence": "unreviewed"
  },
  {
    "id": "sent-живее",
    "conceptIds": [
      "verb-conjugation"
    ],
    "verbLemma": "живее",
    "supportWords": [
      "тука"
    ],
    "variants": [
      {
        "person": "1sg",
        "en": "I live here.",
        "mk": "Живеам тука."
      },
      {
        "person": "2sg",
        "en": "You live here.",
        "mk": "Живееш тука."
      },
      {
        "person": "3sg",
        "en": "He/she lives here.",
        "mk": "Живее тука."
      },
      {
        "person": "1pl",
        "en": "We live here.",
        "mk": "Живееме тука."
      },
      {
        "person": "2pl",
        "en": "You live here.",
        "mk": "Живеете тука."
      },
      {
        "person": "3pl",
        "en": "They live here.",
        "mk": "Живеат тука."
      }
    ],
    "confidence": "unreviewed"
  },
  {
    "id": "sent-живее-t2",
    "conceptIds": [
      "verb-conjugation",
      "definite-articles"
    ],
    "verbLemma": "живее",
    "supportWords": [
      "во",
      "град"
    ],
    "variants": [
      {
        "person": "1sg",
        "en": "I live in the city.",
        "mk": "Живеам во градот."
      },
      {
        "person": "2sg",
        "en": "You live in the city.",
        "mk": "Живееш во градот."
      },
      {
        "person": "3sg",
        "en": "He lives in the city.",
        "mk": "Живее во градот."
      },
      {
        "person": "1pl",
        "en": "We live in the city.",
        "mk": "Живееме во градот."
      },
      {
        "person": "2pl",
        "en": "You live in the city.",
        "mk": "Живеете во градот."
      },
      {
        "person": "3pl",
        "en": "They live in the city.",
        "mk": "Живеат во градот."
      }
    ],
    "tier": 2,
    "confidence": "unreviewed"
  },
  {
    "id": "sent-живее-t3",
    "conceptIds": [
      "verb-conjugation",
      "definite-articles"
    ],
    "verbLemma": "живее",
    "supportWords": [
      "сега",
      "во",
      "нов",
      "стан"
    ],
    "variants": [
      {
        "person": "1sg",
        "en": "I now live in a new apartment.",
        "mk": "Сега живеам во нов стан."
      },
      {
        "person": "2sg",
        "en": "You now live in a new apartment.",
        "mk": "Сега живееш во нов стан."
      },
      {
        "person": "3sg",
        "en": "She now lives in a new apartment.",
        "mk": "Сега живее во нов стан."
      },
      {
        "person": "1pl",
        "en": "We now live in a new apartment.",
        "mk": "Сега живееме во нов стан."
      },
      {
        "person": "2pl",
        "en": "You now live in a new apartment.",
        "mk": "Сега живеете во нов стан."
      },
      {
        "person": "3pl",
        "en": "They now live in a new apartment.",
        "mk": "Сега живеат во нов стан."
      }
    ],
    "tier": 3,
    "confidence": "unreviewed"
  },
  {
    "id": "sent-живее-t4",
    "conceptIds": [
      "verb-conjugation",
      "definite-articles"
    ],
    "verbLemma": "живее",
    "supportWords": [
      "во",
      "град",
      "бидејќи",
      "тука",
      "многу"
    ],
    "variants": [
      {
        "person": "1sg",
        "en": "I live in the city because here I work a lot.",
        "mk": "Живеам во градот бидејќи тука работам многу."
      },
      {
        "person": "2sg",
        "en": "You live in the city because here you work a lot.",
        "mk": "Живееш во градот бидејќи тука работиш многу."
      },
      {
        "person": "3sg",
        "en": "He lives in the city because here he works a lot.",
        "mk": "Живее во градот бидејќи тука работи многу."
      },
      {
        "person": "1pl",
        "en": "We live in the city because here we work a lot.",
        "mk": "Живееме во градот бидејќи тука работиме многу."
      },
      {
        "person": "2pl",
        "en": "You live in the city because here you work a lot.",
        "mk": "Живеете во градот бидејќи тука работите многу."
      },
      {
        "person": "3pl",
        "en": "They live in the city because here they work a lot.",
        "mk": "Живеат во градот бидејќи тука работат многу."
      }
    ],
    "tier": 4,
    "confidence": "unreviewed"
  },
  {
    "id": "sent-зборува",
    "conceptIds": [
      "verb-conjugation"
    ],
    "verbLemma": "зборува",
    "supportWords": [
      "полека"
    ],
    "variants": [
      {
        "person": "1sg",
        "en": "I speak slowly.",
        "mk": "Зборувам полека."
      },
      {
        "person": "2sg",
        "en": "You speak slowly.",
        "mk": "Зборуваш полека."
      },
      {
        "person": "3sg",
        "en": "He/she speaks slowly.",
        "mk": "Зборува полека."
      },
      {
        "person": "1pl",
        "en": "We speak slowly.",
        "mk": "Зборуваме полека."
      },
      {
        "person": "2pl",
        "en": "You speak slowly.",
        "mk": "Зборувате полека."
      },
      {
        "person": "3pl",
        "en": "They speak slowly.",
        "mk": "Зборуваат полека."
      }
    ],
    "confidence": "unreviewed"
  },
  {
    "id": "sent-зборува-t2",
    "conceptIds": [
      "verb-conjugation",
      "definite-articles"
    ],
    "verbLemma": "зборува",
    "supportWords": [
      "полека",
      "со",
      "доктор"
    ],
    "variants": [
      {
        "person": "1sg",
        "en": "I speak slowly with the doctor.",
        "mk": "Зборувам полека со докторот."
      },
      {
        "person": "2sg",
        "en": "You speak slowly with the doctor.",
        "mk": "Зборуваш полека со докторот."
      },
      {
        "person": "3sg",
        "en": "He/she speaks slowly with the doctor.",
        "mk": "Зборува полека со докторот."
      },
      {
        "person": "1pl",
        "en": "We speak slowly with the doctor.",
        "mk": "Зборуваме полека со докторот."
      },
      {
        "person": "2pl",
        "en": "You speak slowly with the doctor.",
        "mk": "Зборувате полека со докторот."
      },
      {
        "person": "3pl",
        "en": "They speak slowly with the doctor.",
        "mk": "Зборуваат полека со докторот."
      }
    ],
    "tier": 2,
    "confidence": "unreviewed"
  },
  {
    "id": "sent-зборува-t3",
    "conceptIds": [
      "verb-conjugation",
      "definite-articles"
    ],
    "verbLemma": "зборува",
    "supportWords": [
      "со",
      "пријател",
      "телефон",
      "секогаш"
    ],
    "variants": [
      {
        "person": "1sg",
        "en": "I always speak with my friend on the phone.",
        "mk": "Секогаш зборувам со пријателот на телефон."
      },
      {
        "person": "2sg",
        "en": "You always speak with your friend on the phone.",
        "mk": "Секогаш зборуваш со пријателот на телефон."
      },
      {
        "person": "3sg",
        "en": "He/she always speaks with the friend on the phone.",
        "mk": "Секогаш зборува со пријателот на телефон."
      },
      {
        "person": "1pl",
        "en": "We always speak with our friend on the phone.",
        "mk": "Секогаш зборуваме со пријателот на телефон."
      },
      {
        "person": "2pl",
        "en": "You always speak with your friend on the phone.",
        "mk": "Секогаш зборувате со пријателот на телефон."
      },
      {
        "person": "3pl",
        "en": "They always speak with the friend on the phone.",
        "mk": "Секогаш зборуваат со пријателот на телефон."
      }
    ],
    "tier": 3,
    "confidence": "unreviewed"
  },
  {
    "id": "sent-зборува-t4",
    "conceptIds": [
      "verb-conjugation",
      "definite-articles"
    ],
    "verbLemma": "зборува",
    "supportWords": [
      "полека",
      "бидејќи",
      "доктор",
      "болен"
    ],
    "variants": [
      {
        "person": "1sg",
        "en": "I speak slowly with the doctor because I am sick today.",
        "mk": "Зборувам полека со докторот бидејќи денес сум болен."
      },
      {
        "person": "2sg",
        "en": "You speak slowly with the doctor because you are sick today.",
        "mk": "Зборуваш полека со докторот бидејќи денес си болен."
      },
      {
        "person": "3sg",
        "en": "He speaks slowly with the doctor because he is sick today.",
        "mk": "Зборува полека со докторот бидејќи денес е болен."
      },
      {
        "person": "1pl",
        "en": "We speak slowly with the doctor because we are sick today.",
        "mk": "Зборуваме полека со докторот бидејќи денес сме болни."
      },
      {
        "person": "2pl",
        "en": "You speak slowly with the doctor because you are sick today.",
        "mk": "Зборувате полека со докторот бидејќи денес сте болни."
      },
      {
        "person": "3pl",
        "en": "They speak slowly with the doctor because they are sick today.",
        "mk": "Зборуваат полека со докторот бидејќи денес се болни."
      }
    ],
    "tier": 4,
    "confidence": "unreviewed"
  },
  {
    "id": "sent-зема",
    "conceptIds": [
      "verb-conjugation",
      "definite-articles"
    ],
    "verbLemma": "зема",
    "supportWords": [
      "клуч"
    ],
    "variants": [
      {
        "person": "1sg",
        "en": "I take the key.",
        "mk": "Го земам клучот."
      },
      {
        "person": "2sg",
        "en": "You take the key.",
        "mk": "Го земаш клучот."
      },
      {
        "person": "3sg",
        "en": "He/she takes the key.",
        "mk": "Го зема клучот."
      },
      {
        "person": "1pl",
        "en": "We take the key.",
        "mk": "Го земаме клучот."
      },
      {
        "person": "2pl",
        "en": "You take the key.",
        "mk": "Го земате клучот."
      },
      {
        "person": "3pl",
        "en": "They take the key.",
        "mk": "Го земаат клучот."
      }
    ],
    "confidence": "unreviewed"
  },
  {
    "id": "sent-зема-t2",
    "conceptIds": [
      "verb-conjugation"
    ],
    "verbLemma": "зема",
    "supportWords": [
      "студен",
      "сок"
    ],
    "variants": [
      {
        "person": "1sg",
        "en": "I take cold juice.",
        "mk": "Земам студен сок."
      },
      {
        "person": "2sg",
        "en": "You take cold juice.",
        "mk": "Земаш студен сок."
      },
      {
        "person": "3sg",
        "en": "He/she takes cold juice.",
        "mk": "Зема студен сок."
      },
      {
        "person": "1pl",
        "en": "We take cold juice.",
        "mk": "Земаме студен сок."
      },
      {
        "person": "2pl",
        "en": "You take cold juice.",
        "mk": "Земате студен сок."
      },
      {
        "person": "3pl",
        "en": "They take cold juice.",
        "mk": "Земаат студен сок."
      }
    ],
    "tier": 2,
    "confidence": "unreviewed"
  },
  {
    "id": "sent-зема-t3",
    "conceptIds": [
      "verb-conjugation",
      "definite-articles"
    ],
    "verbLemma": "зема",
    "supportWords": [
      "билет",
      "за",
      "воз",
      "сега"
    ],
    "variants": [
      {
        "person": "1sg",
        "en": "Now I take a ticket for the train.",
        "mk": "Сега земам билет за возот."
      },
      {
        "person": "2sg",
        "en": "Now you take a ticket for the train.",
        "mk": "Сега земаш билет за возот."
      },
      {
        "person": "3sg",
        "en": "Now he/she takes a ticket for the train.",
        "mk": "Сега зема билет за возот."
      },
      {
        "person": "1pl",
        "en": "Now we take a ticket for the train.",
        "mk": "Сега земаме билет за возот."
      },
      {
        "person": "2pl",
        "en": "Now you take a ticket for the train.",
        "mk": "Сега земате билет за возот."
      },
      {
        "person": "3pl",
        "en": "Now they take a ticket for the train.",
        "mk": "Сега земаат билет за возот."
      }
    ],
    "tier": 3,
    "confidence": "unreviewed"
  },
  {
    "id": "sent-зема-t4",
    "conceptIds": [
      "verb-conjugation",
      "definite-articles"
    ],
    "verbLemma": "зема",
    "supportWords": [
      "такси",
      "бидејќи",
      "дожд",
      "голем"
    ],
    "variants": [
      {
        "person": "1sg",
        "en": "Today I take a taxi because the rain is heavy.",
        "mk": "Денес земам такси бидејќи дождот е голем."
      },
      {
        "person": "2sg",
        "en": "Today you take a taxi because the rain is heavy.",
        "mk": "Денес земаш такси бидејќи дождот е голем."
      },
      {
        "person": "3sg",
        "en": "Today he/she takes a taxi because the rain is heavy.",
        "mk": "Денес зема такси бидејќи дождот е голем."
      },
      {
        "person": "1pl",
        "en": "Today we take a taxi because the rain is heavy.",
        "mk": "Денес земаме такси бидејќи дождот е голем."
      },
      {
        "person": "2pl",
        "en": "Today you take a taxi because the rain is heavy.",
        "mk": "Денес земате такси бидејќи дождот е голем."
      },
      {
        "person": "3pl",
        "en": "Today they take a taxi because the rain is heavy.",
        "mk": "Денес земаат такси бидејќи дождот е голем."
      }
    ],
    "tier": 4,
    "confidence": "unreviewed"
  },
  {
    "id": "sent-знае",
    "conceptIds": [
      "verb-conjugation",
      "definite-articles"
    ],
    "verbLemma": "знае",
    "supportWords": [
      "пат"
    ],
    "variants": [
      {
        "person": "1sg",
        "en": "I know the way.",
        "mk": "Го знам патот."
      },
      {
        "person": "2sg",
        "en": "You know the way.",
        "mk": "Го знаеш патот."
      },
      {
        "person": "3sg",
        "en": "He/She knows the way.",
        "mk": "Го знае патот."
      },
      {
        "person": "1pl",
        "en": "We know the way.",
        "mk": "Го знаеме патот."
      },
      {
        "person": "2pl",
        "en": "You know the way.",
        "mk": "Го знаете патот."
      },
      {
        "person": "3pl",
        "en": "They know the way.",
        "mk": "Го знаат патот."
      }
    ],
    "confidence": "unreviewed"
  },
  {
    "id": "sent-знае-t2",
    "conceptIds": [
      "verb-conjugation",
      "definite-articles"
    ],
    "verbLemma": "знае",
    "supportWords": [
      "добро",
      "пат"
    ],
    "variants": [
      {
        "person": "1sg",
        "en": "I know the way well.",
        "mk": "Го знам добро патот."
      },
      {
        "person": "2sg",
        "en": "You know the way well.",
        "mk": "Го знаеш добро патот."
      },
      {
        "person": "3sg",
        "en": "He knows the way well.",
        "mk": "Го знае добро патот."
      },
      {
        "person": "1pl",
        "en": "We know the way well.",
        "mk": "Го знаеме добро патот."
      },
      {
        "person": "2pl",
        "en": "You know the way well.",
        "mk": "Го знаете добро патот."
      },
      {
        "person": "3pl",
        "en": "They know the way well.",
        "mk": "Го знаат добро патот."
      }
    ],
    "tier": 2,
    "confidence": "unreviewed"
  },
  {
    "id": "sent-знае-t3",
    "conceptIds": [
      "verb-conjugation",
      "definite-articles"
    ],
    "verbLemma": "знае",
    "supportWords": [
      "цена",
      "нов",
      "телефон"
    ],
    "variants": [
      {
        "person": "1sg",
        "en": "I know the price of the new phone.",
        "mk": "Ја знам цената на новиот телефон."
      },
      {
        "person": "2sg",
        "en": "You know the price of the new phone.",
        "mk": "Ја знаеш цената на новиот телефон."
      },
      {
        "person": "3sg",
        "en": "She knows the price of the new phone.",
        "mk": "Ја знае цената на новиот телефон."
      },
      {
        "person": "1pl",
        "en": "We know the price of the new phone.",
        "mk": "Ја знаеме цената на новиот телефон."
      },
      {
        "person": "2pl",
        "en": "You know the price of the new phone.",
        "mk": "Ја знаете цената на новиот телефон."
      },
      {
        "person": "3pl",
        "en": "They know the price of the new phone.",
        "mk": "Ја знаат цената на новиот телефон."
      }
    ],
    "tier": 3,
    "confidence": "unreviewed"
  },
  {
    "id": "sent-знае-t4",
    "conceptIds": [
      "verb-conjugation",
      "definite-articles"
    ],
    "verbLemma": "знае",
    "supportWords": [
      "добро",
      "град",
      "бидејќи",
      "таму"
    ],
    "variants": [
      {
        "person": "1sg",
        "en": "I know the city well because I live there.",
        "mk": "Го знам добро градот бидејќи живеам таму."
      },
      {
        "person": "2sg",
        "en": "You know the city well because you live there.",
        "mk": "Го знаеш добро градот бидејќи живееш таму."
      },
      {
        "person": "3sg",
        "en": "He knows the city well because he lives there.",
        "mk": "Го знае добро градот бидејќи живее таму."
      },
      {
        "person": "1pl",
        "en": "We know the city well because we live there.",
        "mk": "Го знаеме добро градот бидејќи живееме таму."
      },
      {
        "person": "2pl",
        "en": "You know the city well because you live there.",
        "mk": "Го знаете добро градот бидејќи живеете таму."
      },
      {
        "person": "3pl",
        "en": "They know the city well because they live there.",
        "mk": "Го знаат добро градот бидејќи живеат таму."
      }
    ],
    "tier": 4,
    "confidence": "unreviewed"
  },
  {
    "id": "sent-има",
    "conceptIds": [
      "verb-conjugation"
    ],
    "verbLemma": "има",
    "supportWords": [
      "пари"
    ],
    "variants": [
      {
        "person": "1sg",
        "en": "I have money.",
        "mk": "Имам пари."
      },
      {
        "person": "2sg",
        "en": "You have money.",
        "mk": "Имаш пари."
      },
      {
        "person": "3sg",
        "en": "He/she has money.",
        "mk": "Има пари."
      },
      {
        "person": "1pl",
        "en": "We have money.",
        "mk": "Имаме пари."
      },
      {
        "person": "2pl",
        "en": "You have money.",
        "mk": "Имате пари."
      },
      {
        "person": "3pl",
        "en": "They have money.",
        "mk": "Имаат пари."
      }
    ],
    "confidence": "unreviewed"
  },
  {
    "id": "sent-има-t2",
    "conceptIds": [
      "verb-conjugation"
    ],
    "verbLemma": "има",
    "supportWords": [
      "нов",
      "телефон"
    ],
    "variants": [
      {
        "person": "1sg",
        "en": "I have a new phone.",
        "mk": "Имам нов телефон."
      },
      {
        "person": "2sg",
        "en": "You have a new phone.",
        "mk": "Имаш нов телефон."
      },
      {
        "person": "3sg",
        "en": "He has a new phone.",
        "mk": "Има нов телефон."
      },
      {
        "person": "1pl",
        "en": "We have a new phone.",
        "mk": "Имаме нов телефон."
      },
      {
        "person": "2pl",
        "en": "You have a new phone.",
        "mk": "Имате нов телефон."
      },
      {
        "person": "3pl",
        "en": "They have a new phone.",
        "mk": "Имаат нов телефон."
      }
    ],
    "tier": 2,
    "confidence": "unreviewed"
  },
  {
    "id": "sent-има-t3",
    "conceptIds": [
      "verb-conjugation",
      "definite-articles"
    ],
    "verbLemma": "има",
    "supportWords": [
      "голем",
      "куќа",
      "град"
    ],
    "variants": [
      {
        "person": "1sg",
        "en": "I have a big house in the city.",
        "mk": "Имам голема куќа во градот."
      },
      {
        "person": "2sg",
        "en": "You have a big house in the city.",
        "mk": "Имаш голема куќа во градот."
      },
      {
        "person": "3sg",
        "en": "She has a big house in the city.",
        "mk": "Има голема куќа во градот."
      },
      {
        "person": "1pl",
        "en": "We have a big house in the city.",
        "mk": "Имаме голема куќа во градот."
      },
      {
        "person": "2pl",
        "en": "You have a big house in the city.",
        "mk": "Имате голема куќа во градот."
      },
      {
        "person": "3pl",
        "en": "They have a big house in the city.",
        "mk": "Имаат голема куќа во градот."
      }
    ],
    "tier": 3,
    "confidence": "unreviewed"
  },
  {
    "id": "sent-има-t4",
    "conceptIds": [
      "verb-conjugation",
      "definite-articles"
    ],
    "verbLemma": "има",
    "supportWords": [
      "пари",
      "сега",
      "затоа",
      "нов",
      "стан"
    ],
    "variants": [
      {
        "person": "1sg",
        "en": "I have money now, therefore I want a new apartment.",
        "mk": "Сега имам пари, затоа сакам нов стан."
      },
      {
        "person": "2sg",
        "en": "You have money now, therefore you want a new apartment.",
        "mk": "Сега имаш пари, затоа сакаш нов стан."
      },
      {
        "person": "3sg",
        "en": "He has money now, therefore he wants a new apartment.",
        "mk": "Сега има пари, затоа сака нов стан."
      },
      {
        "person": "1pl",
        "en": "We have money now, therefore we want a new apartment.",
        "mk": "Сега имаме пари, затоа сакаме нов стан."
      },
      {
        "person": "2pl",
        "en": "You have money now, therefore you want a new apartment.",
        "mk": "Сега имате пари, затоа сакате нов стан."
      },
      {
        "person": "3pl",
        "en": "They have money now, therefore they want a new apartment.",
        "mk": "Сега имаат пари, затоа сакаат нов стан."
      }
    ],
    "tier": 4,
    "confidence": "unreviewed"
  },
  {
    "id": "sent-јаде",
    "conceptIds": [
      "verb-conjugation"
    ],
    "verbLemma": "јаде",
    "supportWords": [
      "леб"
    ],
    "variants": [
      {
        "person": "1sg",
        "en": "I eat bread.",
        "mk": "Јадам леб."
      },
      {
        "person": "2sg",
        "en": "You eat bread.",
        "mk": "Јадеш леб."
      },
      {
        "person": "3sg",
        "en": "He/she eats bread.",
        "mk": "Јаде леб."
      },
      {
        "person": "1pl",
        "en": "We eat bread.",
        "mk": "Јадеме леб."
      },
      {
        "person": "2pl",
        "en": "You eat bread.",
        "mk": "Јадете леб."
      },
      {
        "person": "3pl",
        "en": "They eat bread.",
        "mk": "Јадат леб."
      }
    ],
    "confidence": "unreviewed"
  },
  {
    "id": "sent-јаде-t2",
    "conceptIds": [
      "verb-conjugation"
    ],
    "verbLemma": "јаде",
    "supportWords": [
      "риба",
      "многу"
    ],
    "variants": [
      {
        "person": "1sg",
        "en": "I eat a lot of fish.",
        "mk": "Јадам многу риба."
      },
      {
        "person": "2sg",
        "en": "You eat a lot of fish.",
        "mk": "Јадеш многу риба."
      },
      {
        "person": "3sg",
        "en": "He/she eats a lot of fish.",
        "mk": "Јаде многу риба."
      },
      {
        "person": "1pl",
        "en": "We eat a lot of fish.",
        "mk": "Јадеме многу риба."
      },
      {
        "person": "2pl",
        "en": "You eat a lot of fish.",
        "mk": "Јадете многу риба."
      },
      {
        "person": "3pl",
        "en": "They eat a lot of fish.",
        "mk": "Јадат многу риба."
      }
    ],
    "tier": 2,
    "confidence": "unreviewed"
  },
  {
    "id": "sent-јаде-t3",
    "conceptIds": [
      "verb-conjugation"
    ],
    "verbLemma": "јаде",
    "supportWords": [
      "риба",
      "секогаш",
      "тука"
    ],
    "variants": [
      {
        "person": "1sg",
        "en": "I always eat fish here.",
        "mk": "Секогаш јадам риба тука."
      },
      {
        "person": "2sg",
        "en": "You always eat fish here.",
        "mk": "Секогаш јадеш риба тука."
      },
      {
        "person": "3sg",
        "en": "He/she always eats fish here.",
        "mk": "Секогаш јаде риба тука."
      },
      {
        "person": "1pl",
        "en": "We always eat fish here.",
        "mk": "Секогаш јадеме риба тука."
      },
      {
        "person": "2pl",
        "en": "You always eat fish here.",
        "mk": "Секогаш јадете риба тука."
      },
      {
        "person": "3pl",
        "en": "They always eat fish here.",
        "mk": "Секогаш јадат риба тука."
      }
    ],
    "tier": 3,
    "confidence": "unreviewed"
  },
  {
    "id": "sent-јаде-t4",
    "conceptIds": [
      "verb-conjugation"
    ],
    "verbLemma": "јаде",
    "supportWords": [
      "зеленчук",
      "денес",
      "бидејќи",
      "болен"
    ],
    "variants": [
      {
        "person": "1sg",
        "en": "Today I'm eating only vegetables because I'm sick.",
        "mk": "Денес јадам само зеленчук бидејќи сум болен."
      },
      {
        "person": "2sg",
        "en": "Today you're eating only vegetables because you're sick.",
        "mk": "Денес јадеш само зеленчук бидејќи си болен."
      },
      {
        "person": "3sg",
        "en": "Today he's eating only vegetables because he's sick.",
        "mk": "Денес јаде само зеленчук бидејќи е болен."
      },
      {
        "person": "1pl",
        "en": "Today we're eating only vegetables because we're sick.",
        "mk": "Денес јадеме само зеленчук бидејќи сме болни."
      },
      {
        "person": "2pl",
        "en": "Today you're eating only vegetables because you're sick.",
        "mk": "Денес јадете само зеленчук бидејќи сте болни."
      },
      {
        "person": "3pl",
        "en": "Today they're eating only vegetables because they're sick.",
        "mk": "Денес јадат само зеленчук бидејќи се болни."
      }
    ],
    "tier": 4,
    "confidence": "unreviewed"
  },
  {
    "id": "sent-купува",
    "conceptIds": [
      "verb-conjugation"
    ],
    "verbLemma": "купува",
    "supportWords": [
      "риба"
    ],
    "variants": [
      {
        "person": "1sg",
        "en": "I buy fish.",
        "mk": "Купувам риба."
      },
      {
        "person": "2sg",
        "en": "You buy fish.",
        "mk": "Купуваш риба."
      },
      {
        "person": "3sg",
        "en": "He/she buys fish.",
        "mk": "Купува риба."
      },
      {
        "person": "1pl",
        "en": "We buy fish.",
        "mk": "Купуваме риба."
      },
      {
        "person": "2pl",
        "en": "You buy fish.",
        "mk": "Купувате риба."
      },
      {
        "person": "3pl",
        "en": "They buy fish.",
        "mk": "Купуваат риба."
      }
    ],
    "confidence": "unreviewed"
  },
  {
    "id": "sent-купува-t2",
    "conceptIds": [
      "verb-conjugation"
    ],
    "verbLemma": "купува",
    "supportWords": [
      "леб"
    ],
    "variants": [
      {
        "person": "1sg",
        "en": "I buy warm bread.",
        "mk": "Купувам топол леб."
      },
      {
        "person": "2sg",
        "en": "You buy warm bread.",
        "mk": "Купуваш топол леб."
      },
      {
        "person": "3sg",
        "en": "He/She buys warm bread.",
        "mk": "Купува топол леб."
      },
      {
        "person": "1pl",
        "en": "We buy warm bread.",
        "mk": "Купуваме топол леб."
      },
      {
        "person": "2pl",
        "en": "You buy warm bread.",
        "mk": "Купувате топол леб."
      },
      {
        "person": "3pl",
        "en": "They buy warm bread.",
        "mk": "Купуваат топол леб."
      }
    ],
    "tier": 2,
    "confidence": "unreviewed"
  },
  {
    "id": "sent-купува-t3",
    "conceptIds": [
      "verb-conjugation",
      "definite-articles"
    ],
    "verbLemma": "купува",
    "supportWords": [
      "овошје",
      "пазар",
      "денес"
    ],
    "variants": [
      {
        "person": "1sg",
        "en": "Today I buy fruit at the market.",
        "mk": "Денес купувам овошје на пазарот."
      },
      {
        "person": "2sg",
        "en": "Today you buy fruit at the market.",
        "mk": "Денес купуваш овошје на пазарот."
      },
      {
        "person": "3sg",
        "en": "Today he/she buys fruit at the market.",
        "mk": "Денес купува овошје на пазарот."
      },
      {
        "person": "1pl",
        "en": "Today we buy fruit at the market.",
        "mk": "Денес купуваме овошје на пазарот."
      },
      {
        "person": "2pl",
        "en": "Today you buy fruit at the market.",
        "mk": "Денес купувате овошје на пазарот."
      },
      {
        "person": "3pl",
        "en": "Today they buy fruit at the market.",
        "mk": "Денес купуваат овошје на пазарот."
      }
    ],
    "tier": 3,
    "confidence": "unreviewed"
  },
  {
    "id": "sent-купува-t4",
    "conceptIds": [
      "verb-conjugation",
      "definite-articles"
    ],
    "verbLemma": "купува",
    "supportWords": [
      "риба",
      "пазар",
      "евтин",
      "таму"
    ],
    "variants": [
      {
        "person": "1sg",
        "en": "I buy fish at the market because it is cheap there.",
        "mk": "Купувам риба на пазарот бидејќи е евтина таму."
      },
      {
        "person": "2sg",
        "en": "You buy fish at the market because it is cheap there.",
        "mk": "Купуваш риба на пазарот бидејќи е евтина таму."
      },
      {
        "person": "3sg",
        "en": "He/She buys fish at the market because it is cheap there.",
        "mk": "Купува риба на пазарот бидејќи е евтина таму."
      },
      {
        "person": "1pl",
        "en": "We buy fish at the market because it is cheap there.",
        "mk": "Купуваме риба на пазарот бидејќи е евтина таму."
      },
      {
        "person": "2pl",
        "en": "You buy fish at the market because it is cheap there.",
        "mk": "Купувате риба на пазарот бидејќи е евтина таму."
      },
      {
        "person": "3pl",
        "en": "They buy fish at the market because it is cheap there.",
        "mk": "Купуваат риба на пазарот бидејќи е евтина таму."
      }
    ],
    "tier": 4,
    "confidence": "unreviewed"
  },
  {
    "id": "sent-може",
    "conceptIds": [
      "verb-conjugation"
    ],
    "verbLemma": "може",
    "supportWords": [
      "работам",
      "брзо"
    ],
    "variants": [
      {
        "person": "1sg",
        "en": "I can work quickly.",
        "mk": "Можам да работам брзо."
      },
      {
        "person": "2sg",
        "en": "You can work quickly.",
        "mk": "Можеш да работиш брзо."
      },
      {
        "person": "3sg",
        "en": "He/she can work quickly.",
        "mk": "Може да работи брзо."
      },
      {
        "person": "1pl",
        "en": "We can work quickly.",
        "mk": "Можеме да работиме брзо."
      },
      {
        "person": "2pl",
        "en": "You can work quickly.",
        "mk": "Можете да работите брзо."
      },
      {
        "person": "3pl",
        "en": "They can work quickly.",
        "mk": "Можат да работат брзо."
      }
    ],
    "confidence": "unreviewed"
  },
  {
    "id": "sent-може-t2",
    "conceptIds": [
      "verb-conjugation"
    ],
    "verbLemma": "може",
    "supportWords": [
      "спијам",
      "тука"
    ],
    "variants": [
      {
        "person": "1sg",
        "en": "I can sleep here.",
        "mk": "Можам да спијам тука."
      },
      {
        "person": "2sg",
        "en": "You can sleep here.",
        "mk": "Можеш да спиеш тука."
      },
      {
        "person": "3sg",
        "en": "He can sleep here.",
        "mk": "Може да спие тука."
      },
      {
        "person": "1pl",
        "en": "We can sleep here.",
        "mk": "Можеме да спиеме тука."
      },
      {
        "person": "2pl",
        "en": "You can sleep here.",
        "mk": "Можете да спиете тука."
      },
      {
        "person": "3pl",
        "en": "They can sleep here.",
        "mk": "Можат да спијат тука."
      }
    ],
    "tier": 2,
    "confidence": "unreviewed"
  },
  {
    "id": "sent-може-t3",
    "conceptIds": [
      "verb-conjugation",
      "definite-articles"
    ],
    "verbLemma": "може",
    "supportWords": [
      "видам",
      "планина",
      "од",
      "тука"
    ],
    "variants": [
      {
        "person": "1sg",
        "en": "I can see the mountain from here.",
        "mk": "Можам да ја видам планината од тука."
      },
      {
        "person": "2sg",
        "en": "You can see the mountain from here.",
        "mk": "Можеш да ја видиш планината од тука."
      },
      {
        "person": "3sg",
        "en": "He/she can see the mountain from here.",
        "mk": "Може да ја види планината од тука."
      },
      {
        "person": "1pl",
        "en": "We can see the mountain from here.",
        "mk": "Можеме да ја видиме планината од тука."
      },
      {
        "person": "2pl",
        "en": "You can see the mountain from here.",
        "mk": "Можете да ја видите планината од тука."
      },
      {
        "person": "3pl",
        "en": "They can see the mountain from here.",
        "mk": "Можат да ја видат планината од тука."
      }
    ],
    "tier": 3,
    "confidence": "unreviewed"
  },
  {
    "id": "sent-може-t4",
    "conceptIds": [
      "verb-conjugation",
      "definite-articles"
    ],
    "verbLemma": "може",
    "supportWords": [
      "одам",
      "град",
      "бидејќи",
      "имам",
      "пари"
    ],
    "variants": [
      {
        "person": "1sg",
        "en": "I can go to the city because I have money.",
        "mk": "Можам да одам во градот бидејќи имам пари."
      },
      {
        "person": "2sg",
        "en": "You can go to the city because you have money.",
        "mk": "Можеш да одиш во градот бидејќи имаш пари."
      },
      {
        "person": "3sg",
        "en": "He can go to the city because he has money.",
        "mk": "Може да оди во градот бидејќи има пари."
      },
      {
        "person": "1pl",
        "en": "We can go to the city because we have money.",
        "mk": "Можеме да одиме во градот бидејќи имаме пари."
      },
      {
        "person": "2pl",
        "en": "You can go to the city because you have money.",
        "mk": "Можете да одите во градот бидејќи имате пари."
      },
      {
        "person": "3pl",
        "en": "They can go to the city because they have money.",
        "mk": "Можат да одат во градот бидејќи имаат пари."
      }
    ],
    "tier": 4,
    "confidence": "unreviewed"
  },
  {
    "id": "sent-оди",
    "conceptIds": [
      "verb-conjugation"
    ],
    "verbLemma": "оди",
    "supportWords": [
      "таму"
    ],
    "variants": [
      {
        "person": "1sg",
        "en": "I go there.",
        "mk": "Одам таму."
      },
      {
        "person": "2sg",
        "en": "You go there.",
        "mk": "Одиш таму."
      },
      {
        "person": "3sg",
        "en": "He/she goes there.",
        "mk": "Оди таму."
      },
      {
        "person": "1pl",
        "en": "We go there.",
        "mk": "Одиме таму."
      },
      {
        "person": "2pl",
        "en": "You go there.",
        "mk": "Одите таму."
      },
      {
        "person": "3pl",
        "en": "They go there.",
        "mk": "Одат таму."
      }
    ],
    "confidence": "unreviewed"
  },
  {
    "id": "sent-оди-t2",
    "conceptIds": [
      "verb-conjugation",
      "definite-articles"
    ],
    "verbLemma": "оди",
    "supportWords": [
      "на",
      "пазар"
    ],
    "variants": [
      {
        "person": "1sg",
        "en": "I'm going to the market.",
        "mk": "Одам на пазар."
      },
      {
        "person": "2sg",
        "en": "You're going to the market.",
        "mk": "Одиш на пазар."
      },
      {
        "person": "3sg",
        "en": "He's going to the market.",
        "mk": "Оди на пазар."
      },
      {
        "person": "1pl",
        "en": "We're going to the market.",
        "mk": "Одиме на пазар."
      },
      {
        "person": "2pl",
        "en": "You're going to the market.",
        "mk": "Одите на пазар."
      },
      {
        "person": "3pl",
        "en": "They're going to the market.",
        "mk": "Одат на пазар."
      }
    ],
    "tier": 2,
    "confidence": "unreviewed"
  },
  {
    "id": "sent-оди-t4",
    "conceptIds": [
      "verb-conjugation",
      "definite-articles"
    ],
    "verbLemma": "оди",
    "supportWords": [
      "во",
      "град",
      "денес",
      "со",
      "пријател"
    ],
    "variants": [
      {
        "person": "1sg",
        "en": "Today I'm going into the city with a friend after work.",
        "mk": "Денес одам во градот со пријател по работа."
      },
      {
        "person": "2sg",
        "en": "Today you're going into the city with a friend after work.",
        "mk": "Денес одиш во градот со пријател по работа."
      },
      {
        "person": "3sg",
        "en": "Today he's going into the city with a friend after work.",
        "mk": "Денес оди во градот со пријател по работа."
      },
      {
        "person": "1pl",
        "en": "Today we're going into the city with a friend after work.",
        "mk": "Денес одиме во градот со пријател по работа."
      },
      {
        "person": "2pl",
        "en": "Today you're going into the city with a friend after work.",
        "mk": "Денес одите во градот со пријател по работа."
      },
      {
        "person": "3pl",
        "en": "Today they're going into the city with a friend after work.",
        "mk": "Денес одат во градот со пријател по работа."
      }
    ],
    "tier": 4,
    "confidence": "unreviewed"
  },
  {
    "id": "sent-пие",
    "conceptIds": [
      "verb-conjugation"
    ],
    "verbLemma": "пие",
    "supportWords": [
      "кафе"
    ],
    "variants": [
      {
        "person": "1sg",
        "en": "I drink coffee.",
        "mk": "Пијам кафе."
      },
      {
        "person": "2sg",
        "en": "You drink coffee.",
        "mk": "Пиеш кафе."
      },
      {
        "person": "3sg",
        "en": "He/she drinks coffee.",
        "mk": "Пие кафе."
      },
      {
        "person": "1pl",
        "en": "We drink coffee.",
        "mk": "Пиеме кафе."
      },
      {
        "person": "2pl",
        "en": "You drink coffee.",
        "mk": "Пиете кафе."
      },
      {
        "person": "3pl",
        "en": "They drink coffee.",
        "mk": "Пијат кафе."
      }
    ],
    "confidence": "unreviewed"
  },
  {
    "id": "sent-пие-t2",
    "conceptIds": [
      "verb-conjugation"
    ],
    "verbLemma": "пие",
    "supportWords": [
      "студен",
      "сок"
    ],
    "variants": [
      {
        "person": "1sg",
        "en": "I drink cold juice.",
        "mk": "Пијам студен сок."
      },
      {
        "person": "2sg",
        "en": "You drink cold juice.",
        "mk": "Пиеш студен сок."
      },
      {
        "person": "3sg",
        "en": "He/she drinks cold juice.",
        "mk": "Пие студен сок."
      },
      {
        "person": "1pl",
        "en": "We drink cold juice.",
        "mk": "Пиеме студен сок."
      },
      {
        "person": "2pl",
        "en": "You drink cold juice.",
        "mk": "Пиете студен сок."
      },
      {
        "person": "3pl",
        "en": "They drink cold juice.",
        "mk": "Пијат студен сок."
      }
    ],
    "tier": 2,
    "confidence": "unreviewed"
  },
  {
    "id": "sent-пие-t4",
    "conceptIds": [
      "verb-conjugation"
    ],
    "verbLemma": "пие",
    "supportWords": [
      "чај",
      "топол",
      "пазар"
    ],
    "variants": [
      {
        "person": "1sg",
        "en": "After the market I drink warm tea with my grandmother.",
        "mk": "По пазарот пијам топол чај со мојата баба."
      },
      {
        "person": "2sg",
        "en": "After the market you drink warm tea with your grandmother.",
        "mk": "По пазарот пиеш топол чај со твојата баба."
      },
      {
        "person": "3sg",
        "en": "After the market he/she drinks warm tea with his/her grandmother.",
        "mk": "По пазарот пие топол чај со неговата баба."
      },
      {
        "person": "1pl",
        "en": "After the market we drink warm tea with our grandmother.",
        "mk": "По пазарот пиеме топол чај со нашата баба."
      },
      {
        "person": "2pl",
        "en": "After the market you drink warm tea with your grandmother.",
        "mk": "По пазарот пиете топол чај со вашата баба."
      },
      {
        "person": "3pl",
        "en": "After the market they drink warm tea with their grandmother.",
        "mk": "По пазарот пијат топол чај со нивната баба."
      }
    ],
    "tier": 4,
    "confidence": "unreviewed"
  },
  {
    "id": "sent-плаќа",
    "conceptIds": [
      "verb-conjugation"
    ],
    "verbLemma": "плаќа",
    "supportWords": [
      "сега"
    ],
    "variants": [
      {
        "person": "1sg",
        "en": "I pay now.",
        "mk": "Плаќам сега."
      },
      {
        "person": "2sg",
        "en": "You pay now.",
        "mk": "Плаќаш сега."
      },
      {
        "person": "3sg",
        "en": "He/she pays now.",
        "mk": "Плаќа сега."
      },
      {
        "person": "1pl",
        "en": "We pay now.",
        "mk": "Плаќаме сега."
      },
      {
        "person": "2pl",
        "en": "You pay now.",
        "mk": "Плаќате сега."
      },
      {
        "person": "3pl",
        "en": "They pay now.",
        "mk": "Плаќаат сега."
      }
    ],
    "confidence": "unreviewed"
  },
  {
    "id": "sent-плаќа-t2",
    "conceptIds": [
      "verb-conjugation"
    ],
    "verbLemma": "плаќа",
    "supportWords": [
      "со",
      "пари"
    ],
    "variants": [
      {
        "person": "1sg",
        "en": "I pay with cash.",
        "mk": "Плаќам со пари."
      },
      {
        "person": "2sg",
        "en": "You pay with cash.",
        "mk": "Плаќаш со пари."
      },
      {
        "person": "3sg",
        "en": "He pays with cash.",
        "mk": "Плаќа со пари."
      },
      {
        "person": "1pl",
        "en": "We pay with cash.",
        "mk": "Плаќаме со пари."
      },
      {
        "person": "2pl",
        "en": "You pay with cash.",
        "mk": "Плаќате со пари."
      },
      {
        "person": "3pl",
        "en": "They pay with cash.",
        "mk": "Плаќаат со пари."
      }
    ],
    "tier": 2,
    "confidence": "unreviewed"
  },
  {
    "id": "sent-плаќа-t3",
    "conceptIds": [
      "verb-conjugation",
      "definite-articles"
    ],
    "verbLemma": "плаќа",
    "supportWords": [
      "билет",
      "на",
      "аеродром"
    ],
    "variants": [
      {
        "person": "1sg",
        "en": "I pay for the ticket at the airport.",
        "mk": "Го плаќам билетот на аеродромот."
      },
      {
        "person": "2sg",
        "en": "You pay for the ticket at the airport.",
        "mk": "Го плаќаш билетот на аеродромот."
      },
      {
        "person": "3sg",
        "en": "She pays for the ticket at the airport.",
        "mk": "Го плаќа билетот на аеродромот."
      },
      {
        "person": "1pl",
        "en": "We pay for the ticket at the airport.",
        "mk": "Го плаќаме билетот на аеродромот."
      },
      {
        "person": "2pl",
        "en": "You pay for the ticket at the airport.",
        "mk": "Го плаќате билетот на аеродромот."
      },
      {
        "person": "3pl",
        "en": "They pay for the ticket at the airport.",
        "mk": "Го плаќаат билетот на аеродромот."
      }
    ],
    "tier": 3,
    "confidence": "unreviewed"
  },
  {
    "id": "sent-плаќа-t4",
    "conceptIds": [
      "verb-conjugation",
      "definite-articles"
    ],
    "verbLemma": "плаќа",
    "supportWords": [
      "билет",
      "за",
      "воз",
      "бидејќи",
      "имам",
      "пари"
    ],
    "variants": [
      {
        "person": "1sg",
        "en": "I pay for the ticket for the train because I have money.",
        "mk": "Го плаќам билетот за возот бидејќи имам пари."
      },
      {
        "person": "2sg",
        "en": "You pay for the ticket for the train because you have money.",
        "mk": "Го плаќаш билетот за возот бидејќи имаш пари."
      },
      {
        "person": "3sg",
        "en": "He pays for the ticket for the train because he has money.",
        "mk": "Го плаќа билетот за возот бидејќи има пари."
      },
      {
        "person": "1pl",
        "en": "We pay for the ticket for the train because we have money.",
        "mk": "Го плаќаме билетот за возот бидејќи имаме пари."
      },
      {
        "person": "2pl",
        "en": "You pay for the ticket for the train because you have money.",
        "mk": "Го плаќате билетот за возот бидејќи имате пари."
      },
      {
        "person": "3pl",
        "en": "They pay for the ticket for the train because they have money.",
        "mk": "Го плаќаат билетот за возот бидејќи имаат пари."
      }
    ],
    "tier": 4,
    "confidence": "unreviewed"
  },
  {
    "id": "sent-прашува",
    "conceptIds": [
      "verb-conjugation",
      "definite-articles"
    ],
    "verbLemma": "прашува",
    "supportWords": [
      "доктор"
    ],
    "variants": [
      {
        "person": "1sg",
        "en": "I ask the doctor.",
        "mk": "Го прашувам докторот."
      },
      {
        "person": "2sg",
        "en": "You ask the doctor.",
        "mk": "Го прашуваш докторот."
      },
      {
        "person": "3sg",
        "en": "He/she asks the doctor.",
        "mk": "Го прашува докторот."
      },
      {
        "person": "1pl",
        "en": "We ask the doctor.",
        "mk": "Го прашуваме докторот."
      },
      {
        "person": "2pl",
        "en": "You ask the doctor.",
        "mk": "Го прашувате докторот."
      },
      {
        "person": "3pl",
        "en": "They ask the doctor.",
        "mk": "Го прашуваат докторот."
      }
    ],
    "confidence": "unreviewed"
  },
  {
    "id": "sent-прашува-t3",
    "conceptIds": [
      "verb-conjugation",
      "definite-articles"
    ],
    "verbLemma": "прашува",
    "supportWords": [
      "пријател",
      "цена",
      "пазар"
    ],
    "variants": [
      {
        "person": "1sg",
        "en": "I ask my friend about the price at the market.",
        "mk": "Го прашувам пријателот за цената на пазарот."
      },
      {
        "person": "2sg",
        "en": "You ask your friend about the price at the market.",
        "mk": "Го прашуваш пријателот за цената на пазарот."
      },
      {
        "person": "3sg",
        "en": "She asks her friend about the price at the market.",
        "mk": "Го прашува пријателот за цената на пазарот."
      },
      {
        "person": "1pl",
        "en": "We ask our friend about the price at the market.",
        "mk": "Го прашуваме пријателот за цената на пазарот."
      },
      {
        "person": "2pl",
        "en": "You ask your friend about the price at the market.",
        "mk": "Го прашувате пријателот за цената на пазарот."
      },
      {
        "person": "3pl",
        "en": "They ask their friend about the price at the market.",
        "mk": "Го прашуваат пријателот за цената на пазарот."
      }
    ],
    "tier": 3,
    "confidence": "unreviewed"
  },
  {
    "id": "sent-прашува-t4",
    "conceptIds": [
      "verb-conjugation",
      "definite-articles"
    ],
    "verbLemma": "прашува",
    "supportWords": [
      "доктор",
      "око",
      "болен"
    ],
    "variants": [
      {
        "person": "1sg",
        "en": "I ask the doctor about my eye because I am sick.",
        "mk": "Го прашувам докторот за окото бидејќи сум болен."
      },
      {
        "person": "2sg",
        "en": "You ask the doctor about your eye because you are sick.",
        "mk": "Го прашуваш докторот за окото бидејќи си болен."
      },
      {
        "person": "3sg",
        "en": "He asks the doctor about his eye because he is sick.",
        "mk": "Го прашува докторот за окото бидејќи е болен."
      },
      {
        "person": "1pl",
        "en": "We ask the doctor about our eyes because we are sick.",
        "mk": "Го прашуваме докторот за окото бидејќи сме болни."
      },
      {
        "person": "2pl",
        "en": "You ask the doctor about your eyes because you are sick.",
        "mk": "Го прашувате докторот за окото бидејќи сте болни."
      },
      {
        "person": "3pl",
        "en": "They ask the doctor about their eyes because they are sick.",
        "mk": "Го прашуваат докторот за окото бидејќи се болни."
      }
    ],
    "tier": 4,
    "confidence": "unreviewed"
  },
  {
    "id": "sent-работи",
    "conceptIds": [
      "verb-conjugation"
    ],
    "verbLemma": "работи",
    "supportWords": [
      "многу"
    ],
    "variants": [
      {
        "person": "1sg",
        "en": "I work a lot.",
        "mk": "Работам многу."
      },
      {
        "person": "2sg",
        "en": "You work a lot.",
        "mk": "Работиш многу."
      },
      {
        "person": "3sg",
        "en": "He/she works a lot.",
        "mk": "Работи многу."
      },
      {
        "person": "1pl",
        "en": "We work a lot.",
        "mk": "Работиме многу."
      },
      {
        "person": "2pl",
        "en": "You work a lot.",
        "mk": "Работите многу."
      },
      {
        "person": "3pl",
        "en": "They work a lot.",
        "mk": "Работат многу."
      }
    ],
    "confidence": "unreviewed"
  },
  {
    "id": "sent-работи-t2",
    "conceptIds": [
      "verb-conjugation"
    ],
    "verbLemma": "работи",
    "supportWords": [
      "многу",
      "денес"
    ],
    "variants": [
      {
        "person": "1sg",
        "en": "I work a lot today.",
        "mk": "Денес работам многу."
      },
      {
        "person": "2sg",
        "en": "You work a lot today.",
        "mk": "Денес работиш многу."
      },
      {
        "person": "3sg",
        "en": "He works a lot today.",
        "mk": "Денес работи многу."
      },
      {
        "person": "1pl",
        "en": "We work a lot today.",
        "mk": "Денес работиме многу."
      },
      {
        "person": "2pl",
        "en": "You work a lot today.",
        "mk": "Денес работите многу."
      },
      {
        "person": "3pl",
        "en": "They work a lot today.",
        "mk": "Денес работат многу."
      }
    ],
    "tier": 2,
    "confidence": "unreviewed"
  },
  {
    "id": "sent-работи-t3",
    "conceptIds": [
      "verb-conjugation",
      "definite-articles"
    ],
    "verbLemma": "работи",
    "supportWords": [
      "секогаш",
      "град",
      "нов"
    ],
    "variants": [
      {
        "person": "1sg",
        "en": "I always work in the new city.",
        "mk": "Секогаш работам во новиот град."
      },
      {
        "person": "2sg",
        "en": "You always work in the new city.",
        "mk": "Секогаш работиш во новиот град."
      },
      {
        "person": "3sg",
        "en": "She always works in the new city.",
        "mk": "Секогаш работи во новиот град."
      },
      {
        "person": "1pl",
        "en": "We always work in the new city.",
        "mk": "Секогаш работиме во новиот град."
      },
      {
        "person": "2pl",
        "en": "You always work in the new city.",
        "mk": "Секогаш работите во новиот град."
      },
      {
        "person": "3pl",
        "en": "They always work in the new city.",
        "mk": "Секогаш работат во новиот град."
      }
    ],
    "tier": 3,
    "confidence": "unreviewed"
  },
  {
    "id": "sent-работи-t4",
    "conceptIds": [
      "verb-conjugation"
    ],
    "verbLemma": "работи",
    "supportWords": [
      "многу",
      "бидејќи",
      "пари"
    ],
    "variants": [
      {
        "person": "1sg",
        "en": "I work a lot because I need money.",
        "mk": "Работам многу бидејќи ми требаат пари."
      },
      {
        "person": "2sg",
        "en": "You work a lot because you need money.",
        "mk": "Работиш многу бидејќи ти требаат пари."
      },
      {
        "person": "3sg",
        "en": "He works a lot because he needs money.",
        "mk": "Работи многу бидејќи му требаат пари."
      },
      {
        "person": "1pl",
        "en": "We work a lot because we need money.",
        "mk": "Работиме многу бидејќи ни требаат пари."
      },
      {
        "person": "2pl",
        "en": "You work a lot because you need money.",
        "mk": "Работите многу бидејќи ви требаат пари."
      },
      {
        "person": "3pl",
        "en": "They work a lot because they need money.",
        "mk": "Работат многу бидејќи им требаат пари."
      }
    ],
    "tier": 4,
    "confidence": "unreviewed"
  },
  {
    "id": "sent-сака",
    "conceptIds": [
      "verb-conjugation"
    ],
    "verbLemma": "сака",
    "supportWords": [
      "пиво"
    ],
    "variants": [
      {
        "person": "1sg",
        "en": "I want beer.",
        "mk": "Сакам пиво."
      },
      {
        "person": "2sg",
        "en": "You want beer.",
        "mk": "Сакаш пиво."
      },
      {
        "person": "3sg",
        "en": "He/she wants beer.",
        "mk": "Сака пиво."
      },
      {
        "person": "1pl",
        "en": "We want beer.",
        "mk": "Сакаме пиво."
      },
      {
        "person": "2pl",
        "en": "You want beer.",
        "mk": "Сакате пиво."
      },
      {
        "person": "3pl",
        "en": "They want beer.",
        "mk": "Сакаат пиво."
      }
    ],
    "confidence": "unreviewed"
  },
  {
    "id": "sent-сака-t2",
    "conceptIds": [
      "verb-conjugation"
    ],
    "verbLemma": "сака",
    "supportWords": [
      "студен",
      "пиво"
    ],
    "variants": [
      {
        "person": "1sg",
        "en": "I want a cold beer.",
        "mk": "Сакам студено пиво."
      },
      {
        "person": "2sg",
        "en": "You want a cold beer.",
        "mk": "Сакаш студено пиво."
      },
      {
        "person": "3sg",
        "en": "He/she wants a cold beer.",
        "mk": "Сака студено пиво."
      },
      {
        "person": "1pl",
        "en": "We want a cold beer.",
        "mk": "Сакаме студено пиво."
      },
      {
        "person": "2pl",
        "en": "You want a cold beer.",
        "mk": "Сакате студено пиво."
      },
      {
        "person": "3pl",
        "en": "They want a cold beer.",
        "mk": "Сакаат студено пиво."
      }
    ],
    "tier": 2,
    "confidence": "unreviewed"
  },
  {
    "id": "sent-сака-t3",
    "conceptIds": [
      "verb-conjugation"
    ],
    "verbLemma": "сака",
    "supportWords": [
      "топол",
      "кафе",
      "сега",
      "тука"
    ],
    "variants": [
      {
        "person": "1sg",
        "en": "Now I want a warm coffee here.",
        "mk": "Сега сакам топло кафе тука."
      },
      {
        "person": "2sg",
        "en": "Now you want a warm coffee here.",
        "mk": "Сега сакаш топло кафе тука."
      },
      {
        "person": "3sg",
        "en": "Now he/she wants a warm coffee here.",
        "mk": "Сега сака топло кафе тука."
      },
      {
        "person": "1pl",
        "en": "Now we want a warm coffee here.",
        "mk": "Сега сакаме топло кафе тука."
      },
      {
        "person": "2pl",
        "en": "Now you want a warm coffee here.",
        "mk": "Сега сакате топло кафе тука."
      },
      {
        "person": "3pl",
        "en": "Now they want a warm coffee here.",
        "mk": "Сега сакаат топло кафе тука."
      }
    ],
    "tier": 3,
    "confidence": "unreviewed"
  },
  {
    "id": "sent-сака-t4",
    "conceptIds": [
      "verb-conjugation",
      "definite-articles"
    ],
    "verbLemma": "сака",
    "supportWords": [
      "кафе",
      "топол",
      "бидејќи",
      "времето",
      "студен"
    ],
    "variants": [
      {
        "person": "1sg",
        "en": "I want to drink warm coffee because the weather is cold.",
        "mk": "Сакам да пијам топло кафе бидејќи времето е студено."
      },
      {
        "person": "2sg",
        "en": "You want to drink warm coffee because the weather is cold.",
        "mk": "Сакаш да пиеш топло кафе бидејќи времето е студено."
      },
      {
        "person": "3sg",
        "en": "He wants to drink warm coffee because the weather is cold.",
        "mk": "Сака да пие топло кафе бидејќи времето е студено."
      },
      {
        "person": "1pl",
        "en": "We want to drink warm coffee because the weather is cold.",
        "mk": "Сакаме да пиеме топло кафе бидејќи времето е студено."
      },
      {
        "person": "2pl",
        "en": "You want to drink warm coffee because the weather is cold.",
        "mk": "Сакате да пиете топло кафе бидејќи времето е студено."
      },
      {
        "person": "3pl",
        "en": "They want to drink warm coffee because the weather is cold.",
        "mk": "Сакаат да пијат топло кафе бидејќи времето е студено."
      }
    ],
    "tier": 4,
    "confidence": "unreviewed"
  },
  {
    "id": "sent-спие",
    "conceptIds": [
      "verb-conjugation"
    ],
    "verbLemma": "спие",
    "supportWords": [
      "многу"
    ],
    "variants": [
      {
        "person": "1sg",
        "en": "I sleep a lot.",
        "mk": "Спијам многу."
      },
      {
        "person": "2sg",
        "en": "You sleep a lot.",
        "mk": "Спиеш многу."
      },
      {
        "person": "3sg",
        "en": "He/she sleeps a lot.",
        "mk": "Спие многу."
      },
      {
        "person": "1pl",
        "en": "We sleep a lot.",
        "mk": "Спиеме многу."
      },
      {
        "person": "2pl",
        "en": "You sleep a lot.",
        "mk": "Спиете многу."
      },
      {
        "person": "3pl",
        "en": "They sleep a lot.",
        "mk": "Спијат многу."
      }
    ],
    "confidence": "unreviewed"
  },
  {
    "id": "sent-спие-t2",
    "conceptIds": [
      "verb-conjugation"
    ],
    "verbLemma": "спие",
    "supportWords": [
      "спијам",
      "многу",
      "добро"
    ],
    "variants": [
      {
        "person": "1sg",
        "en": "I sleep very well.",
        "mk": "Спијам многу добро."
      },
      {
        "person": "2sg",
        "en": "You sleep very well.",
        "mk": "Спиеш многу добро."
      },
      {
        "person": "3sg",
        "en": "He sleeps very well.",
        "mk": "Спие многу добро."
      },
      {
        "person": "1pl",
        "en": "We sleep very well.",
        "mk": "Спиеме многу добро."
      },
      {
        "person": "2pl",
        "en": "You sleep very well.",
        "mk": "Спиете многу добро."
      },
      {
        "person": "3pl",
        "en": "They sleep very well.",
        "mk": "Спијат многу добро."
      }
    ],
    "tier": 2,
    "confidence": "unreviewed"
  },
  {
    "id": "sent-спие-t3",
    "conceptIds": [
      "verb-conjugation",
      "definite-articles"
    ],
    "verbLemma": "спие",
    "supportWords": [
      "спијам",
      "само",
      "час",
      "во",
      "куќа"
    ],
    "variants": [
      {
        "person": "1sg",
        "en": "I sleep only four hours in the house.",
        "mk": "Спијам само четири часа во куќата."
      },
      {
        "person": "2sg",
        "en": "You sleep only four hours in the house.",
        "mk": "Спиеш само четири часа во куќата."
      },
      {
        "person": "3sg",
        "en": "She sleeps only four hours in the house.",
        "mk": "Спие само четири часа во куќата."
      },
      {
        "person": "1pl",
        "en": "We sleep only four hours in the house.",
        "mk": "Спиеме само четири часа во куќата."
      },
      {
        "person": "2pl",
        "en": "You sleep only four hours in the house.",
        "mk": "Спиете само четири часа во куќата."
      },
      {
        "person": "3pl",
        "en": "They sleep only four hours in the house.",
        "mk": "Спијат само четири часа во куќата."
      }
    ],
    "tier": 3,
    "confidence": "unreviewed"
  },
  {
    "id": "sent-спие-t4",
    "conceptIds": [
      "verb-conjugation"
    ],
    "verbLemma": "спие",
    "supportWords": [
      "спијам",
      "лошо",
      "ноќ",
      "бидејќи",
      "работам",
      "многу"
    ],
    "variants": [
      {
        "person": "1sg",
        "en": "I sleep badly at night because I work a lot.",
        "mk": "Спијам лошо во ноќта бидејќи работам многу."
      },
      {
        "person": "2sg",
        "en": "You sleep badly at night because you work a lot.",
        "mk": "Спиеш лошо во ноќта бидејќи работаш многу."
      },
      {
        "person": "3sg",
        "en": "He sleeps badly at night because he works a lot.",
        "mk": "Спие лошо во ноќта бидејќи работи многу."
      },
      {
        "person": "1pl",
        "en": "We sleep badly at night because we work a lot.",
        "mk": "Спиеме лошо во ноќта бидејќи работиме многу."
      },
      {
        "person": "2pl",
        "en": "You sleep badly at night because you work a lot.",
        "mk": "Спиете лошо во ноќта бидејќи работите многу."
      },
      {
        "person": "3pl",
        "en": "They sleep badly at night because they work a lot.",
        "mk": "Спијат лошо во ноќта бидејќи работат многу."
      }
    ],
    "tier": 4,
    "confidence": "unreviewed"
  },
  {
    "id": "sent-треба",
    "conceptIds": [
      "verb-conjugation"
    ],
    "verbLemma": "треба",
    "supportWords": [
      "вода"
    ],
    "variants": [
      {
        "person": "1sg",
        "en": "I need water.",
        "mk": "Ми треба вода."
      },
      {
        "person": "2sg",
        "en": "You need water.",
        "mk": "Ти треба вода."
      },
      {
        "person": "3sg",
        "en": "He/She needs water.",
        "mk": "Му треба вода."
      },
      {
        "person": "1pl",
        "en": "We need water.",
        "mk": "Ни треба вода."
      },
      {
        "person": "2pl",
        "en": "You need water.",
        "mk": "Ви треба вода."
      },
      {
        "person": "3pl",
        "en": "They need water.",
        "mk": "Им треба вода."
      }
    ],
    "confidence": "unreviewed"
  },
  {
    "id": "sent-треба-t2",
    "conceptIds": [
      "verb-conjugation"
    ],
    "verbLemma": "треба",
    "supportWords": [
      "нов",
      "клуч"
    ],
    "variants": [
      {
        "person": "1sg",
        "en": "I need a new key.",
        "mk": "Ми треба нов клуч."
      },
      {
        "person": "2sg",
        "en": "You need a new key.",
        "mk": "Ти треба нов клуч."
      },
      {
        "person": "3sg",
        "en": "He needs a new key.",
        "mk": "Му треба нов клуч."
      },
      {
        "person": "1pl",
        "en": "We need a new key.",
        "mk": "Ни треба нов клуч."
      },
      {
        "person": "2pl",
        "en": "You need a new key.",
        "mk": "Ви треба нов клуч."
      },
      {
        "person": "3pl",
        "en": "They need a new key.",
        "mk": "Им треба нов клуч."
      }
    ],
    "tier": 2,
    "confidence": "unreviewed"
  },
  {
    "id": "sent-треба-t3",
    "conceptIds": [
      "verb-conjugation",
      "definite-articles"
    ],
    "verbLemma": "треба",
    "supportWords": [
      "пари",
      "за",
      "билет",
      "сега"
    ],
    "variants": [
      {
        "person": "1sg",
        "en": "I need money for the ticket now.",
        "mk": "Ми требаат пари за билетот сега."
      },
      {
        "person": "2sg",
        "en": "You need money for the ticket now.",
        "mk": "Ти требаат пари за билетот сега."
      },
      {
        "person": "3sg",
        "en": "He/she needs money for the ticket now.",
        "mk": "Му требаат пари за билетот сега."
      },
      {
        "person": "1pl",
        "en": "We need money for the ticket now.",
        "mk": "Ни требаат пари за билетот сега."
      },
      {
        "person": "2pl",
        "en": "You need money for the ticket now.",
        "mk": "Ви требаат пари за билетот сега."
      },
      {
        "person": "3pl",
        "en": "They need money for the ticket now.",
        "mk": "Им требаат пари за билетот сега."
      }
    ],
    "tier": 3,
    "confidence": "unreviewed"
  },
  {
    "id": "sent-треба-t4",
    "conceptIds": [
      "verb-conjugation"
    ],
    "verbLemma": "треба",
    "supportWords": [
      "вода",
      "бидејќи",
      "болен",
      "многу"
    ],
    "variants": [
      {
        "person": "1sg",
        "en": "I need water now because I am very sick.",
        "mk": "Ми треба вода сега бидејќи сум многу болен."
      },
      {
        "person": "2sg",
        "en": "You need water now because you are very sick.",
        "mk": "Ти треба вода сега бидејќи си многу болен."
      },
      {
        "person": "3sg",
        "en": "He needs water now because he is very sick.",
        "mk": "Му треба вода сега бидејќи е многу болен."
      },
      {
        "person": "1pl",
        "en": "We need water now because we are very sick.",
        "mk": "Ни треба вода сега бидејќи сме многу болни."
      },
      {
        "person": "2pl",
        "en": "You need water now because you are very sick.",
        "mk": "Ви треба вода сега бидејќи сте многу болни."
      },
      {
        "person": "3pl",
        "en": "They need water now because they are very sick.",
        "mk": "Им треба вода сега бидејќи се многу болни."
      }
    ],
    "tier": 4,
    "confidence": "unreviewed"
  }
];
