// MACHINE-GENERATED by pipeline/src/run-words.ts (Opus 4.8). Themed high-frequency single Macedonian
// words that expand the flashcard vocabulary, deduped against the rest of the pack. Merged into `vocab`
// in index.ts. Spot-check before trusting as authoritative. Additive — grow by extending SEED and
// re-running: pipeline/node_modules/.bin/tsx pipeline/src/run-words.ts
import type { ReviewItem } from "@ll/pack-schema";

export const coreWords: ReviewItem[] = [
  {
    "id": "word-bolen",
    "kind": "vocab",
    "prompt": "sick",
    "answer": "болен",
    "translit": "bolen",
    "gloss": "sick",
    "i1Level": 1,
    "tags": [
      "body & health"
    ],
    "confidence": "validated"
  },
  {
    "id": "word-glava",
    "kind": "vocab",
    "prompt": "head",
    "answer": "глава",
    "translit": "glava",
    "gloss": "head",
    "i1Level": 1,
    "tags": [
      "body & health"
    ],
    "meta": {
      "gender": "feminine"
    },
    "confidence": "validated"
  },
  {
    "id": "word-doktor",
    "kind": "vocab",
    "prompt": "doctor",
    "answer": "доктор",
    "translit": "doktor",
    "gloss": "doctor",
    "i1Level": 1,
    "tags": [
      "body & health"
    ],
    "meta": {
      "gender": "masculine"
    },
    "confidence": "validated"
  },
  {
    "id": "word-noga",
    "kind": "vocab",
    "prompt": "leg, foot",
    "answer": "нога",
    "translit": "noga",
    "gloss": "leg, foot",
    "i1Level": 1,
    "tags": [
      "body & health"
    ],
    "meta": {
      "gender": "feminine"
    },
    "confidence": "validated"
  },
  {
    "id": "word-oko",
    "kind": "vocab",
    "prompt": "eye",
    "answer": "око",
    "translit": "oko",
    "gloss": "eye",
    "i1Level": 1,
    "tags": [
      "body & health"
    ],
    "meta": {
      "gender": "neuter"
    },
    "confidence": "validated"
  },
  {
    "id": "word-raka",
    "kind": "vocab",
    "prompt": "hand, arm",
    "answer": "рака",
    "translit": "raka",
    "gloss": "hand, arm",
    "i1Level": 1,
    "tags": [
      "body & health"
    ],
    "meta": {
      "gender": "feminine"
    },
    "confidence": "validated"
  },
  {
    "id": "word-dobar",
    "kind": "vocab",
    "prompt": "good",
    "answer": "добар",
    "translit": "dobar",
    "gloss": "good",
    "i1Level": 1,
    "tags": [
      "common adjectives"
    ],
    "confidence": "validated"
  },
  {
    "id": "word-golem",
    "kind": "vocab",
    "prompt": "big",
    "answer": "голем",
    "translit": "golem",
    "gloss": "big",
    "i1Level": 1,
    "tags": [
      "common adjectives"
    ],
    "confidence": "validated"
  },
  {
    "id": "word-losh",
    "kind": "vocab",
    "prompt": "bad",
    "answer": "лош",
    "translit": "losh",
    "gloss": "bad",
    "i1Level": 1,
    "tags": [
      "common adjectives"
    ],
    "confidence": "validated"
  },
  {
    "id": "word-mal",
    "kind": "vocab",
    "prompt": "small",
    "answer": "мал",
    "translit": "mal",
    "gloss": "small",
    "i1Level": 1,
    "tags": [
      "common adjectives"
    ],
    "confidence": "validated"
  },
  {
    "id": "word-nov",
    "kind": "vocab",
    "prompt": "new",
    "answer": "нов",
    "translit": "nov",
    "gloss": "new",
    "i1Level": 1,
    "tags": [
      "common adjectives"
    ],
    "confidence": "validated"
  },
  {
    "id": "word-star",
    "kind": "vocab",
    "prompt": "old",
    "answer": "стар",
    "translit": "star",
    "gloss": "old",
    "i1Level": 1,
    "tags": [
      "common adjectives"
    ],
    "confidence": "validated"
  },
  {
    "id": "word-studen",
    "kind": "vocab",
    "prompt": "cold",
    "answer": "студен",
    "translit": "studen",
    "gloss": "cold",
    "i1Level": 1,
    "tags": [
      "common adjectives"
    ],
    "confidence": "validated"
  },
  {
    "id": "word-topol",
    "kind": "vocab",
    "prompt": "warm",
    "answer": "топол",
    "translit": "topol",
    "gloss": "warm",
    "i1Level": 1,
    "tags": [
      "common adjectives"
    ],
    "confidence": "validated"
  },
  {
    "id": "word-brzo",
    "kind": "vocab",
    "prompt": "quickly, fast",
    "answer": "брзо",
    "translit": "brzo",
    "gloss": "quickly, fast",
    "note": "adverb",
    "i1Level": 1,
    "tags": [
      "common adverbs"
    ],
    "confidence": "validated"
  },
  {
    "id": "word-dobro",
    "kind": "vocab",
    "prompt": "good, well",
    "answer": "добро",
    "translit": "dobro",
    "gloss": "good, well",
    "note": "adverb/adjective (neuter form); common as 'well/okay'",
    "i1Level": 1,
    "tags": [
      "common adverbs"
    ],
    "confidence": "validated"
  },
  {
    "id": "word-isto",
    "kind": "vocab",
    "prompt": "same, also",
    "answer": "исто",
    "translit": "isto",
    "gloss": "same, also",
    "note": "often 'исто така' = likewise",
    "i1Level": 1,
    "tags": [
      "common adverbs"
    ],
    "confidence": "validated"
  },
  {
    "id": "word-losho",
    "kind": "vocab",
    "prompt": "bad, badly",
    "answer": "лошо",
    "translit": "losho",
    "gloss": "bad, badly",
    "note": "adverb/adjective (neuter form)",
    "i1Level": 1,
    "tags": [
      "common adverbs"
    ],
    "confidence": "validated"
  },
  {
    "id": "word-malku",
    "kind": "vocab",
    "prompt": "little, few",
    "answer": "малку",
    "translit": "malku",
    "gloss": "little, few",
    "note": "quantity adverb",
    "i1Level": 1,
    "tags": [
      "common adverbs"
    ],
    "confidence": "validated"
  },
  {
    "id": "word-mnogu",
    "kind": "vocab",
    "prompt": "much, many, very",
    "answer": "многу",
    "translit": "mnogu",
    "gloss": "much, many, very",
    "note": "quantity/degree adverb",
    "i1Level": 1,
    "tags": [
      "common adverbs"
    ],
    "confidence": "validated"
  },
  {
    "id": "word-mozhebi",
    "kind": "vocab",
    "prompt": "maybe, perhaps",
    "answer": "можеби",
    "translit": "mozhebi",
    "gloss": "maybe, perhaps",
    "note": "modal adverb",
    "i1Level": 1,
    "tags": [
      "common adverbs"
    ],
    "confidence": "validated"
  },
  {
    "id": "word-nikogash",
    "kind": "vocab",
    "prompt": "never",
    "answer": "никогаш",
    "translit": "nikogash",
    "gloss": "never",
    "note": "needs negation, e.g. 'никогаш не'",
    "i1Level": 1,
    "tags": [
      "common adverbs"
    ],
    "confidence": "validated"
  },
  {
    "id": "word-poleka",
    "kind": "vocab",
    "prompt": "slowly",
    "answer": "полека",
    "translit": "poleka",
    "gloss": "slowly",
    "note": "adverb",
    "i1Level": 1,
    "tags": [
      "common adverbs"
    ],
    "confidence": "validated"
  },
  {
    "id": "word-povekje",
    "kind": "vocab",
    "prompt": "more",
    "answer": "повеќе",
    "translit": "povekje",
    "gloss": "more",
    "note": "comparative of многу",
    "i1Level": 1,
    "tags": [
      "common adverbs"
    ],
    "confidence": "validated"
  },
  {
    "id": "word-samo",
    "kind": "vocab",
    "prompt": "only, just",
    "answer": "само",
    "translit": "samo",
    "gloss": "only, just",
    "note": "particle/adverb",
    "i1Level": 1,
    "tags": [
      "common adverbs"
    ],
    "confidence": "validated"
  },
  {
    "id": "word-sega",
    "kind": "vocab",
    "prompt": "now",
    "answer": "сега",
    "translit": "sega",
    "gloss": "now",
    "note": "adverb of time",
    "i1Level": 1,
    "tags": [
      "common adverbs"
    ],
    "confidence": "validated"
  },
  {
    "id": "word-sekogash",
    "kind": "vocab",
    "prompt": "always",
    "answer": "секогаш",
    "translit": "sekogash",
    "gloss": "always",
    "note": "adverb of frequency",
    "i1Level": 1,
    "tags": [
      "common adverbs"
    ],
    "confidence": "validated"
  },
  {
    "id": "word-tamu",
    "kind": "vocab",
    "prompt": "there",
    "answer": "таму",
    "translit": "tamu",
    "gloss": "there",
    "note": "adverb of place",
    "i1Level": 1,
    "tags": [
      "common adverbs"
    ],
    "confidence": "validated"
  },
  {
    "id": "word-tuka",
    "kind": "vocab",
    "prompt": "here",
    "answer": "тука",
    "translit": "tuka",
    "gloss": "here",
    "note": "adverb of place",
    "i1Level": 1,
    "tags": [
      "common adverbs"
    ],
    "confidence": "validated"
  },
  {
    "id": "word-vekje",
    "kind": "vocab",
    "prompt": "already",
    "answer": "веќе",
    "translit": "vekje",
    "gloss": "already",
    "note": "adverb",
    "i1Level": 1,
    "tags": [
      "common adverbs"
    ],
    "confidence": "validated"
  },
  {
    "id": "word-doagjam",
    "kind": "vocab",
    "prompt": "come",
    "answer": "доаѓам",
    "translit": "doagjam",
    "gloss": "come",
    "i1Level": 1,
    "tags": [
      "common verbs"
    ],
    "confidence": "validated"
  },
  {
    "id": "word-imam",
    "kind": "vocab",
    "prompt": "have",
    "answer": "имам",
    "translit": "imam",
    "gloss": "have",
    "i1Level": 1,
    "tags": [
      "common verbs"
    ],
    "confidence": "validated"
  },
  {
    "id": "word-odam",
    "kind": "vocab",
    "prompt": "go, walk",
    "answer": "одам",
    "translit": "odam",
    "gloss": "go, walk",
    "note": "1st person present",
    "i1Level": 1,
    "tags": [
      "common verbs"
    ],
    "confidence": "validated"
  },
  {
    "id": "word-pijam",
    "kind": "vocab",
    "prompt": "drink",
    "answer": "пијам",
    "translit": "piyam",
    "gloss": "drink",
    "i1Level": 1,
    "tags": [
      "common verbs"
    ],
    "confidence": "validated"
  },
  {
    "id": "word-rabotam",
    "kind": "vocab",
    "prompt": "work",
    "answer": "работам",
    "translit": "rabotam",
    "gloss": "work",
    "i1Level": 1,
    "tags": [
      "common verbs"
    ],
    "confidence": "validated"
  },
  {
    "id": "word-spijam",
    "kind": "vocab",
    "prompt": "sleep",
    "answer": "спијам",
    "translit": "spiyam",
    "gloss": "sleep",
    "i1Level": 1,
    "tags": [
      "common verbs"
    ],
    "confidence": "validated"
  },
  {
    "id": "word-vidam",
    "kind": "vocab",
    "prompt": "see",
    "answer": "видам",
    "translit": "vidam",
    "gloss": "see",
    "i1Level": 1,
    "tags": [
      "common verbs"
    ],
    "confidence": "validated"
  },
  {
    "id": "word-zboruvam",
    "kind": "vocab",
    "prompt": "speak",
    "answer": "зборувам",
    "translit": "zboruvam",
    "gloss": "speak",
    "i1Level": 1,
    "tags": [
      "common verbs"
    ],
    "confidence": "validated"
  },
  {
    "id": "word-znam",
    "kind": "vocab",
    "prompt": "know",
    "answer": "знам",
    "translit": "znam",
    "gloss": "know",
    "i1Level": 1,
    "tags": [
      "common verbs"
    ],
    "confidence": "validated"
  },
  {
    "id": "word-ako",
    "kind": "vocab",
    "prompt": "if",
    "answer": "ако",
    "translit": "ako",
    "gloss": "if",
    "note": "conditional conjunction",
    "i1Level": 1,
    "tags": [
      "conjunctions"
    ],
    "confidence": "validated"
  },
  {
    "id": "word-ama",
    "kind": "vocab",
    "prompt": "but",
    "answer": "ама",
    "translit": "ama",
    "gloss": "but",
    "note": "colloquial conjunction, like 'но'",
    "i1Level": 1,
    "tags": [
      "conjunctions"
    ],
    "confidence": "validated"
  },
  {
    "id": "word-bidejkji",
    "kind": "vocab",
    "prompt": "because",
    "answer": "бидејќи",
    "translit": "bideykji",
    "gloss": "because",
    "note": "causal conjunction",
    "i1Level": 1,
    "tags": [
      "conjunctions"
    ],
    "confidence": "validated"
  },
  {
    "id": "word-deka",
    "kind": "vocab",
    "prompt": "that",
    "answer": "дека",
    "translit": "deka",
    "gloss": "that",
    "note": "conjunction introducing clause",
    "i1Level": 1,
    "tags": [
      "conjunctions"
    ],
    "confidence": "validated"
  },
  {
    "id": "word-dodeka",
    "kind": "vocab",
    "prompt": "while, until",
    "answer": "додека",
    "translit": "dodeka",
    "gloss": "while, until",
    "note": "temporal conjunction",
    "i1Level": 1,
    "tags": [
      "conjunctions"
    ],
    "confidence": "validated"
  },
  {
    "id": "word-i",
    "kind": "vocab",
    "prompt": "and",
    "answer": "и",
    "translit": "i",
    "gloss": "and",
    "note": "coordinating conjunction; also 'also/too'",
    "i1Level": 1,
    "tags": [
      "conjunctions"
    ],
    "confidence": "validated"
  },
  {
    "id": "word-ili",
    "kind": "vocab",
    "prompt": "or",
    "answer": "или",
    "translit": "ili",
    "gloss": "or",
    "note": "coordinating conjunction",
    "i1Level": 1,
    "tags": [
      "conjunctions"
    ],
    "confidence": "validated"
  },
  {
    "id": "word-no",
    "kind": "vocab",
    "prompt": "but",
    "answer": "но",
    "translit": "no",
    "gloss": "but",
    "note": "contrastive conjunction",
    "i1Level": 1,
    "tags": [
      "conjunctions"
    ],
    "confidence": "validated"
  },
  {
    "id": "word-zatoa",
    "kind": "vocab",
    "prompt": "therefore, that's why",
    "answer": "затоа",
    "translit": "zatoa",
    "gloss": "therefore, that's why",
    "note": "often 'затоа што' = because",
    "i1Level": 1,
    "tags": [
      "conjunctions"
    ],
    "confidence": "validated"
  },
  {
    "id": "word-baba",
    "kind": "vocab",
    "prompt": "grandmother",
    "answer": "баба",
    "translit": "baba",
    "gloss": "grandmother",
    "i1Level": 1,
    "tags": [
      "family & people"
    ],
    "meta": {
      "gender": "feminine"
    },
    "confidence": "validated"
  },
  {
    "id": "word-chovek",
    "kind": "vocab",
    "prompt": "person, man",
    "answer": "човек",
    "translit": "chovek",
    "gloss": "person, man",
    "i1Level": 1,
    "tags": [
      "family & people"
    ],
    "meta": {
      "gender": "masculine"
    },
    "confidence": "validated"
  },
  {
    "id": "word-dedo",
    "kind": "vocab",
    "prompt": "grandfather",
    "answer": "дедо",
    "translit": "dedo",
    "gloss": "grandfather",
    "i1Level": 1,
    "tags": [
      "family & people"
    ],
    "meta": {
      "gender": "masculine"
    },
    "confidence": "validated"
  },
  {
    "id": "word-devojka",
    "kind": "vocab",
    "prompt": "girl",
    "answer": "девојка",
    "translit": "devoyka",
    "gloss": "girl",
    "i1Level": 1,
    "tags": [
      "family & people"
    ],
    "meta": {
      "gender": "feminine"
    },
    "confidence": "validated"
  },
  {
    "id": "word-momche",
    "kind": "vocab",
    "prompt": "boy",
    "answer": "момче",
    "translit": "momche",
    "gloss": "boy",
    "i1Level": 1,
    "tags": [
      "family & people"
    ],
    "meta": {
      "gender": "neuter"
    },
    "confidence": "validated"
  },
  {
    "id": "word-prijatel",
    "kind": "vocab",
    "prompt": "friend",
    "answer": "пријател",
    "translit": "priyatel",
    "gloss": "friend",
    "i1Level": 1,
    "tags": [
      "family & people"
    ],
    "meta": {
      "gender": "masculine"
    },
    "confidence": "validated"
  },
  {
    "id": "word-jajce",
    "kind": "vocab",
    "prompt": "egg",
    "answer": "јајце",
    "translit": "yayce",
    "gloss": "egg",
    "i1Level": 1,
    "tags": [
      "food & drink"
    ],
    "meta": {
      "gender": "neuter"
    },
    "confidence": "validated"
  },
  {
    "id": "word-meso",
    "kind": "vocab",
    "prompt": "meat",
    "answer": "месо",
    "translit": "meso",
    "gloss": "meat",
    "i1Level": 1,
    "tags": [
      "food & drink"
    ],
    "meta": {
      "gender": "neuter"
    },
    "confidence": "validated"
  },
  {
    "id": "word-ovoshje",
    "kind": "vocab",
    "prompt": "fruit",
    "answer": "овошје",
    "translit": "ovoshye",
    "gloss": "fruit",
    "i1Level": 1,
    "tags": [
      "food & drink"
    ],
    "meta": {
      "gender": "neuter"
    },
    "confidence": "validated"
  },
  {
    "id": "word-riba",
    "kind": "vocab",
    "prompt": "fish",
    "answer": "риба",
    "translit": "riba",
    "gloss": "fish",
    "i1Level": 1,
    "tags": [
      "food & drink"
    ],
    "meta": {
      "gender": "feminine"
    },
    "confidence": "validated"
  },
  {
    "id": "word-shekjer",
    "kind": "vocab",
    "prompt": "sugar",
    "answer": "шеќер",
    "translit": "shekjer",
    "gloss": "sugar",
    "i1Level": 1,
    "tags": [
      "food & drink"
    ],
    "meta": {
      "gender": "masculine"
    },
    "confidence": "validated"
  },
  {
    "id": "word-sol",
    "kind": "vocab",
    "prompt": "salt",
    "answer": "сол",
    "translit": "sol",
    "gloss": "salt",
    "i1Level": 1,
    "tags": [
      "food & drink"
    ],
    "meta": {
      "gender": "feminine"
    },
    "confidence": "validated"
  },
  {
    "id": "word-zelenchuk",
    "kind": "vocab",
    "prompt": "vegetables",
    "answer": "зеленчук",
    "translit": "zelenchuk",
    "gloss": "vegetables",
    "i1Level": 1,
    "tags": [
      "food & drink"
    ],
    "meta": {
      "gender": "masculine"
    },
    "confidence": "validated"
  },
  {
    "id": "word-kluch",
    "kind": "vocab",
    "prompt": "key",
    "answer": "клуч",
    "translit": "kluch",
    "gloss": "key",
    "i1Level": 1,
    "tags": [
      "home & everyday objects"
    ],
    "meta": {
      "gender": "masculine"
    },
    "confidence": "validated"
  },
  {
    "id": "word-kukja",
    "kind": "vocab",
    "prompt": "house",
    "answer": "куќа",
    "translit": "kukja",
    "gloss": "house",
    "i1Level": 1,
    "tags": [
      "home & everyday objects"
    ],
    "meta": {
      "gender": "feminine"
    },
    "confidence": "validated"
  },
  {
    "id": "word-masa",
    "kind": "vocab",
    "prompt": "table",
    "answer": "маса",
    "translit": "masa",
    "gloss": "table",
    "i1Level": 1,
    "tags": [
      "home & everyday objects"
    ],
    "meta": {
      "gender": "feminine"
    },
    "confidence": "validated"
  },
  {
    "id": "word-prozorec",
    "kind": "vocab",
    "prompt": "window",
    "answer": "прозорец",
    "translit": "prozorec",
    "gloss": "window",
    "i1Level": 1,
    "tags": [
      "home & everyday objects"
    ],
    "meta": {
      "gender": "masculine"
    },
    "confidence": "validated"
  },
  {
    "id": "word-stan",
    "kind": "vocab",
    "prompt": "apartment",
    "answer": "стан",
    "translit": "stan",
    "gloss": "apartment",
    "i1Level": 1,
    "tags": [
      "home & everyday objects"
    ],
    "meta": {
      "gender": "masculine"
    },
    "confidence": "validated"
  },
  {
    "id": "word-stol",
    "kind": "vocab",
    "prompt": "chair",
    "answer": "стол",
    "translit": "stol",
    "gloss": "chair",
    "i1Level": 1,
    "tags": [
      "home & everyday objects"
    ],
    "meta": {
      "gender": "masculine"
    },
    "confidence": "validated"
  },
  {
    "id": "word-telefon",
    "kind": "vocab",
    "prompt": "phone",
    "answer": "телефон",
    "translit": "telefon",
    "gloss": "phone",
    "i1Level": 1,
    "tags": [
      "home & everyday objects"
    ],
    "meta": {
      "gender": "masculine"
    },
    "confidence": "validated"
  },
  {
    "id": "word-vrata",
    "kind": "vocab",
    "prompt": "door",
    "answer": "врата",
    "translit": "vrata",
    "gloss": "door",
    "i1Level": 1,
    "tags": [
      "home & everyday objects"
    ],
    "meta": {
      "gender": "feminine"
    },
    "confidence": "validated"
  },
  {
    "id": "word-cena",
    "kind": "vocab",
    "prompt": "price",
    "answer": "цена",
    "translit": "cena",
    "gloss": "price",
    "i1Level": 1,
    "tags": [
      "money & shopping"
    ],
    "meta": {
      "gender": "feminine"
    },
    "confidence": "validated"
  },
  {
    "id": "word-evtin",
    "kind": "vocab",
    "prompt": "cheap",
    "answer": "евтин",
    "translit": "evtin",
    "gloss": "cheap",
    "i1Level": 1,
    "tags": [
      "money & shopping"
    ],
    "confidence": "validated"
  },
  {
    "id": "word-pari",
    "kind": "vocab",
    "prompt": "money",
    "answer": "пари",
    "translit": "pari",
    "gloss": "money",
    "note": "plural only",
    "i1Level": 1,
    "tags": [
      "money & shopping"
    ],
    "meta": {
      "gender": "feminine"
    },
    "confidence": "validated"
  },
  {
    "id": "word-pazar",
    "kind": "vocab",
    "prompt": "market",
    "answer": "пазар",
    "translit": "pazar",
    "gloss": "market",
    "i1Level": 1,
    "tags": [
      "money & shopping"
    ],
    "meta": {
      "gender": "masculine"
    },
    "confidence": "validated"
  },
  {
    "id": "word-prodavnica",
    "kind": "vocab",
    "prompt": "shop",
    "answer": "продавница",
    "translit": "prodavnica",
    "gloss": "shop",
    "i1Level": 1,
    "tags": [
      "money & shopping"
    ],
    "meta": {
      "gender": "feminine"
    },
    "confidence": "validated"
  },
  {
    "id": "word-skap",
    "kind": "vocab",
    "prompt": "expensive",
    "answer": "скап",
    "translit": "skap",
    "gloss": "expensive",
    "i1Level": 1,
    "tags": [
      "money & shopping"
    ],
    "confidence": "validated"
  },
  {
    "id": "word-dozhd",
    "kind": "vocab",
    "prompt": "rain",
    "answer": "дожд",
    "translit": "dozhd",
    "gloss": "rain",
    "i1Level": 1,
    "tags": [
      "nature & weather"
    ],
    "meta": {
      "gender": "masculine"
    },
    "confidence": "validated"
  },
  {
    "id": "word-drvo",
    "kind": "vocab",
    "prompt": "tree",
    "answer": "дрво",
    "translit": "drvo",
    "gloss": "tree",
    "i1Level": 1,
    "tags": [
      "nature & weather"
    ],
    "meta": {
      "gender": "neuter"
    },
    "confidence": "validated"
  },
  {
    "id": "word-planina",
    "kind": "vocab",
    "prompt": "mountain",
    "answer": "планина",
    "translit": "planina",
    "gloss": "mountain",
    "i1Level": 1,
    "tags": [
      "nature & weather"
    ],
    "meta": {
      "gender": "feminine"
    },
    "confidence": "validated"
  },
  {
    "id": "word-sneg",
    "kind": "vocab",
    "prompt": "snow",
    "answer": "снег",
    "translit": "sneg",
    "gloss": "snow",
    "i1Level": 1,
    "tags": [
      "nature & weather"
    ],
    "meta": {
      "gender": "masculine"
    },
    "confidence": "validated"
  },
  {
    "id": "word-sonce",
    "kind": "vocab",
    "prompt": "sun",
    "answer": "сонце",
    "translit": "sonce",
    "gloss": "sun",
    "i1Level": 1,
    "tags": [
      "nature & weather"
    ],
    "meta": {
      "gender": "neuter"
    },
    "confidence": "validated"
  },
  {
    "id": "word-veter",
    "kind": "vocab",
    "prompt": "wind",
    "answer": "ветер",
    "translit": "veter",
    "gloss": "wind",
    "i1Level": 1,
    "tags": [
      "nature & weather"
    ],
    "meta": {
      "gender": "masculine"
    },
    "confidence": "validated"
  },
  {
    "id": "word-chetiri",
    "kind": "vocab",
    "prompt": "four",
    "answer": "четири",
    "translit": "chetiri",
    "gloss": "four",
    "note": "number",
    "i1Level": 1,
    "tags": [
      "numbers"
    ],
    "confidence": "validated"
  },
  {
    "id": "word-deset",
    "kind": "vocab",
    "prompt": "ten",
    "answer": "десет",
    "translit": "deset",
    "gloss": "ten",
    "note": "number",
    "i1Level": 1,
    "tags": [
      "numbers"
    ],
    "confidence": "validated"
  },
  {
    "id": "word-devet",
    "kind": "vocab",
    "prompt": "nine",
    "answer": "девет",
    "translit": "devet",
    "gloss": "nine",
    "note": "number",
    "i1Level": 1,
    "tags": [
      "numbers"
    ],
    "confidence": "validated"
  },
  {
    "id": "word-dva",
    "kind": "vocab",
    "prompt": "two",
    "answer": "два",
    "translit": "dva",
    "gloss": "two",
    "note": "number; masculine (dve f./n.)",
    "i1Level": 1,
    "tags": [
      "numbers"
    ],
    "confidence": "validated"
  },
  {
    "id": "word-eden",
    "kind": "vocab",
    "prompt": "one",
    "answer": "еден",
    "translit": "eden",
    "gloss": "one",
    "note": "number; masculine form (edna f., edno n.)",
    "i1Level": 1,
    "tags": [
      "numbers"
    ],
    "confidence": "validated"
  },
  {
    "id": "word-iljada",
    "kind": "vocab",
    "prompt": "thousand",
    "answer": "илјада",
    "translit": "ilyada",
    "gloss": "thousand",
    "note": "number/noun",
    "i1Level": 1,
    "tags": [
      "numbers"
    ],
    "meta": {
      "gender": "feminine"
    },
    "confidence": "validated"
  },
  {
    "id": "word-nula",
    "kind": "vocab",
    "prompt": "zero",
    "answer": "нула",
    "translit": "nula",
    "gloss": "zero",
    "note": "number",
    "i1Level": 1,
    "tags": [
      "numbers"
    ],
    "confidence": "validated"
  },
  {
    "id": "word-osum",
    "kind": "vocab",
    "prompt": "eight",
    "answer": "осум",
    "translit": "osum",
    "gloss": "eight",
    "note": "number",
    "i1Level": 1,
    "tags": [
      "numbers"
    ],
    "confidence": "validated"
  },
  {
    "id": "word-pet",
    "kind": "vocab",
    "prompt": "five",
    "answer": "пет",
    "translit": "pet",
    "gloss": "five",
    "note": "number",
    "i1Level": 1,
    "tags": [
      "numbers"
    ],
    "confidence": "validated"
  },
  {
    "id": "word-sedum",
    "kind": "vocab",
    "prompt": "seven",
    "answer": "седум",
    "translit": "sedum",
    "gloss": "seven",
    "note": "number",
    "i1Level": 1,
    "tags": [
      "numbers"
    ],
    "confidence": "validated"
  },
  {
    "id": "word-shest",
    "kind": "vocab",
    "prompt": "six",
    "answer": "шест",
    "translit": "shest",
    "gloss": "six",
    "note": "number",
    "i1Level": 1,
    "tags": [
      "numbers"
    ],
    "confidence": "validated"
  },
  {
    "id": "word-sto",
    "kind": "vocab",
    "prompt": "hundred",
    "answer": "сто",
    "translit": "sto",
    "gloss": "hundred",
    "note": "number",
    "i1Level": 1,
    "tags": [
      "numbers"
    ],
    "confidence": "validated"
  },
  {
    "id": "word-tri",
    "kind": "vocab",
    "prompt": "three",
    "answer": "три",
    "translit": "tri",
    "gloss": "three",
    "note": "number",
    "i1Level": 1,
    "tags": [
      "numbers"
    ],
    "confidence": "validated"
  },
  {
    "id": "word-aerodrom",
    "kind": "vocab",
    "prompt": "airport",
    "answer": "аеродром",
    "translit": "aerodrom",
    "gloss": "airport",
    "i1Level": 1,
    "tags": [
      "places & travel"
    ],
    "meta": {
      "gender": "masculine"
    },
    "confidence": "validated"
  },
  {
    "id": "word-grad",
    "kind": "vocab",
    "prompt": "city",
    "answer": "град",
    "translit": "grad",
    "gloss": "city",
    "i1Level": 1,
    "tags": [
      "places & travel"
    ],
    "meta": {
      "gender": "masculine"
    },
    "confidence": "validated"
  },
  {
    "id": "word-hotel",
    "kind": "vocab",
    "prompt": "hotel",
    "answer": "хотел",
    "translit": "hotel",
    "gloss": "hotel",
    "i1Level": 1,
    "tags": [
      "places & travel"
    ],
    "meta": {
      "gender": "masculine"
    },
    "confidence": "validated"
  },
  {
    "id": "word-pat",
    "kind": "vocab",
    "prompt": "road, way",
    "answer": "пат",
    "translit": "pat",
    "gloss": "road, way",
    "i1Level": 1,
    "tags": [
      "places & travel"
    ],
    "meta": {
      "gender": "masculine"
    },
    "confidence": "validated"
  },
  {
    "id": "word-ulica",
    "kind": "vocab",
    "prompt": "street",
    "answer": "улица",
    "translit": "ulica",
    "gloss": "street",
    "i1Level": 1,
    "tags": [
      "places & travel"
    ],
    "meta": {
      "gender": "feminine"
    },
    "confidence": "validated"
  },
  {
    "id": "word-voz",
    "kind": "vocab",
    "prompt": "train",
    "answer": "воз",
    "translit": "voz",
    "gloss": "train",
    "i1Level": 1,
    "tags": [
      "places & travel"
    ],
    "meta": {
      "gender": "masculine"
    },
    "confidence": "validated"
  },
  {
    "id": "word-moj",
    "kind": "vocab",
    "prompt": "my, mine",
    "answer": "мој",
    "translit": "moy",
    "gloss": "my, mine",
    "note": "possessive, agrees with masc. noun",
    "i1Level": 1,
    "tags": [
      "possessives"
    ],
    "confidence": "validated"
  },
  {
    "id": "word-nash",
    "kind": "vocab",
    "prompt": "our, ours",
    "answer": "наш",
    "translit": "nash",
    "gloss": "our, ours",
    "note": "1st person plural possessive",
    "i1Level": 1,
    "tags": [
      "possessives"
    ],
    "confidence": "validated"
  },
  {
    "id": "word-negov",
    "kind": "vocab",
    "prompt": "his",
    "answer": "негов",
    "translit": "negov",
    "gloss": "his",
    "note": "possessive pronoun (masc. owner)",
    "i1Level": 1,
    "tags": [
      "possessives"
    ],
    "confidence": "validated"
  },
  {
    "id": "word-nejzin",
    "kind": "vocab",
    "prompt": "her, hers",
    "answer": "нејзин",
    "translit": "neyzin",
    "gloss": "her, hers",
    "note": "possessive pronoun (fem. owner)",
    "i1Level": 1,
    "tags": [
      "possessives"
    ],
    "confidence": "validated"
  },
  {
    "id": "word-niven",
    "kind": "vocab",
    "prompt": "their, theirs",
    "answer": "нивен",
    "translit": "niven",
    "gloss": "their, theirs",
    "note": "3rd person plural possessive",
    "i1Level": 1,
    "tags": [
      "possessives"
    ],
    "confidence": "validated"
  },
  {
    "id": "word-tvoj",
    "kind": "vocab",
    "prompt": "your, yours (sg.)",
    "answer": "твој",
    "translit": "tvoy",
    "gloss": "your, yours (sg.)",
    "note": "possessive, informal singular",
    "i1Level": 1,
    "tags": [
      "possessives"
    ],
    "confidence": "validated"
  },
  {
    "id": "word-vash",
    "kind": "vocab",
    "prompt": "your, yours (pl.)",
    "answer": "ваш",
    "translit": "vash",
    "gloss": "your, yours (pl.)",
    "note": "2nd person plural/polite possessive",
    "i1Level": 1,
    "tags": [
      "possessives"
    ],
    "confidence": "validated"
  },
  {
    "id": "word-bez",
    "kind": "vocab",
    "prompt": "without",
    "answer": "без",
    "translit": "bez",
    "gloss": "without",
    "note": "preposition of absence",
    "i1Level": 1,
    "tags": [
      "prepositions"
    ],
    "confidence": "validated"
  },
  {
    "id": "word-do",
    "kind": "vocab",
    "prompt": "to, until, next to",
    "answer": "до",
    "translit": "do",
    "gloss": "to, until, next to",
    "note": "preposition indicating limit/proximity",
    "i1Level": 1,
    "tags": [
      "prepositions"
    ],
    "confidence": "validated"
  },
  {
    "id": "word-kaj",
    "kind": "vocab",
    "prompt": "at, to (someone's)",
    "answer": "кај",
    "translit": "kay",
    "gloss": "at, to (someone's)",
    "note": "preposition for being at a person/place",
    "i1Level": 1,
    "tags": [
      "prepositions"
    ],
    "confidence": "validated"
  },
  {
    "id": "word-na",
    "kind": "vocab",
    "prompt": "on, to, of",
    "answer": "на",
    "translit": "na",
    "gloss": "on, to, of",
    "note": "very common preposition; marks possession/indirect object",
    "i1Level": 1,
    "tags": [
      "prepositions"
    ],
    "confidence": "validated"
  },
  {
    "id": "word-nad",
    "kind": "vocab",
    "prompt": "above, over",
    "answer": "над",
    "translit": "nad",
    "gloss": "above, over",
    "note": "preposition of position",
    "i1Level": 1,
    "tags": [
      "prepositions"
    ],
    "confidence": "validated"
  },
  {
    "id": "word-od",
    "kind": "vocab",
    "prompt": "from, of",
    "answer": "од",
    "translit": "od",
    "gloss": "from, of",
    "note": "preposition of origin/source",
    "i1Level": 1,
    "tags": [
      "prepositions"
    ],
    "confidence": "validated"
  },
  {
    "id": "word-okolu",
    "kind": "vocab",
    "prompt": "around, about",
    "answer": "околу",
    "translit": "okolu",
    "gloss": "around, about",
    "note": "preposition of location/approximation",
    "i1Level": 1,
    "tags": [
      "prepositions"
    ],
    "confidence": "validated"
  },
  {
    "id": "word-po",
    "kind": "vocab",
    "prompt": "after, along, per",
    "answer": "по",
    "translit": "po",
    "gloss": "after, along, per",
    "note": "preposition with several meanings",
    "i1Level": 1,
    "tags": [
      "prepositions"
    ],
    "confidence": "validated"
  },
  {
    "id": "word-pod",
    "kind": "vocab",
    "prompt": "under",
    "answer": "под",
    "translit": "pod",
    "gloss": "under",
    "note": "preposition of position",
    "i1Level": 1,
    "tags": [
      "prepositions"
    ],
    "confidence": "validated"
  },
  {
    "id": "word-pred",
    "kind": "vocab",
    "prompt": "before, in front of",
    "answer": "пред",
    "translit": "pred",
    "gloss": "before, in front of",
    "note": "preposition of time/place",
    "i1Level": 1,
    "tags": [
      "prepositions"
    ],
    "confidence": "validated"
  },
  {
    "id": "word-so",
    "kind": "vocab",
    "prompt": "with",
    "answer": "со",
    "translit": "so",
    "gloss": "with",
    "note": "preposition of accompaniment/instrument",
    "i1Level": 1,
    "tags": [
      "prepositions"
    ],
    "confidence": "validated"
  },
  {
    "id": "word-vo",
    "kind": "vocab",
    "prompt": "in, into",
    "answer": "во",
    "translit": "vo",
    "gloss": "in, into",
    "note": "preposition of location/direction",
    "i1Level": 1,
    "tags": [
      "prepositions"
    ],
    "confidence": "validated"
  },
  {
    "id": "word-za",
    "kind": "vocab",
    "prompt": "for, about",
    "answer": "за",
    "translit": "za",
    "gloss": "for, about",
    "note": "preposition of purpose/topic",
    "i1Level": 1,
    "tags": [
      "prepositions"
    ],
    "confidence": "validated"
  },
  {
    "id": "word-jas",
    "kind": "vocab",
    "prompt": "I",
    "answer": "јас",
    "translit": "yas",
    "gloss": "I",
    "note": "1st person singular pronoun",
    "i1Level": 1,
    "tags": [
      "pronouns"
    ],
    "confidence": "validated"
  },
  {
    "id": "word-nie",
    "kind": "vocab",
    "prompt": "we",
    "answer": "ние",
    "translit": "nie",
    "gloss": "we",
    "note": "1st person plural pronoun",
    "i1Level": 1,
    "tags": [
      "pronouns"
    ],
    "confidence": "validated"
  },
  {
    "id": "word-taa",
    "kind": "vocab",
    "prompt": "she",
    "answer": "таа",
    "translit": "taa",
    "gloss": "she",
    "note": "3rd person feminine pronoun",
    "i1Level": 1,
    "tags": [
      "pronouns"
    ],
    "confidence": "validated"
  },
  {
    "id": "word-ti",
    "kind": "vocab",
    "prompt": "you (sg.)",
    "answer": "ти",
    "translit": "ti",
    "gloss": "you (sg.)",
    "note": "2nd person singular, informal",
    "i1Level": 1,
    "tags": [
      "pronouns"
    ],
    "confidence": "validated"
  },
  {
    "id": "word-tie",
    "kind": "vocab",
    "prompt": "they",
    "answer": "тие",
    "translit": "tie",
    "gloss": "they",
    "note": "3rd person plural pronoun",
    "i1Level": 1,
    "tags": [
      "pronouns"
    ],
    "confidence": "validated"
  },
  {
    "id": "word-toa",
    "kind": "vocab",
    "prompt": "it",
    "answer": "тоа",
    "translit": "toa",
    "gloss": "it",
    "note": "3rd person neuter pronoun",
    "i1Level": 1,
    "tags": [
      "pronouns"
    ],
    "confidence": "validated"
  },
  {
    "id": "word-toj",
    "kind": "vocab",
    "prompt": "he",
    "answer": "тој",
    "translit": "toy",
    "gloss": "he",
    "note": "3rd person masculine pronoun",
    "i1Level": 1,
    "tags": [
      "pronouns"
    ],
    "confidence": "validated"
  },
  {
    "id": "word-vie",
    "kind": "vocab",
    "prompt": "you (pl./formal)",
    "answer": "вие",
    "translit": "vie",
    "gloss": "you (pl./formal)",
    "note": "2nd person plural or polite",
    "i1Level": 1,
    "tags": [
      "pronouns"
    ],
    "confidence": "validated"
  },
  {
    "id": "word-chij",
    "kind": "vocab",
    "prompt": "whose",
    "answer": "чиј",
    "translit": "chiy",
    "gloss": "whose",
    "note": "possessive interrogative; agrees in gender/number",
    "i1Level": 1,
    "tags": [
      "question words"
    ],
    "confidence": "validated"
  },
  {
    "id": "word-kade",
    "kind": "vocab",
    "prompt": "where",
    "answer": "каде",
    "translit": "kade",
    "gloss": "where",
    "note": "question word for location",
    "i1Level": 1,
    "tags": [
      "question words"
    ],
    "confidence": "validated"
  },
  {
    "id": "word-kako",
    "kind": "vocab",
    "prompt": "how",
    "answer": "како",
    "translit": "kako",
    "gloss": "how",
    "note": "question word; also 'as/like'",
    "i1Level": 1,
    "tags": [
      "question words"
    ],
    "confidence": "validated"
  },
  {
    "id": "word-koj",
    "kind": "vocab",
    "prompt": "who, which",
    "answer": "кој",
    "translit": "koy",
    "gloss": "who, which",
    "note": "interrogative/relative pronoun",
    "i1Level": 1,
    "tags": [
      "question words"
    ],
    "confidence": "validated"
  },
  {
    "id": "word-kolku",
    "kind": "vocab",
    "prompt": "how much/many",
    "answer": "колку",
    "translit": "kolku",
    "gloss": "how much/many",
    "note": "question word for quantity",
    "i1Level": 1,
    "tags": [
      "question words"
    ],
    "confidence": "validated"
  },
  {
    "id": "word-shto",
    "kind": "vocab",
    "prompt": "what",
    "answer": "што",
    "translit": "shto",
    "gloss": "what",
    "note": "question word; also relative pronoun 'that/which'",
    "i1Level": 1,
    "tags": [
      "question words"
    ],
    "confidence": "validated"
  },
  {
    "id": "word-zoshto",
    "kind": "vocab",
    "prompt": "why",
    "answer": "зошто",
    "translit": "zoshto",
    "gloss": "why",
    "note": "question word for reason",
    "i1Level": 1,
    "tags": [
      "question words"
    ],
    "confidence": "validated"
  },
  {
    "id": "word-ona",
    "kind": "vocab",
    "prompt": "that",
    "answer": "она",
    "translit": "ona",
    "gloss": "that",
    "note": "demonstrative, distal neuter",
    "i1Level": 1,
    "tags": [
      "this & that"
    ],
    "confidence": "validated"
  },
  {
    "id": "word-ova",
    "kind": "vocab",
    "prompt": "this",
    "answer": "ова",
    "translit": "ova",
    "gloss": "this",
    "note": "demonstrative, neuter/general",
    "i1Level": 1,
    "tags": [
      "this & that"
    ],
    "confidence": "validated"
  },
  {
    "id": "word-ovaa",
    "kind": "vocab",
    "prompt": "this",
    "answer": "оваа",
    "translit": "ovaa",
    "gloss": "this",
    "note": "demonstrative, feminine",
    "i1Level": 1,
    "tags": [
      "this & that"
    ],
    "confidence": "validated"
  },
  {
    "id": "word-ovoj",
    "kind": "vocab",
    "prompt": "this",
    "answer": "овој",
    "translit": "ovoy",
    "gloss": "this",
    "note": "demonstrative, masculine",
    "i1Level": 1,
    "tags": [
      "this & that"
    ],
    "confidence": "validated"
  },
  {
    "id": "word-chas",
    "kind": "vocab",
    "prompt": "hour, o'clock",
    "answer": "час",
    "translit": "chas",
    "gloss": "hour, o'clock",
    "i1Level": 1,
    "tags": [
      "time & days"
    ],
    "meta": {
      "gender": "masculine"
    },
    "confidence": "validated"
  },
  {
    "id": "word-den",
    "kind": "vocab",
    "prompt": "day",
    "answer": "ден",
    "translit": "den",
    "gloss": "day",
    "i1Level": 1,
    "tags": [
      "time & days"
    ],
    "meta": {
      "gender": "masculine"
    },
    "confidence": "validated"
  },
  {
    "id": "word-godina",
    "kind": "vocab",
    "prompt": "year",
    "answer": "година",
    "translit": "godina",
    "gloss": "year",
    "i1Level": 1,
    "tags": [
      "time & days"
    ],
    "meta": {
      "gender": "feminine"
    },
    "confidence": "validated"
  },
  {
    "id": "word-mesec",
    "kind": "vocab",
    "prompt": "month",
    "answer": "месец",
    "translit": "mesec",
    "gloss": "month",
    "i1Level": 1,
    "tags": [
      "time & days"
    ],
    "meta": {
      "gender": "masculine"
    },
    "confidence": "validated"
  },
  {
    "id": "word-nedela",
    "kind": "vocab",
    "prompt": "week, Sunday",
    "answer": "недела",
    "translit": "nedela",
    "gloss": "week, Sunday",
    "i1Level": 1,
    "tags": [
      "time & days"
    ],
    "meta": {
      "gender": "feminine"
    },
    "confidence": "validated"
  },
  {
    "id": "word-nokj",
    "kind": "vocab",
    "prompt": "night",
    "answer": "ноќ",
    "translit": "nokj",
    "gloss": "night",
    "i1Level": 1,
    "tags": [
      "time & days"
    ],
    "meta": {
      "gender": "feminine"
    },
    "confidence": "validated"
  },
  {
    "id": "word-utro",
    "kind": "vocab",
    "prompt": "morning",
    "answer": "утро",
    "translit": "utro",
    "gloss": "morning",
    "i1Level": 1,
    "tags": [
      "time & days"
    ],
    "meta": {
      "gender": "neuter"
    },
    "confidence": "validated"
  }
];
