// MACHINE-GENERATED by pipeline/src/run-words.ts (Opus 4.8). A themed set of high-frequency single
// Macedonian words that expand the flashcard vocabulary, deduped against the rest of the pack. Merged
// into `vocab` in index.ts. Spot-check before trusting as authoritative. Regenerate/grow with:
//   pipeline/node_modules/.bin/tsx pipeline/src/run-words.ts
import type { ReviewItem } from "@ll/pack-schema";

export const coreWords: ReviewItem[] = [
  {
    "id": "word-bolen",
    "kind": "vocab",
    "prompt": "sick",
    "answer": "болен",
    "translit": "bolen",
    "gloss": "sick",
    "i1Level": 1,
    "tags": [
      "body & health"
    ],
    "confidence": "validated"
  },
  {
    "id": "word-glava",
    "kind": "vocab",
    "prompt": "head",
    "answer": "глава",
    "translit": "glava",
    "gloss": "head",
    "i1Level": 1,
    "tags": [
      "body & health"
    ],
    "meta": {
      "gender": "feminine"
    },
    "confidence": "validated"
  },
  {
    "id": "word-lekar",
    "kind": "vocab",
    "prompt": "doctor",
    "answer": "лекар",
    "translit": "lekar",
    "gloss": "doctor",
    "i1Level": 1,
    "tags": [
      "body & health"
    ],
    "meta": {
      "gender": "masculine"
    },
    "confidence": "validated"
  },
  {
    "id": "word-noga",
    "kind": "vocab",
    "prompt": "leg, foot",
    "answer": "нога",
    "translit": "noga",
    "gloss": "leg, foot",
    "i1Level": 1,
    "tags": [
      "body & health"
    ],
    "meta": {
      "gender": "feminine"
    },
    "confidence": "validated"
  },
  {
    "id": "word-oko",
    "kind": "vocab",
    "prompt": "eye",
    "answer": "око",
    "translit": "oko",
    "gloss": "eye",
    "i1Level": 1,
    "tags": [
      "body & health"
    ],
    "meta": {
      "gender": "neuter"
    },
    "confidence": "validated"
  },
  {
    "id": "word-raka",
    "kind": "vocab",
    "prompt": "hand, arm",
    "answer": "рака",
    "translit": "raka",
    "gloss": "hand, arm",
    "i1Level": 1,
    "tags": [
      "body & health"
    ],
    "meta": {
      "gender": "feminine"
    },
    "confidence": "validated"
  },
  {
    "id": "word-dobar",
    "kind": "vocab",
    "prompt": "good",
    "answer": "добар",
    "translit": "dobar",
    "gloss": "good",
    "i1Level": 1,
    "tags": [
      "common adjectives"
    ],
    "confidence": "validated"
  },
  {
    "id": "word-golem",
    "kind": "vocab",
    "prompt": "big",
    "answer": "голем",
    "translit": "golem",
    "gloss": "big",
    "i1Level": 1,
    "tags": [
      "common adjectives"
    ],
    "confidence": "validated"
  },
  {
    "id": "word-losh",
    "kind": "vocab",
    "prompt": "bad",
    "answer": "лош",
    "translit": "losh",
    "gloss": "bad",
    "i1Level": 1,
    "tags": [
      "common adjectives"
    ],
    "confidence": "validated"
  },
  {
    "id": "word-mal",
    "kind": "vocab",
    "prompt": "small",
    "answer": "мал",
    "translit": "mal",
    "gloss": "small",
    "i1Level": 1,
    "tags": [
      "common adjectives"
    ],
    "confidence": "validated"
  },
  {
    "id": "word-nov",
    "kind": "vocab",
    "prompt": "new",
    "answer": "нов",
    "translit": "nov",
    "gloss": "new",
    "i1Level": 1,
    "tags": [
      "common adjectives"
    ],
    "confidence": "validated"
  },
  {
    "id": "word-star",
    "kind": "vocab",
    "prompt": "old",
    "answer": "стар",
    "translit": "star",
    "gloss": "old",
    "i1Level": 1,
    "tags": [
      "common adjectives"
    ],
    "confidence": "validated"
  },
  {
    "id": "word-studen",
    "kind": "vocab",
    "prompt": "cold",
    "answer": "студен",
    "translit": "studen",
    "gloss": "cold",
    "i1Level": 1,
    "tags": [
      "common adjectives"
    ],
    "confidence": "validated"
  },
  {
    "id": "word-topol",
    "kind": "vocab",
    "prompt": "warm",
    "answer": "топол",
    "translit": "topol",
    "gloss": "warm",
    "i1Level": 1,
    "tags": [
      "common adjectives"
    ],
    "confidence": "validated"
  },
  {
    "id": "word-doagjam",
    "kind": "vocab",
    "prompt": "come",
    "answer": "доаѓам",
    "translit": "doagjam",
    "gloss": "come",
    "i1Level": 1,
    "tags": [
      "common verbs"
    ],
    "confidence": "validated"
  },
  {
    "id": "word-imam",
    "kind": "vocab",
    "prompt": "have",
    "answer": "имам",
    "translit": "imam",
    "gloss": "have",
    "i1Level": 1,
    "tags": [
      "common verbs"
    ],
    "confidence": "validated"
  },
  {
    "id": "word-odam",
    "kind": "vocab",
    "prompt": "go, walk",
    "answer": "одам",
    "translit": "odam",
    "gloss": "go, walk",
    "note": "1st person present",
    "i1Level": 1,
    "tags": [
      "common verbs"
    ],
    "confidence": "validated"
  },
  {
    "id": "word-pijam",
    "kind": "vocab",
    "prompt": "drink",
    "answer": "пијам",
    "translit": "pijam",
    "gloss": "drink",
    "i1Level": 1,
    "tags": [
      "common verbs"
    ],
    "confidence": "validated"
  },
  {
    "id": "word-rabotam",
    "kind": "vocab",
    "prompt": "work",
    "answer": "работам",
    "translit": "rabotam",
    "gloss": "work",
    "i1Level": 1,
    "tags": [
      "common verbs"
    ],
    "confidence": "validated"
  },
  {
    "id": "word-spijam",
    "kind": "vocab",
    "prompt": "sleep",
    "answer": "спијам",
    "translit": "spijam",
    "gloss": "sleep",
    "i1Level": 1,
    "tags": [
      "common verbs"
    ],
    "confidence": "validated"
  },
  {
    "id": "word-vidam",
    "kind": "vocab",
    "prompt": "see",
    "answer": "видам",
    "translit": "vidam",
    "gloss": "see",
    "i1Level": 1,
    "tags": [
      "common verbs"
    ],
    "confidence": "validated"
  },
  {
    "id": "word-zboruvam",
    "kind": "vocab",
    "prompt": "speak",
    "answer": "зборувам",
    "translit": "zboruvam",
    "gloss": "speak",
    "i1Level": 1,
    "tags": [
      "common verbs"
    ],
    "confidence": "validated"
  },
  {
    "id": "word-znam",
    "kind": "vocab",
    "prompt": "know",
    "answer": "знам",
    "translit": "znam",
    "gloss": "know",
    "i1Level": 1,
    "tags": [
      "common verbs"
    ],
    "confidence": "validated"
  },
  {
    "id": "word-baba",
    "kind": "vocab",
    "prompt": "grandmother",
    "answer": "баба",
    "translit": "baba",
    "gloss": "grandmother",
    "i1Level": 1,
    "tags": [
      "family & people"
    ],
    "meta": {
      "gender": "feminine"
    },
    "confidence": "validated"
  },
  {
    "id": "word-chovek",
    "kind": "vocab",
    "prompt": "person, man",
    "answer": "човек",
    "translit": "chovek",
    "gloss": "person, man",
    "i1Level": 1,
    "tags": [
      "family & people"
    ],
    "meta": {
      "gender": "masculine"
    },
    "confidence": "validated"
  },
  {
    "id": "word-dedo",
    "kind": "vocab",
    "prompt": "grandfather",
    "answer": "дедо",
    "translit": "dedo",
    "gloss": "grandfather",
    "i1Level": 1,
    "tags": [
      "family & people"
    ],
    "meta": {
      "gender": "masculine"
    },
    "confidence": "validated"
  },
  {
    "id": "word-devojka",
    "kind": "vocab",
    "prompt": "girl",
    "answer": "девојка",
    "translit": "devojka",
    "gloss": "girl",
    "i1Level": 1,
    "tags": [
      "family & people"
    ],
    "meta": {
      "gender": "feminine"
    },
    "confidence": "validated"
  },
  {
    "id": "word-momche",
    "kind": "vocab",
    "prompt": "boy",
    "answer": "момче",
    "translit": "momche",
    "gloss": "boy",
    "i1Level": 1,
    "tags": [
      "family & people"
    ],
    "meta": {
      "gender": "neuter"
    },
    "confidence": "validated"
  },
  {
    "id": "word-prijatel",
    "kind": "vocab",
    "prompt": "friend",
    "answer": "пријател",
    "translit": "prijatel",
    "gloss": "friend",
    "i1Level": 1,
    "tags": [
      "family & people"
    ],
    "meta": {
      "gender": "masculine"
    },
    "confidence": "validated"
  },
  {
    "id": "word-jajce",
    "kind": "vocab",
    "prompt": "egg",
    "answer": "јајце",
    "translit": "jajce",
    "gloss": "egg",
    "i1Level": 1,
    "tags": [
      "food & drink"
    ],
    "meta": {
      "gender": "neuter"
    },
    "confidence": "validated"
  },
  {
    "id": "word-meso",
    "kind": "vocab",
    "prompt": "meat",
    "answer": "месо",
    "translit": "meso",
    "gloss": "meat",
    "i1Level": 1,
    "tags": [
      "food & drink"
    ],
    "meta": {
      "gender": "neuter"
    },
    "confidence": "validated"
  },
  {
    "id": "word-ovoshje",
    "kind": "vocab",
    "prompt": "fruit",
    "answer": "овошје",
    "translit": "ovoshje",
    "gloss": "fruit",
    "i1Level": 1,
    "tags": [
      "food & drink"
    ],
    "meta": {
      "gender": "neuter"
    },
    "confidence": "validated"
  },
  {
    "id": "word-riba",
    "kind": "vocab",
    "prompt": "fish",
    "answer": "риба",
    "translit": "riba",
    "gloss": "fish",
    "i1Level": 1,
    "tags": [
      "food & drink"
    ],
    "meta": {
      "gender": "feminine"
    },
    "confidence": "validated"
  },
  {
    "id": "word-shekjer",
    "kind": "vocab",
    "prompt": "sugar",
    "answer": "шеќер",
    "translit": "shekjer",
    "gloss": "sugar",
    "i1Level": 1,
    "tags": [
      "food & drink"
    ],
    "meta": {
      "gender": "masculine"
    },
    "confidence": "validated"
  },
  {
    "id": "word-sol",
    "kind": "vocab",
    "prompt": "salt",
    "answer": "сол",
    "translit": "sol",
    "gloss": "salt",
    "i1Level": 1,
    "tags": [
      "food & drink"
    ],
    "meta": {
      "gender": "feminine"
    },
    "confidence": "validated"
  },
  {
    "id": "word-zelenchuk",
    "kind": "vocab",
    "prompt": "vegetables",
    "answer": "зеленчук",
    "translit": "zelenchuk",
    "gloss": "vegetables",
    "i1Level": 1,
    "tags": [
      "food & drink"
    ],
    "meta": {
      "gender": "masculine"
    },
    "confidence": "validated"
  },
  {
    "id": "word-kluch",
    "kind": "vocab",
    "prompt": "key",
    "answer": "клуч",
    "translit": "kluch",
    "gloss": "key",
    "i1Level": 1,
    "tags": [
      "home & everyday objects"
    ],
    "meta": {
      "gender": "masculine"
    },
    "confidence": "validated"
  },
  {
    "id": "word-kukja",
    "kind": "vocab",
    "prompt": "house",
    "answer": "куќа",
    "translit": "kukja",
    "gloss": "house",
    "i1Level": 1,
    "tags": [
      "home & everyday objects"
    ],
    "meta": {
      "gender": "feminine"
    },
    "confidence": "validated"
  },
  {
    "id": "word-masa",
    "kind": "vocab",
    "prompt": "table",
    "answer": "маса",
    "translit": "masa",
    "gloss": "table",
    "i1Level": 1,
    "tags": [
      "home & everyday objects"
    ],
    "meta": {
      "gender": "feminine"
    },
    "confidence": "validated"
  },
  {
    "id": "word-prozorec",
    "kind": "vocab",
    "prompt": "window",
    "answer": "прозорец",
    "translit": "prozorec",
    "gloss": "window",
    "i1Level": 1,
    "tags": [
      "home & everyday objects"
    ],
    "meta": {
      "gender": "masculine"
    },
    "confidence": "validated"
  },
  {
    "id": "word-stan",
    "kind": "vocab",
    "prompt": "apartment",
    "answer": "стан",
    "translit": "stan",
    "gloss": "apartment",
    "i1Level": 1,
    "tags": [
      "home & everyday objects"
    ],
    "meta": {
      "gender": "masculine"
    },
    "confidence": "validated"
  },
  {
    "id": "word-stol",
    "kind": "vocab",
    "prompt": "chair",
    "answer": "стол",
    "translit": "stol",
    "gloss": "chair",
    "i1Level": 1,
    "tags": [
      "home & everyday objects"
    ],
    "meta": {
      "gender": "masculine"
    },
    "confidence": "validated"
  },
  {
    "id": "word-telefon",
    "kind": "vocab",
    "prompt": "phone",
    "answer": "телефон",
    "translit": "telefon",
    "gloss": "phone",
    "i1Level": 1,
    "tags": [
      "home & everyday objects"
    ],
    "meta": {
      "gender": "masculine"
    },
    "confidence": "validated"
  },
  {
    "id": "word-vrata",
    "kind": "vocab",
    "prompt": "door",
    "answer": "врата",
    "translit": "vrata",
    "gloss": "door",
    "i1Level": 1,
    "tags": [
      "home & everyday objects"
    ],
    "meta": {
      "gender": "feminine"
    },
    "confidence": "validated"
  },
  {
    "id": "word-cena",
    "kind": "vocab",
    "prompt": "price",
    "answer": "цена",
    "translit": "cena",
    "gloss": "price",
    "i1Level": 1,
    "tags": [
      "money & shopping"
    ],
    "meta": {
      "gender": "feminine"
    },
    "confidence": "validated"
  },
  {
    "id": "word-evtin",
    "kind": "vocab",
    "prompt": "cheap",
    "answer": "евтин",
    "translit": "evtin",
    "gloss": "cheap",
    "i1Level": 1,
    "tags": [
      "money & shopping"
    ],
    "confidence": "validated"
  },
  {
    "id": "word-pari",
    "kind": "vocab",
    "prompt": "money",
    "answer": "пари",
    "translit": "pari",
    "gloss": "money",
    "note": "plural only",
    "i1Level": 1,
    "tags": [
      "money & shopping"
    ],
    "meta": {
      "gender": "feminine"
    },
    "confidence": "validated"
  },
  {
    "id": "word-pazar",
    "kind": "vocab",
    "prompt": "market",
    "answer": "пазар",
    "translit": "pazar",
    "gloss": "market",
    "i1Level": 1,
    "tags": [
      "money & shopping"
    ],
    "meta": {
      "gender": "masculine"
    },
    "confidence": "validated"
  },
  {
    "id": "word-prodavnica",
    "kind": "vocab",
    "prompt": "shop",
    "answer": "продавница",
    "translit": "prodavnica",
    "gloss": "shop",
    "i1Level": 1,
    "tags": [
      "money & shopping"
    ],
    "meta": {
      "gender": "feminine"
    },
    "confidence": "validated"
  },
  {
    "id": "word-skap",
    "kind": "vocab",
    "prompt": "expensive",
    "answer": "скап",
    "translit": "skap",
    "gloss": "expensive",
    "i1Level": 1,
    "tags": [
      "money & shopping"
    ],
    "confidence": "validated"
  },
  {
    "id": "word-dozhd",
    "kind": "vocab",
    "prompt": "rain",
    "answer": "дожд",
    "translit": "dozhd",
    "gloss": "rain",
    "i1Level": 1,
    "tags": [
      "nature & weather"
    ],
    "meta": {
      "gender": "masculine"
    },
    "confidence": "validated"
  },
  {
    "id": "word-drvo",
    "kind": "vocab",
    "prompt": "tree",
    "answer": "дрво",
    "translit": "drvo",
    "gloss": "tree",
    "i1Level": 1,
    "tags": [
      "nature & weather"
    ],
    "meta": {
      "gender": "neuter"
    },
    "confidence": "validated"
  },
  {
    "id": "word-planina",
    "kind": "vocab",
    "prompt": "mountain",
    "answer": "планина",
    "translit": "planina",
    "gloss": "mountain",
    "i1Level": 1,
    "tags": [
      "nature & weather"
    ],
    "meta": {
      "gender": "feminine"
    },
    "confidence": "validated"
  },
  {
    "id": "word-sneg",
    "kind": "vocab",
    "prompt": "snow",
    "answer": "снег",
    "translit": "sneg",
    "gloss": "snow",
    "i1Level": 1,
    "tags": [
      "nature & weather"
    ],
    "meta": {
      "gender": "masculine"
    },
    "confidence": "validated"
  },
  {
    "id": "word-sonce",
    "kind": "vocab",
    "prompt": "sun",
    "answer": "сонце",
    "translit": "sonce",
    "gloss": "sun",
    "i1Level": 1,
    "tags": [
      "nature & weather"
    ],
    "meta": {
      "gender": "neuter"
    },
    "confidence": "validated"
  },
  {
    "id": "word-veter",
    "kind": "vocab",
    "prompt": "wind",
    "answer": "ветер",
    "translit": "veter",
    "gloss": "wind",
    "i1Level": 1,
    "tags": [
      "nature & weather"
    ],
    "meta": {
      "gender": "masculine"
    },
    "confidence": "validated"
  },
  {
    "id": "word-aerodrom",
    "kind": "vocab",
    "prompt": "airport",
    "answer": "аеродром",
    "translit": "aerodrom",
    "gloss": "airport",
    "i1Level": 1,
    "tags": [
      "places & travel"
    ],
    "meta": {
      "gender": "masculine"
    },
    "confidence": "validated"
  },
  {
    "id": "word-grad",
    "kind": "vocab",
    "prompt": "city",
    "answer": "град",
    "translit": "grad",
    "gloss": "city",
    "i1Level": 1,
    "tags": [
      "places & travel"
    ],
    "meta": {
      "gender": "masculine"
    },
    "confidence": "validated"
  },
  {
    "id": "word-hotel",
    "kind": "vocab",
    "prompt": "hotel",
    "answer": "хотел",
    "translit": "hotel",
    "gloss": "hotel",
    "i1Level": 1,
    "tags": [
      "places & travel"
    ],
    "meta": {
      "gender": "masculine"
    },
    "confidence": "validated"
  },
  {
    "id": "word-pat",
    "kind": "vocab",
    "prompt": "road, way",
    "answer": "пат",
    "translit": "pat",
    "gloss": "road, way",
    "i1Level": 1,
    "tags": [
      "places & travel"
    ],
    "meta": {
      "gender": "masculine"
    },
    "confidence": "validated"
  },
  {
    "id": "word-ulica",
    "kind": "vocab",
    "prompt": "street",
    "answer": "улица",
    "translit": "ulica",
    "gloss": "street",
    "i1Level": 1,
    "tags": [
      "places & travel"
    ],
    "meta": {
      "gender": "feminine"
    },
    "confidence": "validated"
  },
  {
    "id": "word-voz",
    "kind": "vocab",
    "prompt": "train",
    "answer": "воз",
    "translit": "voz",
    "gloss": "train",
    "i1Level": 1,
    "tags": [
      "places & travel"
    ],
    "meta": {
      "gender": "masculine"
    },
    "confidence": "validated"
  },
  {
    "id": "word-chas",
    "kind": "vocab",
    "prompt": "hour, o'clock",
    "answer": "час",
    "translit": "chas",
    "gloss": "hour, o'clock",
    "i1Level": 1,
    "tags": [
      "time & days"
    ],
    "meta": {
      "gender": "masculine"
    },
    "confidence": "validated"
  },
  {
    "id": "word-den",
    "kind": "vocab",
    "prompt": "day",
    "answer": "ден",
    "translit": "den",
    "gloss": "day",
    "i1Level": 1,
    "tags": [
      "time & days"
    ],
    "meta": {
      "gender": "masculine"
    },
    "confidence": "validated"
  },
  {
    "id": "word-godina",
    "kind": "vocab",
    "prompt": "year",
    "answer": "година",
    "translit": "godina",
    "gloss": "year",
    "i1Level": 1,
    "tags": [
      "time & days"
    ],
    "meta": {
      "gender": "feminine"
    },
    "confidence": "validated"
  },
  {
    "id": "word-mesec",
    "kind": "vocab",
    "prompt": "month",
    "answer": "месец",
    "translit": "mesec",
    "gloss": "month",
    "i1Level": 1,
    "tags": [
      "time & days"
    ],
    "meta": {
      "gender": "masculine"
    },
    "confidence": "validated"
  },
  {
    "id": "word-nedela",
    "kind": "vocab",
    "prompt": "week, Sunday",
    "answer": "недела",
    "translit": "nedela",
    "gloss": "week, Sunday",
    "i1Level": 1,
    "tags": [
      "time & days"
    ],
    "meta": {
      "gender": "feminine"
    },
    "confidence": "validated"
  },
  {
    "id": "word-nokj",
    "kind": "vocab",
    "prompt": "night",
    "answer": "ноќ",
    "translit": "nokj",
    "gloss": "night",
    "i1Level": 1,
    "tags": [
      "time & days"
    ],
    "meta": {
      "gender": "feminine"
    },
    "confidence": "validated"
  },
  {
    "id": "word-utro",
    "kind": "vocab",
    "prompt": "morning",
    "answer": "утро",
    "translit": "utro",
    "gloss": "morning",
    "i1Level": 1,
    "tags": [
      "time & days"
    ],
    "meta": {
      "gender": "neuter"
    },
    "confidence": "validated"
  }
];
