// Derives the CHAPTER SPINE from the curriculum the architect already produced — no LLM, instant, free.
// The 12 curriculum units are the chapters; every generated artifact already encodes its unit in its id
// (`gen-<unit>`, `gen-<unit>-story`, `gen-<unit>-v3`, …) or in `tags`, so this only names them, fixes
// their order, and records the two things the ids can't express:
//   • wordTags  — which semantic buckets of the hand-authored core word list (words.ts: "food & drink",
//                 "numbers", …) each chapter teaches, so those 150 words get a home in the spine;
//   • extraIds  — hand-authored artifacts that predate the pipeline's id convention.
// Writes packages/pack-mk/src/chapters.ts.
//
// Run:  pipeline/node_modules/.bin/tsx pipeline/src/run-chapters.ts
import { readFileSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import type { Chapter, CefrBand } from "@ll/pack-schema";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..", "..");
const CURRICULUM = join(ROOT, "pipeline", "output", "curriculum-mk.json");
const OUT = join(ROOT, "packages", "pack-mk", "src", "chapters.ts");

interface CurriculumFile {
  stages: { stage: number; name: string; cefr: CefrBand; goal: string }[];
  sequence: string[];
  units: { id: string; stage: number; title: string; cefr: CefrBand; situation: string }[];
}
const curriculum: CurriculumFile = JSON.parse(readFileSync(CURRICULUM, "utf8"));

// Short labels for chips/headings, where the full unit title ("Café & bar: order and pay (the anchor)")
// is too long. Also the display order key for the Library.
const SHORT: Record<string, string> = {
  "s0-repair": "Repair kit",
  "s0-greet": "Greetings & politeness",
  "s0-survive": "Survival words & numbers",
  "s1-cafe-order": "Café & bar",
  "s1-greet-intro": "Introductions",
  "s1-market": "At the market",
  "s1-directions": "Directions",
  "s2-smalltalk": "Small talk & opinions",
  "s2-pasttime": "Past & future",
  "s2-home-family": "Home, family & work",
  "s2-arrange": "Phone & arranging",
  "s2-problems": "Problems & complaints",
};

// The hand-authored core word list (packages/pack-mk/src/words.ts) is tagged semantically, not by unit.
// Each bucket is assigned to the chapter whose situation actually uses it, so browsing a chapter shows
// its words. Every tag in words.ts must appear exactly once here (asserted below).
const WORD_TAGS: Record<string, string[]> = {
  "s0-repair": ["question words"],
  "s0-greet": ["pronouns", "this & that", "greeting", "social"],
  "s0-survive": ["numbers", "common adverbs"],
  "s1-cafe-order": ["food & drink", "drinks", "ordering", "paying"],
  "s1-greet-intro": ["common verbs", "introductions"],
  "s1-market": ["money & shopping", "common adjectives", "shopping"],
  "s1-directions": ["places & travel", "prepositions", "directions"],
  "s2-smalltalk": ["nature & weather", "conjunctions", "small-talk"],
  "s2-pasttime": ["time & days"],
  "s2-arrange": ["phone"],
  "s2-home-family": ["family & people", "home & everyday objects", "possessives"],
  "s2-problems": ["body & health"],
};

// Hand-authored content that predates `gen-<unit>` ids, mapped onto the chapter it belongs with.
const EXTRA_IDS: Record<string, string[]> = {
  "s1-cafe-order": ["bar-order-a-drink", "ana-coffee", "cafe", "cafe-order-gap", "w-order-coffee"],
  "s1-greet-intro": ["bar-small-talk", "gen-introductions", "w-greet-name", "w-from"],
  "s1-market": ["gen-shopping", "w-ask-price"],
  "s1-directions": ["gen-directions"],
  "s2-arrange": ["gen-phone"],
};
const chapters: Chapter[] = curriculum.sequence.map((id, i) => {
  const unit = curriculum.units.find((u) => u.id === id);
  if (!unit) throw new Error(`curriculum.sequence references unknown unit "${id}"`);
  const stage = curriculum.stages.find((s) => s.stage === unit.stage);
  return {
    id,
    order: i + 1,
    stage: unit.stage,
    stageTitle: stage?.name ?? `Stage ${unit.stage}`,
    title: unit.title,
    shortTitle: SHORT[id] ?? unit.title,
    cefr: unit.cefr,
    goal: unit.situation,
    ...(EXTRA_IDS[id] ? { extraIds: EXTRA_IDS[id] } : {}),
    ...(WORD_TAGS[id] ? { wordTags: WORD_TAGS[id] } : {}),
  };
});

// Guard: a word tag assigned to two chapters would put the same words in two places.
const seen = new Map<string, string>();
for (const c of chapters) {
  for (const t of c.wordTags ?? []) {
    if (seen.has(t)) throw new Error(`word tag "${t}" claimed by both ${seen.get(t)} and ${c.id}`);
    seen.set(t, c.id);
  }
}

const header =
  `// MACHINE-GENERATED by pipeline/src/run-chapters.ts from pipeline/output/curriculum-mk.json.\n` +
  `// The course spine: 12 ordered chapters over content that already exists (artifacts join by the\n` +
  `// \`gen-<chapterId>\` id convention / tags — see packages/core/src/chapters). Edit the maps in\n` +
  `// run-chapters.ts and re-run; don't hand-edit this file.\n` +
  `import type { Chapter } from "@ll/pack-schema";\n\n` +
  `export const chapters: Chapter[] = ${JSON.stringify(chapters, null, 2)};\n`;
writeFileSync(OUT, header);
console.log(`Wrote ${chapters.length} chapters to ${OUT}:`);
for (const c of chapters) console.log(`  ${String(c.order).padStart(2)}. [s${c.stage} ${c.cefr}] ${c.shortTitle} — ${c.title}`);
