// Offline generator: a themed set of high-frequency SINGLE Macedonian words to expand the flashcard
// vocabulary (the served set is thin on single words — mostly phrases). Opus, deduped against the
// existing pack vocab. Writes packages/pack-mk/src/words.ts (export `coreWords: ReviewItem[]`), merged
// into the pack in index.ts. Idempotent-ish: regenerating overwrites; pass a higher TARGET to grow.
//
// Run:  pipeline/node_modules/.bin/tsx pipeline/src/run-words.ts
import "./env.js";
import { writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import type { ReviewItem } from "@ll/pack-schema";
import { macedonian } from "@ll/pack-mk";
import { normalize } from "@ll/core/familiarity";
import { structuredCall, MODELS } from "@ll/core/llm";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..", "..");
const OUT = join(ROOT, "packages", "pack-mk", "src", "words.ts");
const TARGET = 60;

const THEMES = [
  "family & people", "food & drink", "home & everyday objects", "common verbs", "common adjectives",
  "time & days", "places & travel", "body & health", "nature & weather", "money & shopping",
];

const pack = macedonian;
const existing = new Set(pack.vocab.map((v) => normalize(v.answer)));

const SCHEMA: Record<string, unknown> = {
  type: "object",
  additionalProperties: false,
  properties: {
    words: {
      type: "array",
      items: {
        type: "object",
        additionalProperties: false,
        properties: {
          answer: { type: "string", description: "The Macedonian word (Cyrillic), a SINGLE word — no phrases, no spaces." },
          translit: { type: "string", description: "Romanization." },
          gloss: { type: "string", description: "Concise English meaning (1-3 words)." },
          gender: { type: "string", description: "For a NOUN only: masculine | feminine | neuter. Empty string otherwise." },
          theme: { type: "string", description: "One of the given themes." },
          note: { type: "string", description: "Optional short usage/stress note, or empty string." },
        },
        required: ["answer", "translit", "gloss", "gender", "theme", "note"],
      },
    },
  },
  required: ["words"],
};

const SYSTEM =
  `You are an expert Macedonian teacher choosing the most useful HIGH-FREQUENCY vocabulary for an absolute beginner. ` +
  `Return about ${TARGET} common SINGLE words (no phrases, no multi-word entries, no proper nouns), spread across these themes: ${THEMES.join(", ")}. ` +
  `Aim for roughly equal coverage per theme. For each: the standard Macedonian word (Cyrillic), an accurate romanization, a concise English gloss, the gender for nouns only (else ""), the theme, and an optional short note. ` +
  `Use correct, natural, standard Macedonian (proper gender, standard forms). Prefer everyday words a beginner meets first (e.g. common nouns, the most common verbs in dictionary form, basic adjectives).`;

const excludeList = [...pack.vocab].map((v) => v.answer).join(", ");

const { data, costUsd } = await structuredCall<{ words: { answer: string; translit: string; gloss: string; gender: string; theme: string; note: string }[] }>({
  model: MODELS.offline,
  system: SYSTEM,
  user: `Do NOT include any of these already-known entries (or trivial inflections of them):\n${excludeList}\n\nGive ~${TARGET} new high-frequency single words across the themes.`,
  schema: SCHEMA,
  maxTokens: 8000,
});

// Validate + dedup: single token, Cyrillic, not already known, no dupes within the batch.
const seen = new Set<string>();
const isCyrillic = (s: string) => /[Ѐ-ӿ]/.test(s);
const items: ReviewItem[] = [];
let skipped = 0;
for (const w of data.words) {
  const answer = w.answer.trim();
  const key = normalize(answer);
  if (!answer || /\s/.test(answer) || !isCyrillic(answer) || existing.has(key) || seen.has(key)) { skipped++; continue; }
  seen.add(key);
  const slug = (w.translit || key).toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "") || `w${items.length}`;
  items.push({
    id: `word-${slug}`,
    kind: "vocab",
    prompt: w.gloss,
    answer,
    translit: w.translit,
    gloss: w.gloss,
    ...(w.note?.trim() ? { note: w.note.trim() } : {}),
    i1Level: 1,
    tags: [w.theme || "core"],
    ...(w.gender?.trim() ? { meta: { gender: w.gender.trim() } } : {}),
    confidence: "validated" as const,
  });
}

// Stable order: by theme, then by translit, so the file diffs minimally on regen.
items.sort((a, b) => (a.tags[0]! + a.translit).localeCompare(b.tags[0]! + b.translit));

const header =
  `// MACHINE-GENERATED by pipeline/src/run-words.ts (Opus 4.8). A themed set of high-frequency single\n` +
  `// Macedonian words that expand the flashcard vocabulary, deduped against the rest of the pack. Merged\n` +
  `// into \`vocab\` in index.ts. Spot-check before trusting as authoritative. Regenerate/grow with:\n` +
  `//   pipeline/node_modules/.bin/tsx pipeline/src/run-words.ts\n` +
  `import type { ReviewItem } from "@ll/pack-schema";\n\n` +
  `export const coreWords: ReviewItem[] = ${JSON.stringify(items, null, 2)};\n`;
writeFileSync(OUT, header);

const byTheme = items.reduce<Record<string, number>>((a, i) => ((a[i.tags[0]!] = (a[i.tags[0]!] || 0) + 1), a), {});
console.log(`Wrote ${items.length} words to ${OUT} (skipped ${skipped}). $${costUsd.toFixed(4)}.`);
console.log("by theme:", JSON.stringify(byTheme));
